docs/setup-and-installing.md
Fixed bad path to UE4 fork.
https://improbableio.atlassian.net/browse/UNR-479
Primary reviewer:
@oblm
=> UNR-479: Fix UE4 fork path

docs/features.md, docs/readme.md
I added the bit in the red rectangle as a separate bullet point. @Vatyx please confirm this is right.
=> Update the features page

README.md, docs/content/directory-structure.md, docs/content/interop.md, docs/readme.md, docs/setup-and-installing.md
Small docs edits
Some link checking.
Is docs.
@anne-edwards
=> Small docs edits

README.md, docs/content/directory-structure.md, docs/content/generating-a-snapshot.md, docs/content/glossary.md, docs/content/handover-between-server-workers.md, docs/content/helper-scripts.md, docs/content/interop.md, docs/content/porting-unreal-project-to-gdk.md, docs/content/singleton-actors.md, docs/content/supported-replicated-types.md, docs/content/toolbar.md, docs/content/troubleshooting.md, docs/contributions/unreal-gdk-coding-standards.md, docs/features.md, docs/known-issues.md, docs/readme.md, docs/setup-and-installing.md
Fix of all broken links in the GDK docs detected by Jamies tool.
https://improbableio.atlassian.net/browse/UNR-469
@ElleEss @anne-edwards @Vatyx
=> UNR-469: Docs/link fixes

README.md
=> Added feature list link in the readme.

Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorGenerateSnapshot.cpp, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorUtils.cpp, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorUtils.h
-------
This PR creates a common utils file for the plugin for managing `FConfigFile`.
Both codegen and snapshot work as previously.
@Vatyx @danielimprobable 
Ticket link: https://improbableio.atlassian.net/browse/UNR-464
=> UNR-464 - common plugin utils

README.md
Added troubleshooting link to main page for easy access.
@ElleEss @anne-edwards
=> Add troubleshooting link to main page

README.md
This adds a link to the definition of "module" that we're using in the ReadMe. This clarity is necessary as there are multiple types of modules (Editor Modules for example), as well as the generic programming concept of a module, to confuse this with.
I also change Autumn to Fall because USA!
None
=> Link to a definition of modules.

Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorInteropCodeGenerator.h
-------
Fixed compilation error in the GDK plugin
Compiled and ran locally
@m-samiec
=> Fixed compilation error

Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.h, Source/SpatialGDK/Public/SpatialTypeBinding.h
Added support for static arrays in handover data
Jira: https://improbableio.atlassian.net/projects/UNR/issues/UNR-282
PR for TestSuite: https://github.com/spatialos/UnrealGDKTestSuite/pull/93
PR for TPS: https://github.com/spatialos/UnrealGDKThirdPersonShooter/pull/21
Added handover static arrays to testsuite and verified data correctly transitioned. 
No documentation needed.
@danielimprobable @wanqizhu @mpmisko
=> UNR-282: Added support for static arrays in handover data

docs/content/porting-unreal-project-to-gdk.md
Fixes a few small outdated things in the porting guide and adjusts it for the changes brought by UNR-466.
Went through the porting guide manually.
@danielimprobable
=> Adjust porting guide for UNR-466

Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorGenerateSnapshot.cpp, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarSettings.cpp, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarSettings.h
-------
Saving snapshots in the correct place was broken. This PR fixes it with a few additional refactors in
`SpatialGDKEditorGenerateSnapshot.cpp`.
Snapshot generation works as expected.
=> Fix default snapshot path

docs/content/interop.md, docs/content/singleton-actors.md, docs/content/troubleshooting.md
Updated troubleshooting the handle out of date UHT.
@ElleEss @anne-edwards
=> Updated doc

Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarSettings.cpp, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarSettings.h
-------
We were not specifying settings paths correctly. We used engine paths instead of the project root. This PR fixes that.
@danielimprobable
=> fix relative paths

Source/SpatialGDK/Public/Utils/SchemaDatabase.h
=> Add missing include

Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SchemaGenerator.cpp, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.cpp, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, Source/SpatialGDK/Private/Interop/SpatialSender.cpp, Source/SpatialGDK/Private/Interop/SpatialTypebindingManager.cpp, Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h, Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h, Source/SpatialGDK/Public/Schema/UnrealMetadata.h, Source/SpatialGDK/Public/SpatialGDKLoader.h, Source/SpatialGDK/Public/Utils/SchemaDatabase.h
Fix loading worker.dll
Spaces after for and if
Naming things
=> Style adjustments and fixes

Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, Source/SpatialGDK/Private/Interop/SpatialSender.cpp, Source/SpatialGDK/Private/Interop/SpatialTypebindingManager.cpp, Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, Source/SpatialGDK/Public/Interop/SpatialTypebindingManager.h
Ported changes to dynamic branch.
Ran test suite.
Also ran my local ability system tests.
=> Port subobject changes to dynamic typebindings

Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp
@improbable-valentyn please merge this in once you've looked at it.
=> Fixed order of component ids

Source/SpatialGDK/Private/SpatialNetDriver.cpp, Source/SpatialGDK/Public/SpatialNetDriver.h
Readds UNR-518 when the engine build is ready.
=> Readd UNR-518

BuildGDK.bat, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp, Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, Source/SpatialGDK/Private/Interop/SpatialSender.cpp, Source/SpatialGDK/Private/Interop/SpatialTypebindingManager.cpp, Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h, Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h, Source/SpatialGDK/Public/Interop/SpatialView.h, Source/SpatialGDK/Public/Schema/UnrealObjectRef.h, Source/SpatialGDK/Public/SpatialConstants.h, Source/SpatialGDK/Public/Utils/EntityRegistry.h
-------
Fixes for compilation errors on Linux and warnings.
Compiles against the [TestSuite branch](https://github.com/spatialos/UnrealGDKTestSuite/pull/104) on both windows and linux
No Documentation required.
@improbable-valentyn @mironec
=> UNR-559: Fix warnings and enable Linux compilation (WIP)

SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp, SpatialGDK/Source/Public/Schema/UnrealObjectRef.h, SpatialGDK/Source/Public/Utils/SchemaOption.h, SpatialGDKEditorToolbar/Source/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp, SpatialGDKEditorToolbar/Source/Private/InteropCodeGenerator/TypeStructure.cpp
-------
Style fixes.
@Vatyx @joshuahuburn
=> Fix style, add template GetTypeHash

Setup.bat
-------
Removed the download of the old worker SDK include files and removed a reference to the old codegen.version file.
Built testsuite successfully against this PR.
None required.
=> Cleanup of Setup.bat

SpatialGDK/Source/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/Public/Interop/Connection/SpatialWorkerConnection.h
-------
Add WorkerId accessor to SpatialWorkerConnection.
Required to fix up ThirdPersonShooter.
n/a
=> Add Worker ID to SpatialWorkerConnection.

SpatialGDK/Documentation/contributions/unreal-gdk-coding-standards.md, SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/Private/EngineClasses/SpatialNetBitReader.cpp, SpatialGDK/Source/Private/EngineClasses/SpatialNetBitWriter.cpp, SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/Private/Interop/SpatialView.cpp, SpatialGDK/Source/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/Public/EngineClasses/SpatialNetBitReader.h, SpatialGDK/Source/Public/EngineClasses/SpatialNetBitWriter.h, SpatialGDK/Source/Public/EngineClasses/SpatialPackageMapClient.h, SpatialGDK/Source/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/Public/Interop/SpatialView.h, SpatialGDK/Source/Public/Schema/Component.h, SpatialGDK/Source/Public/Schema/DynamicComponent.h, SpatialGDK/Source/Public/Schema/Rotation.h, SpatialGDK/Source/Public/Schema/StandardLibrary.h, SpatialGDK/Source/Public/Schema/UnrealMetadata.h, SpatialGDK/Source/Public/Schema/UnrealObjectRef.h, SpatialGDK/Source/Public/SpatialConstants.h, SpatialGDK/Source/Public/Utils/ComponentReader.h, SpatialGDK/Source/Public/Utils/SchemaOption.h, SpatialGDK/Source/Public/Utils/SchemaUtils.h, SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
-------
Due our decision to wrap non-Unreal classes in namespaces, this pr introduces these namespaces and updates the coding guidelines
Compile fine in test suite.
Coding guidelines updated
@improbable-valentyn @m-samiec @Vatyx
=> Added namespaces and update to our coding guidelines.

SpatialGDK/Source/Private/EngineClasses/SpatialGameInstance.cpp, SpatialGDK/Source/SpatialGDK.Build.cs
-------
Get SpatialNetworking flag from settings instead of engine so we can remove that function from the engine.
@m-samiec
=> Get SpatialNetworking flag from settings

SpatialGDK/Source/Private/EngineClasses/SpatialNetBitReader.cpp, SpatialGDK/Source/Private/EngineClasses/SpatialNetBitWriter.cpp, SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/Public/EngineClasses/SpatialNetBitReader.h, SpatialGDK/Source/Public/EngineClasses/SpatialNetBitWriter.h, SpatialGDK/Source/Public/EngineClasses/SpatialPackageMapClient.h, SpatialGDK/Source/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/Public/Schema/UnrealObjectRef.h, SpatialGDK/Source/Public/SpatialConstants.h, SpatialGDK/Source/Public/Utils/ComponentReader.h, SpatialGDK/Source/Public/Utils/SchemaUtils.h
-------
Fix Linux build support by removing improbable namespace around UnrealObjectRef
Please discuss if you disagree with this change.
Builds on Linux
@danielimprobable @davedolben
=> Fix Linux build support by removing improbable namespace around UnrealObjectRef

SpatialGDKEditorToolbar/Source/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp, SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbarSettings.cpp, SpatialGDKEditorToolbar/Source/Public/SpatialGDKEditorToolbarSettings.h
Added setting for generating all classes if toggled on.
=> Made switch for generating all classes

SpatialGDK/Source/Private/Interop/Connection/SpatialWorkerConnection.cpp
-------
Fix deployment list error printing garbage text.
Tested when attempting to `ClientTravel` to a cloud deployment.
=> Fix deployment list error printing garbage text

SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/Public/Interop/SpatialSender.h
This reverts commit 47ee376c7f3d7f7da83a0242e6b76ded7a275600.
-------
Revent UNR-556 because it causes crashes in Scavengers.
=> Revert "[UNR-556] Resend reliable RPCs (#367)"

SpatialGDK/Source/Public/Interop/Connection/ConnectionConfig.h, SpatialGDK/Source/Public/Schema/UnrealMetadata.h
Midwinter ran into build issue with the latest master due to missing includes. This fixes it.
=> Fix missing includes 

SpatialGDK/Extras/schema/spawner.schema, SpatialGDK/Extras/schema/unreal_metadata.schema
-------
Fixed some of the warnings produced by the schemas
=> Removed unused schema references

SpatialGDK/Source/Private/Utils/ComponentFactory.cpp
This is a temporary work around for trying to add a startup actor to a snapshot and an object wants to be assign a NetGUID. I've added a ticket for this which is referenced in a comment.
=> Fix crash in snapshot generator

SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbar.cpp, SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar.Build.cs
Ensure spatial networking is on for schema generation.
Drive-by warning fix.
@improbable-valentyn @danielimprobable
=> Ensure spatial networking is on for schema gen

SpatialGDK/Documentation/setup-and-installing.md
Also fix 'Generate Schema' -> 'Schema'.
=> Add missing snapshot gen step to docs.

SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
This PR will automatically generate schema for all supported classes, going beyond just Actors and ActorComponents.
=> Generate schema for UObjects automatically

SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/Public/EngineClasses/SpatialNetDriver.h, SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Fixed references to other actors for snapshot entities.
Tried referencing other entities in the world, replicated and not replicated, and the proper UnrealObjRefs were generated.
@improbable-valentyn @danielimprobable
=> Working UnrealObjRefs for Startup Actors

SpatialGDK/Source/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/Public/Interop/SpatialPlayerSpawner.h
-------
See title.
Build locally.
n/a
=> Fixed IWYU issues in SpatialSender.cpp and SpatialPlayerSpawner.h

SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbar.cpp, SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbarCommands.cpp, SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbarStyle.cpp, SpatialGDKEditorToolbar/Source/Public/SpatialGDKEditorToolbar.h, SpatialGDKEditorToolbar/Source/Public/SpatialGDKEditorToolbarCommands.h
Also moved swapped the order of the schema and snapshot buttons to more conform to the order you'd run each command.
@danielimprobable @joshuahuburn
=> Prevent crash when running snapshot and schema at the same time

README.md, SpatialGDK/Documentation/content/glossary.md, SpatialGDK/Documentation/index.md, SpatialGDK/Documentation/setup-and-installing.md, SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/Private/Interop/SpatialDispatcher.cpp, SpatialGDK/Source/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/Public/EngineClasses/SpatialPackageMapClient.h, SpatialGDK/Source/Public/Utils/RepLayoutUtils.h, SpatialGDK/Source/SpatialGDK.Build.cs, SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.cpp, SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/TypeStructure.cpp, SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/CodeWriter.h, SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar.Build.cs
Changes required to run on 420.
420 engine branch: https://github.com/improbableio/UnrealEngine/tree/4.20-SpatialOSUnrealGDK
Test suite PR: https://github.com/spatialos/UnrealGDKTestSuite/pull/112
TPS PR: https://github.com/spatialos/UnrealGDKThirdPersonShooter/pull/26
Ran TestSuite, and all tests ran.
Documentation updated to point to the 420 branch.
@girayimprobable @danielimprobable
=> Upgrade to 4.20

SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
This will make sure both AI Characters and Player Characters will have the same spatial position.
@m-samiec
=> Made any controller match its pawn's position.

SpatialGDK/Documentation/content/generating-a-snapshot.md
-------
Updated the snapshot docs
@girayimprobable @joshuahuburn @ElleEss @anne-edwards
=> Removed tag

SpatialGDK/Documentation/content/directory-structure.md
-------
Updated directory structure docs
@girayimprobable @anne-edwards @joshuahuburn @ElleEss
=> Updated directory structure docs

SpatialGDK/Extras/schema/global_state_manager.schema, SpatialGDK/Extras/schema/player.schema, SpatialGDK/Extras/schema/rotation.schema, SpatialGDK/Extras/schema/spawner.schema, SpatialGDK/Extras/schema/unreal_metadata.schema, SpatialGDK/Source/Public/SpatialConstants.h
-------
It's all going to be better now.
=> Make schema better

SpatialGDK/Extras/schema/singleton.schema, SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/Private/Interop/SpatialStaticComponentView.cpp, SpatialGDK/Source/Public/Schema/Singleton.h, SpatialGDK/Source/Public/SpatialConstants.h
-------
Simpler streaming queries.
=> Add a singleton component to simplify streaming queries

SpatialGDK/Documentation/content/helper-scripts.md
-------
Updated the helper-scripts.md
@girayimprobable @joshuahuburn @anne-edwards @ElleEss
=> Updated the helper-scripts.md

SpatialGDK/Extras/schema/singleton.schema
-------
Fix Singleton component schema package.
@Vatyx
=> Fix Singleton component schema package

SpatialGDK/Documentation/content/generating-a-snapshot.md
-------
Updated snapshot docs
@anne-edwards @ElleEss @m-samiec @joshuahuburn
=> MD'd snapshot docs

SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
-------
If you generate schema with "Generate schema for all classes", then uncheck the box and generate again, the SchemaDatabase will still have all classes in it, resulting in a bad snapshot.
@Vatyx
=> Clean ClassToSchema before generating schema

SpatialGDK/Documentation/content/porting-unreal-project-to-gdk.md
Porting guide docs update. Probably best to view changes in Visual Studio Code with the Markdown plugin and GitHub Pull Requests plugin to make this easier to see and review.
=> Updated the porting guide

SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp
=> Add default initialization

SpatialGDK/Documentation/content/cross-server-rpcs.md, SpatialGDK/Documentation/content/generating-a-snapshot.md, SpatialGDK/Documentation/content/get-started/gdk-and-starter-project.md, SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md, SpatialGDK/Documentation/content/glossary.md, SpatialGDK/Documentation/content/handover-between-server-workers.md, SpatialGDK/Documentation/content/singleton-actors.md, SpatialGDK/Documentation/index.md, SpatialGDK/Documentation/welcome.md
-------
Updated glossary
@girayimprobable @joshuahuburn @anne-edwards @ElleEss @m-samiec
=> Updated glossary

SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorToolbar.cpp
-------
Tell `cmd` to spawn another `cmd` so it all appears in one window.
@Vatyx @danielimprobable
=> Local deploy pauses if there's an error

SpatialGDK/Documentation/content/map-travel.md
=> Map travel initial doc

SpatialGDK/Documentation/content/spatial-type.md
=> Updated spatial type doc

SpatialGDK/Documentation/content/get-started/tutorial.md
-------
Tutorial updates adding the health replication
Related tutorial update https://github.com/spatialos/UnrealGDKThirdPersonShooter/pull/36
@oblm @joshuahuburn @ElleEss
=> Updated tutorial

SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md, SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
Added a check for the cast to SpatialGameInstance. 
Updated docs.
=> Added check for SpatialGameInstance and also updated docs

SpatialGDK/Source/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/Public/Utils/ComponentFactory.h
-------
Removed the object refs after this PR https://github.com/improbableio/UnrealEngine/pull/48
@improbable-valentyn @joshuahuburn @m-samiec
=> Removed object ref code

SpatialGDK/Extras/schema/global_state_manager.schema, SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/Private/Interop/SnapshotManager.cpp, SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/Public/SpatialConstants.h, SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Renamed the component from `GlobalStateManager` to `SingletonManager` to be more descriptive.
=> Rename component to SingletonManager

SpatialGDK/Documentation/index.md, SpatialGDK/Documentation/welcome.md
Updated welcome page and index to offer more information for non-coders who come here (journos, CTOs, influencers) or anyone curious but not wanting to get started yet. 
To add: How long it takes to get started.
Improbadoc
These are docs.
@ernopp @joshuahuburn @anne-edwards 
FYI
=> Update welcome and index page

SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
Ignore branch name, that was a whoops.
=> Changed SpatialPosition to be rebased from zero origin

SpatialGDK/Documentation/index.md, SpatialGDK/Documentation/welcome.md
+ Updated in-line CSS for image so it's with the text.
+ Slight rejig of the welcome text to make the Get started link more proinent and remove double link to the SpatialOS Concepts documentation as the page doesn't need it twice.
+ 
@ernopp @anne-edwards
=> Small update to welcome and index page

SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md
Adds a warning about the stability of the porting workflow.
improbadoc linted
@ernopp
=> Add callout

SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
Fix not being able to build on Linux due to referencing a static const.
=> Fix not being able to build on Linux

SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
fixing compilation error due to not defining function in header file.
test compilation on shooter game
https://improbableio.atlassian.net/browse/UNR-636
=> Added missing function declaration

SpatialGDK/Documentation/known-issues.md
UNR-897 - Seamless Travel not supported.
-------
=> Added UNR-897 to known issues

RequireSetup
-------
https://github.com/spatialos/UnrealGDK/pull/604
@m-samiec
=> Increment RequireSetup version (changes from #604)

RequireSetup, SpatialGDK/Extras/schema/spawner.schema, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitReader.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitWriter.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h, SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKLoader.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h, SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
-------
Mostly David's work from [this PR](https://github.com/spatialos/UnrealGDK/pull/564), excluding the Locator v2 flow, which was extracted separately (here)[https://github.com/spatialos/UnrealGDK/pull/615].
Tested locally with StarterProject, ShooterGame.
@davedissian @m-samiec
=> [UNR-885] FUniqueNetId support, KCP integration

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialTypebindingManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialTypebindingManager.h, SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h, SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h, SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Seems to work for me, but would be nice if you tested this locally as well.
=> Use TSharedRef for FClassInfo, change call sites to use FClassInfo&

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
https://improbableio.atlassian.net/browse/UNR-953
=> UNR-953 Added parent index check

.github/pull-request-template.md
-------
Updated PR template to add release notes for each merge.
@m-samiec @girayimprobable
=> Updated template for release notes

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitReader.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitWriter.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h, SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.cpp, SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h, SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentReader.h, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.h, SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Move unreal obj ref constants in class and added IsValid() function.
Additional drive-by cleanups.
Feature: Add IsValid() to FUnrealObjRef
Ran test suite
@BenNaccarato @Vatyx
=> Add FUnrealObjRef.IsValid()

SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
=> Switched to Raknet default

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h
=> Better function name

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
Disabled component updates 
REQUIRED: Disabled loopback of component updates
Tried on starter project and demo gym on Scavengers
=> Disable loopback of component updates

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
Bugfix - Fix hanging on shutdown for PIE when disconnected from SpatialOS
(Documentation changes are exempt)
Tried in starter project
@BenNaccarato @m-samiec
=> Fix hanging on shutdown when timeed out from SpatialOS

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
-------
Created https://improbableio.atlassian.net/browse/UNR-989 to investigate the root cause of this issue.
Bugfix: Fixed crash on multiserver PIE shutdown.
@Vatyx
=> Fix crash on multiserver PIE shutdown

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Added return statement to a case in switch statement that didn't have return.
=> Fix not returning in switch statement

SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Server Only constant was checked back in by mistake. Removing it and reformatting SpatialConstants.h
=> Remove unused constant and reformat.

README.md, SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
-------
Edited readme and build-unreal-fork pages. 
REQUIRED: Enter a simple message for this commit which will go in the release notes. Prefix with "Bugfix:" or "Feature:".
(Documentation changes are exempt)
If your change will take a long time to review, you can name at most two primary reviewers who are …
=> [UNR-1003] - Docs/update engine branch instructions

README.md, SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Update docs to point to the unreal-engine url directly. Github has our appropriate branch set automatically.
@NotRobSheridan @joshuahuburn
=> Adjusted fork path

SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
-------
The GDK will completely fail in this case, so it's important to make it an error.
Just a log change
None
=> Turn bReplicates offset warning into an error

SpatialGDK/Documentation/content/dynamic-typebindings.md, SpatialGDK/Documentation/content/generating-a-snapshot.md, SpatialGDK/Documentation/content/get-started/tutorial.md, SpatialGDK/Documentation/content/glossary.md, SpatialGDK/Documentation/content/map-travel.md, SpatialGDK/Documentation/content/schema.md, SpatialGDK/Documentation/content/whatsnew.md, SpatialGDK/Documentation/toc.md, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
-------
New doc added to explain schema gen, when to generate schema, source control considerations, etc.
Edited links throughout the docs (Though I might have missed a few) 
Local Improbadoc build
Laura (though she has already pontificated on the doc), Chris, Giray.
=> Added new doc for Schema

.buildkite/premerge.steps.yaml, ci/build-gdk.ps1, ci/get-engine.ps1
Adds a step ensuring that UE4 Prereqs have already been installed on this agent
@m-samiec
=> Install UE4 prereqs and renaming CI events

.buildkite/premerge.steps.yaml, ci/build-gdk.ps1, ci/get-engine.ps1
=> Update build kite queue to production queue

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
We are renaming "fake client" to "simulated player" to align terminology across (upcoming) projects.
For backwards compatibility the build script will still support `FakeClient` as a GameName (which results in `UnrealFakeClient@Linux.zip` as the created assembly), but will show a warning to use `SimulatedPlayer` instead. Using `SimulatedPlayer` as the GameName will result in a different assembly name (`UnrealSimulatedPlayer@Linux.zip`) being created.
=> Update build script to use SimulatedPlayer instead of FakeClient

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
=> Remove duplicate local variable for unreal metadata

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
-------
Fix order of initialization causing a warning.
@Vatyx
=> Fix order of initialization

SpatialGDK/Documentation/content/get-started/gdk-template.md, SpatialGDK/Documentation/content/get-started/tutorial.md
This docs only change explains what the release branch is, and how to keep your GDK up to date.
Rendered in improbadoc.
=> Explain how to upgrade the GDK

README.md, SpatialGDK/Documentation/content/get-started/introduction.md, SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md, SpatialGDK/Documentation/content/glossary.md, SpatialGDK/Documentation/content/toolbars.md, SpatialGDK/Documentation/content/troubleshooting.md, SpatialGDK/Documentation/index.md
-------
Removed any mention of the Starter Project from the docs. The Starter Project has been superceded by the Starter Template. 
Local Improbadoc build
=> Removed any mentions of the Starter Project from the docs

.buildkite/premerge.steps.yaml
... since this makes it easier to eyeball what it needs, as well as lock that down for the future where we multiply the steps via a test-matrix.
-------
REQUIRED: Enter a simple message for this commit which will go in the release notes. Prefix with "Bugfix:" or "Feature:".
(Documentation changes are exempt)
How is this documented (for example: release note, upgrade guide, feature …
=> Scope to Windows

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
Fix newly introduced inline errors.
@Vatyx @tenevdev
=> Remove inline

SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
-------
Just an unnecessary branch in schema generation
Removed unnecessary branching in schema generation
No need.
No need.
@m-samiec
=> Remove unnecessary branching

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
-------
Fixed a bad merge conflict resolution.
@Vatyx
=> Fix bad merge

Setup.bat
-------
We're no longer using TeamCity, so we can and should remove the TeamCity ifs from `Setup.bat`.
=> Remove TeamCity ifs from Setup.bat

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Hotfix to https://github.com/spatialos/UnrealGDK/pull/789, to ensure it builds for linux workers too.
(Make sure we use the linux supported int64 `Worker_EntityId_Key`, instead of `Worker_EntityId`
As a hotfix, I'd argue that a release note isn't necessary?
Now builds correctly.
=> change variable type to ensure linux builds work

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs, SpatialGDK/Build/Scripts/DeploymentLauncher.bat
-------
Adds the option to specify deployment regions for the launched deployments.
=> Add deployment region options

SpatialGDK/Documentation/content/get-started/dependencies.md
Specify the correct version, 2015, of the DirectX dependency
=> Specify the correct version of the DirectX dependency.

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
-------
Fixed bad log formatting.
Release note.
@m-samiec
=> Fix editor crash when making LogSpatialSender Verbose

SpatialGDK/Documentation/content/upgrading.md, SpatialGDK/Documentation/toc.md
* Adds an upgrade guide to the public documentation.
* Adds that upgrade guide to the table of contents on the Troubleshooting section.
Rendered in improbadoc.
=> Doc: upgrade guide

SpatialGDK/Extras/internal-documentation/release-process.md
-------
* Specify that you must use a fresh setup when testing a release.
* Also some drive by fixes
This is documentation
=> Specify that you must use a fresh setup when testing a release.

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/EditorWorkerController.h, SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Added spatial event delegate, and prevent worker replace issuing if spatial not connected.
@Vatyx
=> Add listen for spatial end event

SpatialGDK/Documentation/content/cloud-dev-workflow.md, SpatialGDK/Documentation/content/get-started/gdk-template.md
-------
Fix two broken links in the public docs.
Rendered and linted the docs.
=> fix links to markdown anchors

README.md, SpatialGDK/Documentation/content/cloud-dev-workflow.md, SpatialGDK/Documentation/content/get-started/gdk-template.md, SpatialGDK/Documentation/content/get-started/introduction.md, SpatialGDK/Documentation/index.md, SpatialGDK/Documentation/recommended-use.md, SpatialGDK/Documentation/toc.md
This didn't make it into the rc branch but should
Was previously approved here https://github.com/spatialos/UnrealGDK/pull/856
=> Update roadmap links

SpatialGDK/Documentation/content/get-started/tutorial.md
Previously approved here https://github.com/spatialos/UnrealGDK/pull/848
=> Small multiserver tutorial fixes from DOC-913

SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-setup.md
Fixes DOC-1063
Checked with improbadoc
=> Docs - Add back schema and snapshot generation to shooter tutorial

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Fixed a crash in the schema generation commandlets.
=> UNR-1312 Fix schema commandlet crash

SpatialGDK/Documentation/content/get-started/gdk-template.md, SpatialGDK/Documentation/content/technical-overview/gdk-concepts.md, SpatialGDK/Documentation/content/technical-overview/gdk-principles.md, SpatialGDK/Documentation/content/technical-overview/how-the-gdk-fits-in.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-healthchanges.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-localtest.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-setup.md, SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
Tutorial text update
Formatting update
Remove "image" from captions and then put it back!
N/A for docs
Improbadoc
Is docs
@anne-edwards @NotRobSheridan @eddyrainy @ernopp
=> Updated tutorial text for SpatialOS settings, formatting updates

SpatialGDK/Extras/internal-documentation/release-process.md
-------
Adds a step, update the roadmap, to the release process.
=> Add "update the roadmap" to release-process.md

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp
-------
Merge the following changes (which were merged into the RC) into master:
https://github.com/spatialos/UnrealGDK/pull/900
=> Merge 0.4.1-rc into master

CHANGELOG.md
-------
Forgot to add a release note for https://github.com/spatialos/UnrealGDK/pull/921
@m-samiec
=> Add release note for UNR-1368

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
-------
Reduced MulticastRPC authority warning to verbose to match other authority based logs in this class.
@m-samiec
=> Reduced MulticastRPC authority warning to verbose

SpatialGDK/Documentation/unreal-features-support.md
=> Update RPC Status

SpatialGDK/Extras/internal-documentation/release-process.md
-------
This change simplifies the LAN testing process in `release-process.md`.
I ran these steps.
=> Simplify the LAN testing process in release-process.md

SpatialGDK/Documentation/content/upgrading.md
-------
Notes that one must delete their schema database when upgrading GDK versions.
None, I'm taking @Vatyx & @m-samiec on their word here.
=> [UNR-1427] Schema database must be deleted upon upgrading.

SpatialGDK/Extras/internal-documentation/release-process.md
cc @ElleEss  @NotRobSheridan @eddyrainy
=> get review on release notes

SpatialGDK/Documentation/unreal-features-support.md
=> Add Listen Server & Network lag commands to features support page

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
-------
Merge the following changes (which were merged into the RC) into master:
https://github.com/spatialos/UnrealGDK/pull/934
https://github.com/spatialos/UnrealGDK/pull/942
https://github.com/spatialos/UnrealGDK/pull/935
@m-samiec
=> Merge 0.4.2 release into master

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Quick formatting fix on build-unreal fork page.
=> docs/formatting fix for build-unreal-fork

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-intro.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-play.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-authentication.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-clone.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-configure.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-intro.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-launch.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-play.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-workers.md, SpatialGDK/Documentation/index.md, SpatialGDK/Documentation/toc.md
Minor edits to index.md to point towards new tutorials
Added publishing date to all new pages
Updated build-unreal-fork to point to new tutorial and template
local improbadoc
=> docs/Updated index page - Added publishing data to both tutorials

README.md
Description
Updated readme.md to bring it in line with our messaging and documentation changes.
Added link to example project repo.
=> docs/DOC-1066 Update README.md

SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-launch.md
Quick formatting and text fix for deployment manager launch page.
=> docs/Update tutorial-deploymentmgr-launch.md

SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-launch.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-play.md, SpatialGDK/Documentation/toc.md
Quick formatting and text fixes as requested by Ernie.
=> Formatting fixes - Slight text edits

SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-play.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-authentication.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-configure.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-play.md
Minor formatting and typo fixes.
=> Fixed small formatting bits

SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetricsDisplay.h
Make MetricsDisplay toggle BlueprintCallable
@cmsmithio
=> Make toggle blueprint callable

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md, SpatialGDK/Documentation/content/get-started/dependencies.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-intro.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-play.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md, SpatialGDK/Documentation/content/get-started/gdk-template.md, SpatialGDK/Documentation/content/get-started/introduction.md, SpatialGDK/Documentation/index.md, SpatialGDK/Documentation/toc.md
-------
UX fixes due to dodge ToC and link from a drop-down.
Also amendment to text on set up intro page and ToC tiny rejig.
Imporobadoc (screen grabs attached)
Is docs.
@anne-edwards 
Ernie and Rob (not available) FYI 
----
----
---
=> UX updates

CHANGELOG.md, Setup.sh
Fix pathing issues in setup.sh (raised by @cyberbibby here - https://github.com/spatialos/UnrealGDK/pull/706)
Remove teamcity references from setup.sh (done for setup.bat here - https://github.com/spatialos/UnrealGDK/pull/760)
Bugfix: Fix path naming issues in `setup.sh`
@samiwh @aleximprobable
=> Setup.sh fixes

SpatialGDK/Documentation/content/get-started/dependencies.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md, SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md, SpatialGDK/Documentation/index.md
1. Updated home page link to  GDK concepts.
2. Updated home page estimated times.
3. Fixed typo and wrong name in porting guide.
4. Renumbered "1 - Get the dependencies" (didn't make sense that login wan't a step!).
N/A
Improbadoc
Is docs
@anne-edwards @NotRobSheridan
=> Link, typo, small format

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
No content change, just formatting and text standardisations and explanations.
* Formatted step 2 and 3 to be clearer and use standard formatting.
* Made terms clearer by being consistent.
* Explained why we were doing some tasks.
* Oriented user on which application they are using.
https://docs-testing.improbable.io/unreal/alpha/content/get-started/build-unreal-fork
@anne-edwards 
@NotRobSheridan  FYI
@ernopp  FYI
@io-ben FYI
=> Non-content update to environment variables steps & a small tweak

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Add safety checks to latest position batching work.
@samiwh @mattyoung-improbable
=> Add safety checks for position batching

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
-------
Add Singleton and SingletonManager to QBI system constraints. 
When an entity uses QBI, it will be excluded from chunk-based interest systems (such as streaming queries). 
Added to changelog.
Validated behavior in dev and test config, verified Interest component in inspector.
=> Fix Singleton Interest

SpatialGDK/Documentation/content/map-travel.md, SpatialGDK/Documentation/unreal-features-support.md
-------
Clarifies that Server Travel is not currently supported.
Rendered and linted in improbadoc.
=> [UNR-1494] Docs: Server Travel is not currently supported.

SpatialGDK/Extras/fastbuild/install.ps1, SpatialGDK/Extras/fastbuild/uninstall-0.96.ps1, SpatialGDK/Extras/fastbuild/uninstall.ps1
-------
Upgraded Fastbuild to 0.98
@jared-improbable
=> Upgraded fastbuild version to 0.98

SpatialGDK/Documentation/content/cross-server-rpcs.md
-------
Updated the documentation 
@ElleEss @NotRobSheridan
=> Update cross server documentation

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Fixed compilation warning regarding using FAssetDataTagMapSharedView::Find for 4.22
Generated schema fully on 4.22
=> Fix compliation warning in 4.22

SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Add toggle to disable QBI for server-workers. Performance workaround only useful for single-server deployments.
I don't think we should document this as it's a temporary workaround
Scale test ran successfully
@yumnuska @Vatyx
=> Add toggle for server qbi

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
-------
Docs quick fix: Rendering of notes in setup.
Improbadoc rendered:
=> Docs quick fix: Rendering of notes in setup.

Setup.bat
-------
Fixed an issue in Setup.bat, where it wouldn't copy required schema.
Setup.bat should work as expected on newly cloned repositories.
=> * Fixed schema copying in Setup.bat

.buildkite/premerge.steps.yaml
Update BK to use new agent queue.
Internal change, no note required
@joshuahuburn
=> Update BK agent queue

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
-------
Docs quick fix: Rendering of title in setup.
Improbadoc rendered and linted
=> Docs quick fix: Fix titles and list numbering

SpatialGDK/Extras/internal-documentation/release-process.md
-------
Docs:
* Introduces the concept of staging branches.
* Removes references to Test Suite.
* Add Example Project to release-testing.
=> Docs: Introduce the concept of staging branches & Example Project.

SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
-------
Made QBI switch an internal facing switch since it should be on by default.
=> Make QBI switch non public

SpatialGDK/Documentation/content/cloud-deployment-workflow.md, SpatialGDK/Documentation/content/command-line-arguments.md, SpatialGDK/Documentation/content/cross-server-rpcs.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-intro.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-play.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md, SpatialGDK/Documentation/content/get-started/gdk-template.md, SpatialGDK/Documentation/content/glossary.md, SpatialGDK/Documentation/content/local-deployment-workflow.md, SpatialGDK/Documentation/content/map-travel.md, SpatialGDK/Documentation/content/pricing-and-support/pricing.md, SpatialGDK/Documentation/content/pricing-and-support/support.md, SpatialGDK/Documentation/content/singleton-actors.md, SpatialGDK/Documentation/content/troubleshooting.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-authentication.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-clone.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-configure.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-intro.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-launch.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-play.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-workers.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-cloudtest.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-healthchanges.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-localtest.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-setup.md, SpatialGDK/Documentation/content/upgrading.md, SpatialGDK/Documentation/unreal-features-support.md
-------
Fix the issues with changelog across Unreal docs:
- doesn't have `----`
- doesn't have the italics
- not left aligned
- wrong tag for **br**: change from **/br** to **br/**
=> Fix changelog issues

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
We now return nullptr if no NetConnections exist at all. Added some other null checks elsewhere which rely on this.
=> Return nullptr if no ServerConnection or any ClientConnections exist

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Teeny change that makes a lot of difference.
=> Small format change for consistency and flow!

SpatialGDK/Documentation/unreal-features-support.md
Better reflect the latest platform support timelines as discussed [here](https://docs.google.com/document/d/1MlaO68xj6UZetrBdyxVNSrhwXEh7z_ktZc0oL_TefrQ/edit?disco=AAAADFxN6ZI&ts=5d076813)
Tested with Improbadoc
Please could @ElleEss  or @eddyrainy  review? Thanks
=> Docs - platform support updates

SpatialGDK/SpatialGDK.uplugin
Set version in uplugin so we can tell what it is.
=> Set version in uplugin

SpatialGDK/SpatialGDK.uplugin
Reverts spatialos/UnrealGDK#1044
=> Revert "Set version in uplugin"

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
Early out from SpatialNetDriver if SpatialClassInfoManager fails to init (because SchemaDatabase is missing)
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for reviewing this …
=> Bugfix [UNR-1573] Editor Crashes if SchemaDatabase is not found.

Setup.bat
-------
Adjust whitespace in `Setup.bat`.
@joshuahuburn
=> Adjust whitespace in Setup.bat

SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
Quick fix - Edited directory path to spatialos.json file on example project cloud deployment page.
=> docs/Update exampleproject-cloud-deployment.md

.gitignore
-------
Added .vscode folder to .gitignore
User specific files in .vscode folder are not version controlled.
User specific files in .vscode folder are not version controlled.
=> Added .vscode folder to .gitignore

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h, SpatialGDK/SpatialGDK.uplugin
-------
Merge the following changes (which were merged into the RC) into master:
https://github.com/spatialos/UnrealGDK/pull/1047
https://github.com/spatialos/UnrealGDK/pull/1055
https://github.com/spatialos/UnrealGDK/pull/1053
=> Merge 0.5.0-preview into master

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Following multiple users on Discord missing this step
Tested with improabdoc
=> Docs - clearer callout on fork step 1

SpatialGDK/Extras/internal-documentation/release-process.md
=> Fix link to roadmap in release-process.md

SpatialGDK/Documentation/content/dynamic-typebindings.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md, SpatialGDK/Documentation/content/get-started/gdk-template.md, SpatialGDK/Documentation/content/get-started/introduction.md, SpatialGDK/Documentation/content/spatialos-concepts/schema-and-snapshots.md, SpatialGDK/Documentation/content/toolbars.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-cloudtest.md, SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
-------
Small fixes for docs - adding missing links, correcting wrong links and typos etc. See [DOC-1088](https://improbableio.atlassian.net/browse/DOC-1088) for a list of fixes made.
@ElleEss @NotRobSheridan
=> Quick Fixes (DOC-1088)

SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
-------
Changed how we use schema_compiler so we print stderr as well as stdout
@Vatyx
=> Fixed schema generation to print std err

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
-------
Engine RP: https://github.com/improbableio/UnrealEngine/pull/166
See CHANGELOG.md
Played ShooterGame
Release note
=> [UNR-1591] Scene outliner world selection and blueprint debug object combo box UI shows worker label

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Recent change creates compiler warning about shadow declaration, we should avoid those.
=> [Bugfix] Rename local variable to avoid shadow declaration warning

SpatialGDK/Documentation/content/glossary.md, SpatialGDK/Documentation/content/how-to-use-schema.md
Updated the schema generation doc according to Patrick's changes (see [DOC-1093](https://improbableio.atlassian.net/browse/DOC-1093)).
@padhansell 
@ElleEss 
LMK if you'd like a docs preview for this (although I don't actually know how to do them).
=> Docs - Update the schema generation docs

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
-------
After new discoveries of default arguments passed into spatialos and the way we do safety checks for where to write snapshots and schema to we have decided to take out previous changes that safety checks directories set in Editor Settings and removing the editor settings options to specify schema output directory.
@m-samiec
=> Unr1640: Snapshot not being read from path set in editor settings

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/RPCContainer.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCContainer.h
=> Test implementation

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
-------
This warning can be benign, so reducing its severity.
It's trivial
@m-samiec
=> [UNR-1393] Downgrade HandleUnreliableRPC warning

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Made logs that don't need to be always outputted to be verbose instead.
=> Moved spamming logs to be Verbose instead of Log

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs, ci/unreal-engine.version
-------
These changes automatically stop a running deployment with the same name as the one that is about to be launched via the deployment launcher script.
Manually tested.
@girayimprobable @WVerlaek
=> Stop running deployments with the same name

RequireSetup
-------
Bumping this version so that the GDK setup will run (required for BeginPlay change)
=> Bump version

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Common/LinuxScripts.cs
-------
Restores the templating of the game name in the shell scripts for simulated players.
How is this documented (for example: release …
=> Fix shell scripts templating

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
-------
Packed RPCs might have been dropped. This PR fixes it.
Bugfix for the Ordered RPCs task. The bug was not in known issues.
Packed RPCs logic should work as expected.
No new notes.
@improbable-valentyn @joshuahuburn
=> Fix for Packed RPCs being dropped

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h
-------
Merge this fix into RC.
@m-samiec
=> Queue RPCs by Worker_EntityId (#1138)

OWNERS
Added Owners file for PROW to add tech writers to docs PRs
=> Add Owners File 

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
-------
There's been a case when cross-server RPCs might have been queued on receiving side, but not processed. Those should now be properly handled. 
Fixed an issue that didn't get into known issues yet.
Cross-server RPCs should work as expected.
No doc update.
@improbable-valentyn @mattyoung-improbable
=> UNR-1692 Cross-server RPCs should now be properly handled.

SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Don't kick off async tasks in DeploymentManager when running commandlets.
@samiwh @girayimprobable
=> Don't kick off processes in commandlets

SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
-------
We can and should pin the spatial daemon. This PR adds a --version argument to the spatial service start call which will use a pinned version rather than always getting latest.
@m-samiec @achannn
=> Pin SpatialD

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
-------
Added tracking of RPCs on entity creation
RPCs on entity creation should now also be included in RPC metrics.
RPCs on entity creation should now also be included in RPC metrics.
No doc update
=> UNR-1606 Added tracking of the RPCs on entity creation

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
-------
Added tracking of RPCs on entity creation
RPCs on entity creation should now also be included in RPC metrics.
RPCs on entity creation should now also be included in RPC metrics.
No doc update
@joshuahuburn
=> UNR-1606 Added tracking of the RPCs on entity creation (#1182)

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
UNR-1766
Explicitly resolve stably named subobjects correctly within package map.
@Vatyx
=> Resolve stably named subobjects correctly

RequireSetup, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Common/LinuxScripts.cs
Make sure the user home directory actually exists; if it doesn't the script will terminate
=> Fix native server launch script

SpatialGDK/Documentation/content/pricing-and-support/versioning-scheme.md, SpatialGDK/Documentation/content/upgrading.md, SpatialGDK/Documentation/toc.md
- Adds new versioning scheme page
- Approved by DavidP & reviewed by Laura [in this Gdoc](https://docs.google.com/document/d/1ihSDw23y74vS2S2JUm5v-3pADNAnzfcmqFrbQ_vHl9M/edit#heading=h.o1n4v7p7au8y) - feedback incorporated and PRed directly. 
- Tested in improbadoc
cc @anne-edwards this is a bronze publish
=> DOC-1172 Versioning scheme page

SpatialGDK/Documentation/content/get-started/dependencies.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-intro.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md, SpatialGDK/Documentation/content/get-started/introduction.md
-------
As outlined in ticket DOC-1230 I have created a pull request to tackle the suggested feedback items. 
Created changes  for Unreal GDK setup and related Example project documentation 
Tested locally 
@NotRobSheridan @ernopp
=> DOC-1230 Suggested GDK & Example project docs changes 

SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.h
-------
We weren't checking for previously generated component Ids for subobjects.
=> Schema gen with no changes should no longer generate new ComponentIds

CHANGELOG.md
-------
There is a load balancing bug which is causing reconnect a worker to sometimes fail. This makes users aware of the consequences. 
Added
This is known issue.
=> Add reconnect a worker known issue

SpatialGDK/Documentation/content/get-started/dependencies.md
Removes an incorrect statement that we support VS2019
Rendered and linted
=> Removes an incorrect statement that we support VS2019

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Remove check added in previous PR - https://github.com/spatialos/UnrealGDK/pull/1212
=> Remove check

ci/unreal-engine.version
Updated ci engine version to latest 422 version.
=> Update to latest 422 engine rc

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Add null check for channel that can occur when non-authoritative server shuts down in PIE.
@tenevdev
=> Add null check for channel

SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md, SpatialGDK/Documentation/content/get-started/gdk-template.md, SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-local.md, SpatialGDK/Documentation/content/how-to-use-schema.md, SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-deployment.md
-------
Add explanation to how to exclude directories from schema generation.
=> UNR-1781: add documentation to how to exclude directories from schema generation.

RequireSetup, SpatialGDK/Extras/schema/relevant.schema, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Schema/AlwaysRelevant.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
Added AlwaysRelevant component that gets attached to Actors that have bAlwaysRelevant set. This is currently only parsed at entity creation and won't get dynamically toggle if the variable is. 
@Vatyx @yumnuska
=> UNR-1738 Initial AlwaysRelevant support

SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-testing.md
Very tiny change for UNR-1817 
Tested locally 
=> UNR-1817 DB-Worker tutorial small doc change for all time deaths

SpatialGDK/SpatialGDK.uplugin
-------
* We forgot to increment Version in SpatialGDK.uplugin. I've fixed that.
* In a [separate PR](https://github.com/spatialos/UnrealGDK/pull/1152/commits/754539f8e65ae9c90bed85b8782ee672fb5f5426), I've also added it to the release process so we don't (nearly) miss it in the future.
=> We forgot to increment Version in SpatialGDK.uplugin

SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-setup.md
Small docs fix for UNR-1819 
Tested locally
=> UNR-1819 Docs fix incorrect branch

SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-communicating.md, SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-intro.md, SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-setup.md, SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-syncing.md, SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-testing.md
=> Misc tweaks

SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md, SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
Small docs change as a work around for known issue UNR-1811
This change updates the following pages 
**Example project**
https://docs.improbable.io/unreal/alpha/content/get-started/example-project/exampleproject-cloud-deployment#step-4-launch-your-cloud-deployment
**Unreal GDK Starter Template** 
https://docs.improbable.io/unreal/alpha/content/get-started/starter-template/get-started-template-cloud#step-4-launch-your-cloud-deployment
Tested locally using improbadoc 
=> UNR-1811 - Docs improvement for known issue of relative paths

SpatialGDK/Documentation/content/apis-and-helper-scripts/actor-group-ownership-helpers.md, SpatialGDK/Documentation/content/glossary.md, SpatialGDK/Documentation/content/tutorials/offloading-tutorial/offloading-gameplay-changes.md, SpatialGDK/Documentation/content/tutorials/offloading-tutorial/offloading-intro.md, SpatialGDK/Documentation/content/tutorials/offloading-tutorial/offloading-setup.md, SpatialGDK/Documentation/content/workers/offloading-concept.md, SpatialGDK/Documentation/content/workers/set-up-offloading.md
=> Bronze review for offloading topics

SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-communicating.md, SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-setup.md, SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-syncing.md, SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-testing.md
Fixing formatting, typos, updated ExternalSchemaCodegen.bat argument format, missing imports that make it impossible to finish tutorial otherwise
Probably not the end of these since I'm currently failing to complete the tutorial.
Required changes to finish branch just made in https://github.com/spatialos/UnrealGDKExampleProject/pull/37
=> more misc docs fixes

SpatialGDK/Documentation/content/workflows/autostart-server-workers.md, SpatialGDK/Documentation/content/workflows/set-up-vs.md
-------
Quick passthrough on the `Debugging workers from Visual Studio` docs section.
=> Doc 1250 debugging workflow

SpatialGDK/Documentation/content/map-travel.md, SpatialGDK/Documentation/content/technical-overview/gdk-concepts.md
-------
https://improbableio.atlassian.net/browse/UNR-1674
and
https://improbableio.atlassian.net/browse/UNR-1680
Updated and simplified map travel doc to match current functionality.
@ElleEss @ernopp @eddyrainy
=> UNR-1674 Docs update map travel

SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md
Added missing step for building project
-------
Missing build step from example project tutorial
=> Example Project Missing step to build project

SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md, SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md, SpatialGDK/Documentation/content/simulated-players.md
-------
Some small changes to make simulated player docs read better and make more sense.
=> Simulated player nits

SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md, SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
-------
Added a note to cloud deployment workflows to ensure users change the correct `name` field in their spatialos.json file as there are 2 name fields and we don't explicitly specify which to change
@ernopp
=> Added note about which name field to edit

SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md, SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-local.md
Removed a step that was added as a temporary fix, and updated the numbering.
=> Remove step that is no longer needed

SpatialGDK/Documentation/content/get-started/example-project/exampleproject-manual-setup.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-setup.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-cloudtest.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-healthchanges.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-localtest.md, SpatialGDK/Documentation/toc.md
1. Added steps to intro page.
2. Added reminder to step 1.
3. Slight rename of step 1 to describe what we are doing.
4. ToC update
5. Tiny format fix for Example Project because the steps were borked.
FYI @Ernie (as on hols)
=> Added change branch for multiserver zoning shooter tutorial

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/Schema/ClientRPCEndpoint.h, SpatialGDK/Source/SpatialGDK/Public/Schema/ServerRPCEndpoint.h
Cherry-pick of https://github.com/spatialos/UnrealGDK/pull/1246 into 0.6.1
=> IsListening and ownership fix (#1246)

SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-authentication.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-clone.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-configure.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-intro.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-launch.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-workers.md
-------
Work in progress do not merge. This PR will address every action item in DOC-1221, minus the ones that @ElleEss has identified as non-issues or being addressed in other PRs.
None, this just makes our docs clearer.
improbadoc lint and render
=> Docs - DOC-1221

RequireSetup
-------
Changed schema in this PR https://github.com/spatialos/UnrealGDK/pull/1281, but forgot to update `RequireSetup`.
@m-samiec @aleximprobable
=> Increment RequireSetup

SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
-------
Adding `SPATIALGDK_API` declaration to `UnrealObjectRef` so that it could be used from other modules.
@m-samiec
=> Adding SPATIALGDK_API declaration to UnrealObjectRef.

CHANGELOG.md, README.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
=> UNR-1908 Release branch merge

SpatialGDK/Documentation/content/get-started/dependencies.md
This has trolled two internal users dogfooding already. A small warning. Tested with improbadoc
=> Docs - Add VS 2019 support

OWNERS
=> remove old owner

SpatialGDK/Documentation/unreal-features-support.md
=> Docs - Unreal features support page cleanup + push out gameplay debugger support

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
Auto-install should be the first option as it's the recommended one
=> Docs - Auto install as first option

SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-cloudtest.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md
This aligns with the explanations in other tutorials https://github.com/spatialos/UnrealGDK/pull/1330
=> Zoning tutorial fixes: UNR-1938, UNR-1914

SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-syncing.md
-------
Updating documentation on the database integration sync tutorial. 
This PR is related to the couple of PRs listed below and should each go in at the same time:
https://github.com/spatialos/UnrealGDKExampleProject/pull/53
https://github.com/spatialos/UnrealGDKExampleProject/pull/54
Tested that the following through the docs gives the end result of a successful database integration example 
@ernopp @ElleEss
=> DOC-1259: Update Database Integration Guide Docs

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Removed support for UE 4.20
Removed support for UE 4.20 
Compiled and ran test suite.
Support for 4.22 is already our default, so I don't believe documentation is required.
@improbable-valentyn @mironec
=> Remove 420 support

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
-------
Fixed an issue, where GlobalStateManager is not properly set up on client and client cannot process ReceiveActor.
No update in Release notes.
Tested the ExampleProject against the latest Runtime version to make sure it works as expected.
No documentation update.
@samiwh @improbable-valentyn
=> Bugfix/UNR-2164 GSM Reception Fix

ci/check-version-file.ps1
Test merge to check branch protection.
=> Look for version file in the right directory

SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
-------
Added an error message to allow capturing more information if the crash in ComponentReader occurs again.
No release notes update
N/A
No documentation update
=> UNR-2176 Added error message

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Encountered crash when running in PIE and starting a new level. This is a fix for code that just went in, so ticket/release note not necessary.
Reviewers:
@mironec
=> Add check for null package map

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
-------
Inspector port was updated in spatiald. We need to update our button to match this.
his pull request?
=> Bugfix - Fix inspector button

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
Turn on modular upd downstream compression
=> Enable downstream compression

RequireSetup
-------
Bump the RequireSetup sequence number to trigger a schema copy after the AuthorityIntent change.
N/A
N/A
N/A
@m-samiec
=> Increment RequireSetup sequence number

ci/get-engine.ps1
-------
Set GCS publish bucket location directly in the engine retrieval script.
None: this is a CI change.
=> UNR-2186: define gcs publish bucked

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
-------
This PR releases 0.6.2.
See CHANGELOG.md.
Release process tests complete.
Associated documentation here: https://github.com/spatialos/UnrealGDK/pull/1325
=> Release 0.6.2-rc

SpatialGDK/Documentation/content/get-started/dependencies.md
=> Docs - DOC-1332 - Adds VS 2019 support

SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentReader.h
-------
Changed the check to an error log + continue. Changed the functions to also take the component ID which is only used in that log.
=> GCS-1548 Error instead of crash if there's an invalid field ID in a schema object

SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
The code looked wrong. I think this fixes it.
=> Fix wrong offset used in unresolved reference map for fast array serialization

SpatialGDK/Documentation/content/get-started/example-project/exampleproject-play.md, SpatialGDK/Documentation/content/get-started/introduction.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-authentication.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-clone.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-configure.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-launch.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-play.md, SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-workers.md, SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-logs.md, SpatialGDK/Documentation/index.md
https://docs-staging.improbable.io/unreal/alpha
Updated deprecated content (following @Ernie's PR) - few bits still hanging around.
Ref:
https://improbable.slack.com/archives/CD2TQ4WAX/p1571245217022000?thread_ts=1568284590.047200&cid=CD2TQ4WAX
ref: 
https://github.com/spatialos/UnrealGDK/pull/1436
=> Removed remaining references to deprecated tutorial

SpatialGDK/Documentation/content/get-started/dependencies.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md
-------
This is the documentation counterpart to: https://github.com/spatialos/UnrealGDK/pull/1457
Release note in PR linked above.
I have manually executed the workaround detailed in this PR and then built the UE4 fork, build the Example Project, local and cloud deployed and playtested with two clients and one server.
I also rendered and linked this using `improbadoc`.
=> Add MSVC install workaround to `docs-preview`

CHANGELOG.md, RequireSetup, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
Don't let spaces break your build.
@joshuahuburn @mironec
=> Quote paths when copying worker coordinator

SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
-------
Minor fixes for Schema Generation tests.
Run Schema Generation tests
No doc update
@joshuahuburn
=> UNR-2008 Minor fixes for Schema Generation tests.

SpatialGDK/Documentation/content/cloud-deployment-workflow.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md, SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
=> Docs - UNR-2325 - Add missing simplayer clients build step

SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/GridBasedLBStrategy.h
UPROPERTY's in Engine Plugins must have Categories.
=> Bugfix: Add Category to UPROPERTY

SpatialGDK/Documentation/content/cross-server-rpcs.md
-------
Added docs to describe how to use the AllowUnresolvedParameters from UNR-2244,
@ElleEss @m-samiec
=> Docs - added docs about AllowUnresolvedParameters

SpatialGDK/Extras/worker-sdk-upgrade.md
-------
Based on the conversation here: https://github.com/improbableio/UnrealEngine/pull/280#issuecomment-550267321
Adding a file documenting additional steps that need to be taken when upgrading the Worker SDK to make sure everything still works as expected
=> Adding a Worker SDK upgrade doc

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
-------
If a class isn't found in schema database, we log an error and try to quit, but if an RPC was getting called, the game would still crash. This will make it early out before hitting that.
=> UNR-2317 Fix crash when starting PIE with missing schema

SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-intro.md
=> Fix a typo that Jo found

ci/unreal-engine.version
This change is just localised for the rc branch to let CI pass.
(This may need a larger discussion in how we do CI in rc-branches / different CI process)
When this creates a merge conflict when merging rc back into master, just ignore this change.
=> Update unreal-engine.version file to preview

SpatialGDK/Documentation/unreal-features-support.md
-------
Fixed table alignment from:
to:
Nah
Linted and rendered.
This is documentation
=> Fixed an error in the feature support table

SpatialGDK/Documentation/content/cloud-deployment-workflow.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md, SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md, SpatialGDK/Documentation/content/simulated-players.md
=> Docs - Simplayer fixes based on Teri's feedback

SpatialGDK/Documentation/content/spatialos-concepts/authority-and-interest.md
-------
The hyperlink now matches the page title.
https://improbableio.atlassian.net/browse/DOC-1382
NA
Linted and served in improbadoc.
NA
@anne-edwards @ElleEss
=> Added 'and zoning' to 'workers and zoning' URL

SpatialGDK/Documentation/content/spatialos-concepts/authority-and-interest.md
Cherry picked this update - https://github.com/spatialos/UnrealGDK/pull/1514
=> Cherry picked update from docs-preview

SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
-------
`ConfigRestartRequired` is false by default, so there's no need to specify it everywhere.
@m-samiec
=> Remove unnecessary ConfigRestartRequired = false from settings

SpatialGDK/Documentation/content/simulated-players.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md
-------
Doc update SimPlayer UnrealExampleProject batch files. Two batch files have been added to the UnrealExampleProject. One allows you to spin up a single clients that will run a simulated player. The other will run 10 simulated player clients.
@ElleEss @MarkWoulfeImprobable
=> [UNR-2425][MS] Doc update SimPlayer UnrealExampleProject batch files.

SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp
-------
`git cherry-pick 825ff83d89b8720b8047a901ad50debfc30988e4`
None
@joshuahuburn tested with the log line in question, gets parsed correctly: https://regex101.com/r/sIPlRq/1/
None
@joshuahuburn
=> Bugfix: Fixed up regex to handle log categories without imporba… (#1512)

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
https://improbableio.atlassian.net/browse/DOC-1279
Fix for the ticket, cleans up description of auto/manual installation and clarifies the branch to use when setting up (step 5)
=> DOC-1279: Explain branching and auto/manual install

ci/build-and-send-slack-notification.ps1
-------
Tiny change to display the build source correctly.
Not customer facing, no release note has been added.
-
No additional documentation has been added
@mironec @jamiebrynes7 @michelefabris
=> fix environment variable

SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-communicating.md, SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-intro.md, SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-syncing.md, SpatialGDK/Documentation/content/tutorials/dbsync/tutorial-dbsync-testing.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-cloudtest.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-healthchanges.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-localtest.md, SpatialGDK/Documentation/toc.md
Adds experimental wording to these two tutorials
Tested with Improbadoc
=> Mark DBSync and Zoning tutorials as experimental

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
-------
Adjusted format and namespace scope to be consistent.
@m-samiec
=> Adjust formatting and namespace scope for SpatialConstants

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
-------
New argument was added, but this index wasn't incremented.
@improbable-danny @oblm
=> Fix the third StopDeployments argument

SpatialGDK/SpatialGDK.uplugin
-------
Increments the `VersionName` and `Version` of `SpatialGDK/SpatialGDK.uplugin`.
NA
**Not tested**
NA
@m-samiec
=> Update Version and VersionName in SpatialGDK.uplugin

CHANGELOG.md
-------
Include a tiny CHANGELOG change. This change is already live in preview, I just don't want to undo it in `0.7.1`.
Rendered markdown.
=> Update CHANGELOG.md (#1458)

CHANGELOG.md, Setup.sh, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultWorkerJsonGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp, SpatialGDK/Source/SpatialGDKServices/Private/Interop/Connection/EditorWorkerController.cpp, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp, SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp, SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp, SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h, SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesModule.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerTest.cpp, SpatialGDK/SpatialGDK.uplugin
-------
This enables the SpatialOS toolbar on Mac. 
still need to do that
tested it manually on my Mac machine
none needed for now
=> Enabling SpatialOS toolbar on Mac

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
-------
Added a missing #if WITH_EDITOR to fix the build.
@mironec @m-samiec
=> Added a missing #if WITH_EDITOR to fix the build

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md, SpatialGDK/Documentation/index.md
Documentation changes to GDK for Unreal for tickets DOC-1279 and DOC-1358. Cherry picking across to preview.
=> Cherry pick commits from recent tickets to docs-preview from docs-release

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
-------
Fix for scavengers dropped URL options.
=> [UNR-2553][MS] Fix for droppped URL options.

SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Update text according to the tech editor comments
Run Engine and check the new text
@joshuahuburn 
@m-samiec
=> UNR-2318: Use text which was provided by tech editors

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
-------
SpatialNetDriver has no friends anymore. 
Hid Dispatcher and SnapshotManager in private section of SpatialNetDriver. 
Removed unused IsSingletonEntity function from SpatialActorChannel.
No release note udpate
The code compiles.
No doc update.
@samiwh @mattyoung-improbable
=> UNR-2129 Removing unused code

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
Remove references to the Net Driver from SpatialMetrics
=> [UNR-2129] Decouple net driver and Spatial metrics

CHANGELOG.md
=> Release note for 0.6.4

CHANGELOG.md
=> Update VersionName and release date

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialLoadBalanceEnforcer.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
Refactored an error message.
Fixed an erroneous return statement.
Gym
=> Refactored an overzealous warning message and a drive by fix.

CHANGELOG.md
=> Update release date in CHANGELOG

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
this happened accidentally in a rebase
=> Don't create locking policy on client

SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/ReferenceCountedLockingPolicy.cpp
This was blocking Evi's build compiling. It succeeded on my machine + CI, could be an issue with precompiled headers.
=> Update ReferenceCountedLockingPolicy include

Setup.sh, SpatialGDK/Extras/git/post-merge
-------
When running `Setup.sh --china` will not work due to how the `DOMAIN_ENV_VAR` is being set. This fixes this issue, plus the post-merge file and some smaller style changes. :)  
tested it on my Mac machine
How is this documented (for example: release note, upgrade guide, feature page, in-code …
=> Fixing Setup.sh

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
Moved the StaticComponetView and the GlobalStateManager to the SpatialGameInstance.
No release note update.
Everything should work as before.
No documentation update.
@MatthewSandfordImprobable @joshuahuburn @m-samiec
=> UNR-2129 SpatialWorkerCleanup

.buildkite/premerge.steps.yaml, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/ReferenceCountedLockingPolicy.cpp
-------
Updates the queue to a more recent version that includes a fix for:
Not customer facing. No release note has been added.
I have not tested this queue. I hope the merge gate will suffice. My heart hurts...
It's a one line change
=> update queue to recent version

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Fixed schema database not loading correct when running in editor.
bugfix: Fixed issue where schema database failed to load previous saved state when working in editor.
Ran local schema gen, and test frameworks.
@improbable-valentyn @aleximprobable
=> Switch schema database path to editor version

SpatialGDK/Source/SpatialGDKTests/Examples/SpatialGDKExampleTest.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/SpatialWorkerFlags/SpatialWorkerFlagsTest.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/ReferenceCountedLockingPolicy/ReferenceCountedLockingPolicyTest.cpp
Fixed include errors in tests.
=> Fix TestDefinitions.h includes and misc fixes

SpatialGDK/Documentation/content/get-started/dependencies.md
-------
Updated the Git dependency to:
a) Accurately state the NEED for Git.
b) Recommend GitHub Desktop instead of Git for Windows. This provides parity with the following page in the documentation which refers to GitHub Desktop.
N/A
Ran improbadoc serve
N/A
If your change will take a long time to review, you can name at most two primary reviewers who are @ElleEss @jostichbury
=> [DOC-1368] Improved Git section

SpatialGDK/Documentation/index.md
In fixing DOC-1358 I introduced a minor issue (change history wasn't italicised and some bullets were incorrect). This fixes those issues.
=> Fix up mistakes in index.md introduced by fix to DOC-1358

SpatialGDK/Documentation/content/get-started/dependencies.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md
-------
Added a warning about the 45% hand on first run and addressed other minor issues.
N/A
Improbadoc serve
N/A
@ElleEss @jostichbury
=> [DOC-1371]/[DOC-1372] add note on launch wait and fix typos

SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md
-------
Addressed the comments within the ticket (https://improbableio.atlassian.net/browse/DOC-1424) and made a whole bunch of formatting improvements.
N/A
Improbadoc serve
N/A
@anne-edwards @jostichbury
=> [DOC-1424] improve cloud deployment page

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
Fix crash when attempting to add map element back in whilst map size changes.
Also included @samiwh and @tenevdev fix and extended upon it slightly - https://github.com/spatialos/UnrealGDK/pull/1672
Internal functionality not yet documented, release note not necessary
=> Fix crash in latency tracer

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Added more detailed stat tracking in component update.
@aleximprobable @joshuahuburn
=> Added more detailed stat tracking in component update

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
First draft of using NCD components to respect bNetUseOwnerRelevancy flag
To address : how to handover the overriden component in the static component view ?
Test Gym with actors with different net cull distances changing their owner
=> [UNR-2276] Respect use net owner relevancy

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/CheckoutRadiusConstraintUtils.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/CheckoutRadiusConstraintUtils.h, SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/CheckoutRadiusConstraintUtils/CheckoutRadiusConstraintUtilsTest.cpp
-------
dedupe constraints by radius bucket, should make scavengers queries nicer
does this need a release note?
Added unit tests for the deduping
check the inspector in scavengers (or another complex game) to see if there are multiple buckets in an interest component with the same radius on any one entity (tested manually by myself in scavengers, sim player test to see performance impact coming soon ™️ )
How is …
=> dedupe bucket

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
Feature: Batch Spatial Position Updates now defaults to false. 
Tested on both runtime stacks, performance was better.
@samiwh @mironec
=> Change batch position update default to false

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
…nection
-------
Moved a couple of functions from SpatialNetDriver to SpatialWorkerConnection to be able to reuse them in tests.
@improbable-valentyn @mironec
=> UNR-2710 Moved some SpatialNetDriver functions to SpatialWorkerConnection

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
-------
Added stat in LatencyTracer
@m-samiec
=> UNR-2741 - Added stat in LatencyTracer

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialActorGroupManager.cpp
Was hitting this crash 100% for in my local state - returning dereferenced pointer that may be bad if container realloc-ed.
@improbable-valentyn @mironec
=> Fixed spatial actor group manager bad return

SpatialGDK/Documentation/index.md
=> Docs - Homepage formatting error

SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
Add missing generate call missed in this PR https://github.com/spatialos/UnrealGDK/pull/1639
@joshuahuburn
=> Generate ncd components when using cook commandlet

SpatialGDK/Source/SpatialGDKTests/SpatialGDK/EngineClasses/SpatialVirtualWorkerTranslator/SpatialVirtualWorkerTranslatorTest.cpp
=> Unbreak master, my bad lol

SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Name NCD components with 64 bit ints.
=> Fixed NCD component name output

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
Increased spatial gdk settings logged on startup.
@joshuahuburn
=> Add more spatial gdk setting logging on startup

CHANGELOG.md, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
-------
Bring in a fix that went into 0.8.1-preview-rc
https://github.com/spatialos/UnrealGDK/pull/1772
@m-samiec @MatthewSandfordImprobable
=> Merge 0.8.1-preview-rc into master

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
-------
* Restructure ReuqestDeploymentLoginTokens logic and export the function to outside so caller can call this API to get new deployment info as they wish.
=> MBL-13 Remove hard coded locator url in example project.

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialRPCService.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialRPCService.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
-------
Adds components that are needed for workers to function correctly when result types are on.
Test gyms appear to show this working. The handover gym still has issues, however the issues seem to happen with or without result types (but _not_ if `enable_legacy_checkout_all_initially` is true) UPDATE: appears to be fixed
A couple in code comments
@mattyoung-improbable @m-samiec @samiwh
=> correct components

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
Increased unreal profiling coverage within the SpatialGDK plugin.
Based on stat captures provided by existing games.
@danielimprobable @improbable-danny
=> UNR-322 : Add more profiling coverage

CHANGELOG.md
=> SpatialOutput window open by default.

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/ExpectedSchema/rpc_endpoints.schema
The follow up work to split server to server RPCs out for ring buffers as well. 
Using the server to server RPC gym, as in https://github.com/spatialos/UnrealGDK/pull/1795
@samiwh @improbable-valentyn
=> ring buffer split rpc

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp
Did the wrong check for whether the json is valid. This fixes it.
=> fixing dev auth generation button

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
-------
This was a mistake we made when adding the option to run the spatial worker connection on the game thread. 
@samiwh  @aleximprobable
=> Worker connection on game thread fix

CHANGELOG.md, Setup.bat, Setup.sh, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp, SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp, SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h, SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.cpp
NEEDS TO BE A MERGE COMMIT!
Do not squash.
=> Merge 0.8.1-rc into master

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
Updating for engine change: https://github.com/improbableio/UnrealEngine/pull/356
=> Update GDK for OnOwnerUpdated args engine change

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
Cleaned up the cmd line option handling code which will be useful for NFR pipeline without modifying the settings (+ added a few extra parameters) 
-------
Modified how we handle command line args (internal only) - it makes it bit easier to add new args without copy/paste and exposed a few of the other settings 
Testing using both -Argument and -Argument=[True/False] method
Test passing a few command line arguments and check the desired result 
@m-samiec
=> Cleaned up cmd line options

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
There were duplicate commits that caused this - removing redundant call.
=> Remove redundant tracer call

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialOSDispatcherInterface.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/SpatialOSDispatcherInterface/SpatialOSDispatcherSpy.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/SpatialOSDispatcherInterface/SpatialOSDispatcherSpy.h
small change to make this more obvious, rather make it clearer than leave it
=> rename and add comment as I got confused

CHANGELOG.md, SpatialGDK/Extras/internal-documentation/release-process.md
-------
Changlog and docs update for the linking of engine to GDK and ExampleProject version for use in InstallGDK scripts.
@oblm
=> [UNR-2221][MS] Docs and changelog update for InstallGDK script changes

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
-------
We added runtime version as a param to the deployment launcher. We forgot to make this change. 
@joshuahuburn  @mironec
=> Bugfix for broken SimPlayers 

CHANGELOG.md, SpatialGDK/SpatialGDK.uplugin
-------
In which I fix up the CHANGELOG.
=> Update CHANGELOG.md, increment the VersionName and Version.

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectDummy.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectSpy.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectStub.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/RPCContainerTest.cpp
-------
Move `bIsServer` and `QueueType` to `RPCContainer`
RPCContainer tests should pass.
It's an internal change, no doc update.
@m-samiec
=> UNR-3014 Moved some flags to RPCContainter

SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp
-------
Added handling of new cases in RPC error logging.
@m-samiec
=> UNR-2888 Added proper error output for new RPC errors

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
here it is, new PR because it was easier, will close the other
=> indentation

SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Replaces parallel tracking sets for LevelComponentIds and NetCullDistanceComponentIds with a copy from the source maps when the schema database is written at the end.
=> Remove parallel tracking sets

ci/common.ps1
N/A
Reviewers:
@joshuahuburn as resident PowerShell expert
=> Maybe fix slack hooks?

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
as discussed offline, channels might not be there for miscellaneous reasons
testing:
ran into the left most cube a few times and nothing crashed
=> schrodinger's channel A

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
Bug fixes I encountered when doing the replication graph work. Pulling into a separate PR so they can get merged now.
Fixes dormant actor deletion when using NCD interest
Fixes an issue where load balancer would crash when using world composition on clients
Fixes an issue with the load balancer printing bad warnings when using world composition
Transient fixes, not release note
Ran through test gyms
@jacquese @mironec @alastairdglennie
=> Fixes for bugs encountered in during test gyms playthroughs

SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
squid test was successful, so time to flip (can always flip back if something comes up in the near future)
=> flip result types

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
=> [UNR-3064][MS] Catching exception where resources run out in AWS

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp, SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
=> [UNR-3062][MS] Fixing spatial auth to west when in china in local deployment 

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
=> [UNR-3064][MS] Adding extra logging for unhandled exceptions

SpatialGDK/Source/SpatialGDKEditor/Private/Utils/LaunchConfigEditor.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/Utils/TransientUObjectEditor.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/Utils/TransientUObjectEditor.h, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
-------
We have to update to a release version of `spatiald` (was previously a custom version). 
Additionally I've added fixes for includes for Engine Plugins.
Transient issue.
@ImprobableNic @mironec
=> SpatialD update + Engine Plugin include fixes

CHANGELOG.md
-------
Added the release date to the CHANGELOG
=> Release date for 0.8.1 in CHANGELOG.md

SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp
cherry-picks https://github.com/spatialos/UnrealGDK/pull/1863
=> Create log directory if it doesn't exist for the spatial output (#1863)

SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewCoordinator.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewDelta.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/WorkerView.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/CommandMessages.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ConnectionHandlers/AbstractConnectionHandler.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ConnectionHandlers/QueuedOpListConnectionHandler.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/MessagesToSend.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/AbstractOpList.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/ViewDeltaLegacyOpList.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/WorkerConnectionOpList.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewCoordinator.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewDelta.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/WorkerView.h
-------
READ IN COMMIT ORDER.
Creating the first bits of SpatialView.
Currently only handling create entity requests and responses.
Behind a settings flag bUseSpatialWorkerView.
Unit tests to come in a separate PR. This exists in it's current form so that we can review the basic structure.
This is an internal feature, but there will be internal documentation to come.
=> WIP UNR-2927 Initial SpatialView vertical slice

SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewDelta.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/WorkerView.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ConnectionHandlers/AbstractConnectionHandler.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ConnectionHandlers/QueuedOpListConnectionHandler.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/MessagesToSend.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/ViewDeltaLegacyOpList.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/WorkerConnectionOpList.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewCoordinator.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewDelta.h
=> Made headers explicit.

ci/unreal-engine.version
=> Switch back to 4.23 default until NFR pipeline is sorted

.buildkite/premerge.steps.yaml, ci/gdk_build.template.steps.yaml, ci/setup-build-test-gdk.ps1
Reverts spatialos/UnrealGDK#1942
=> Revert "Update to 2019 queue"

CHANGELOG.md, SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
=> [UNR-3178]Pin 14.5.0 as the runtime version

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
this is some kind of sick joke
=> my boolean defaults to true question mark?

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
Fix vs 2019 errors in trace library - waiting on green build here - https://buildkite.com/improbable/shootergamebuildkite-sg-perf-test/builds/1226
@improbable-danny @joshuahuburn
=> Explicit bool

SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
Increase the default ring buffer size until we have better data on this.
@m-samiec @samiwh
=> Increase the default ring buffer size

CHANGELOG.md, RequireSetup, SpatialGDK/Extras/schema/rpc_components.schema, SpatialGDK/Extras/schema/rpc_payload.schema, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Update gdk defaults for 0.9 release.
https://github.com/spatialos/UnrealGDKExampleProject/pull/138
https://github.com/spatialos/UnrealGDKTestGyms/pull/71
Updated changelog - see it for details.
TestGyms & Playtests
@improbable-valentyn @samiwh
=> UNR-3056 - 0.9 - Update defaults, remove rpc packing

SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
Updated outgoing rpc time to 30s
@joshuahuburn
=> Update QueuedOutgoingRPCWaitTime to 30s

SpatialGDK/Extras/internal-documentation/release-process.md
Update our internal docs to include UnrealGDKTestGyms
@oblm
=> Add TestGyms rc to release docs

CHANGELOG.md, SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp
1. Update CHANGELOG.md.
2. Make the comment clearer.
=> Update change log file.

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
GSM can fail on startup for a few reasons - made warning messages slightly more verbose.
@MatthewSandfordImprobable @alastairdglennie
=> Made gsm failure warning more verbose

SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
Quickly fix compilation issue on our integration branch.
=> Fix include order

SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Schema/Interest.h, SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
This breaks iterative builds.
@m-samiec
=> Rename result types

SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
Prevent updates that only contained cleared fields from being dropped.
@mironec @samiwh
=> Write bytes when clearing fields

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Fixed an issue with UArrayProperty replication. 
No doc update.
=> UNR-3365 ResolveObjectReferences fix

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
Fixes issue with unity builds.
@m-samiec @mironec
=> Changing Stream to UStream

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Changed UE_LOG from Log to Error for ResolveObjectReferences error.
@m-samiec
=> Changed Log to Error for

SpatialGDK/Source/SpatialGDKEditor/Private/EditorExtension/LBStrategyEditorExtension.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/EditorExtension/LBStrategyEditorExtension.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/LoadBalancingEditorExtension/SpatialGDKEditorLBExtensionTest.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/LoadBalancingEditorExtension/TestLoadBalancingStrategy.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/LoadBalancingEditorExtension/TestLoadBalancingStrategyEditorExtension.h
Code which looked for a load balancing strategy's extension did not check actual inheritance between classes.
Added unit tests around these features.
=> [UNR-3325] Fix editor load balancing extension selection

SpatialGDK/Source/SpatialGDK/Private/Schema/UnrealObjectRef.cpp
=> Fixing conflict with singleton-esque stably-named object behaviour

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
- Set some runtime settings when we choose different flow in new UI.
=> UNR-3382 Set some runtime settings when we choose different flow in new UI.

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Tentative fix for the stack overflow in USpatialReceiver::ReceiveActor.
@ImprobableNic @m-samiec
=> UNR-3407 Async Package Load fix

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h
This reverts commit 47816806857339f54085dada85ffdde15f8504d9.
=> Revert "[UNR-3128] Fix startup actors receiving empty lists (#1998)"

CHANGELOG.md
Based on https://github.com/spatialos/UnrealGDK/pull/2053/files which targeted master.
Adapted all the 0.9 logs with their touch ups.
@anne-edwards @ernopp
=> Fix up 0.9.0 CHANGELOG

CHANGELOG.md
Final proofread of release notes before translation.
=> Final Changelog proofread before translation

ci/setup-build-test-gdk.ps1
=> Fix release CI

SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
Original author: @yunjielu 
Original PR: https://github.com/spatialos/UnrealGDK/pull/2022
@ImprobableNic @MatthewSandfordImprobable
=> Add a button to open console page

RequireSetup, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
Shame on me (tested the original PR while having extra changes that added a deployment tag by default so didn't test empty tags)
=> Fix creating deployment with empty tags

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorPackageAssembly.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorPackageAssembly.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
Unecessary to support Win32, so remove the Windows Platform option.
=> UNR-3422 Remove Win32 Platform Option

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
When starting local deployment, grey out the start button.
=> UNR-3429 When starting local deployment, grey out the start button.

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Raised here - https://improbableio.atlassian.net/browse/NWX-14100
Still running validation tests - will report back.
@cmsmithio @improbable-valentyn
=> Process auth gained before actor creation

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp, ci/run-tests.ps1, ci/setup-build-test-gdk.ps1
Enables zoning tests in CI. Namely the one test that's currently there.
N/A
This CI.
N/A
@joshuahuburn (sorry)
=> Enable zoning automated tests in CI

SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Prevent users from specifying invalid IP or deployment name in the drop down menu.
=> UNR-3427 Prevent users from specifying invalid IP or deployment name in the dropdown menu.

SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h, SpatialGDK/Source/SpatialGDKEditorCommandlet/Public/SpatialGDKEditorCommandletModule.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.h
Not much to say here.
@jessicafalk
=> Add missing '#pragma once'

SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/OwnershipLockingPolicy.cpp
=> Change spammy logs to Verbose

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Merge failure notifications from `feature/workflow-improvements` branch.
Original PR: https://github.com/spatialos/UnrealGDK/pull/2139
Original author: @jayprobable 
=> Failure notification in package assembly when schema or snapshot fails

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
After user launch the cloud deployment, will copy the deployment name into start drop down menu.
=> UNR-3482 Copy cloud deployment name from the cloud deployment window to the Start dropdown

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Save config so the selected connection flow stays after reopening the editor.
=> Save config when selecting connection flow

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCommandLineArgsManager.cpp
=> Fix connecting to local deployment from 'Push settings to device'

SpatialGDK/Source/SpatialGDK/Public/Schema/ComponentPresence.h
https://improbableio.atlassian.net/browse/UNR-3592
Ensure ComponentPresence component objects are constructed safely.
@alastairdglennie @samiwh
=> Rework component data/updates

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKCloudDeploymentConfiguration.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Mark required fields and update the corresponding logic in `IsDeploymentConfigurationValid`.
@jessicafalk @jayprobable
=> Mark required fields in Cloud deployment window

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
@jessicafalk @mattyoung-improbable
=> Move Schema and Snapshot buttons to the right

RequireSetup, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs, SpatialGDK/Source/SpatialGDKEditor/Private/CloudDeploymentConfiguration.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/CloudDeploymentConfiguration.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKCloudDeploymentConfiguration.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKCloudDeploymentConfiguration.h
Region code is greyed out if you type something in the cluster field.
Region picker is not shown if Services Region is set to China ("CN" is automatically used)
=> Ignore region code if deployment cluster is specified

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
=> Switch inspector links for new runtime

SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
Update to the latest release of runtime and the latest pinned templates.
@ernopp @jessicafalk
=> Update runtime and templates

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
Fix for compile error introduce in https://github.com/spatialos/UnrealGDK/pull/2146
=> Fix trace compile error

CHANGELOG.md, SpatialGDK/SpatialGDK.uplugin, ci/unreal-engine.version
=> Merge rc back into master to get a nicer changelog

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
https://improbableio.atlassian.net/browse/UNR-3683
Fix for unreleased feature
@jacquese @samiwh @mironec @sjtsilvester
=> [UNR-3683] Fix initial server checkout of auth entities

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialStatics.h
Use `IsMultiWorkerEnabled` rather than checking number of worker layers
=> Fix IsReadyForReplication for all scenarios

CHANGELOG.md
https://github.com/spatialos/UnrealGDKExampleProject/pull/180
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for reviewing this request. @ mention …
=> ExampleProject Control gamemode default

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKCloudDeploymentConfiguration.cpp
This should've been done as part of this PR https://github.com/spatialos/UnrealGDK/pull/2220 but was missed as an oversight.
@jessicafalk
=> Remove hidden enum values from Simplayers region picker

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorPackageAssembly.cpp
Support paths with spaces.
@jessicafalk
=> Quote project path when building assembly

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialConditionMapFilter.h, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
=> [UNR-3686] Fix OwnerOnly properties set in OnAuthorityGained

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
Breaking change between old and new offloading implementation
=> Clients are never actor group owner

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKCloudDeploymentConfiguration.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKCloudDeploymentConfiguration.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Original PR (went into `master`)
https://github.com/spatialos/UnrealGDK/pull/2258
Changes on top of that PR: moved the checkbox above the file picker and made auto generate checked by default.
@mironec @oblm
=> UNR-3675 Add Auto Generate Launch Configuration Checkbox (#2258)

CHANGELOG.md, SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
0.4.3.
https://github.com/spatialos/UnrealGDKExampleProject/pull/187
https://github.com/improbableio/UnrealEngine/pull/557
https://github.com/improbableio/UnrealEngine/pull/558
Updated.
@io-ben 
Release note
@io-ben
=> [UNR-3733] Update standard runtime version to 0.4.3

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
https://improbableio.atlassian.net/browse/UNR-3729
=> Add error checking Actor group owner before net driver is ready

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp
Fixes client crash when travelling between deployments that was introduced in #2262
Crash details - https://improbableio.atlassian.net/browse/NWX-15317
Fix change in previously unreleased code, note not required.
Validated by NWX
@samiwh @joshuahuburn @mironec
=> Fix server worker entity deletion crash

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Stuff that shouldn't have been removed on Friday night.
Comment noting the mistake:
https://github.com/spatialos/UnrealGDK/commit/052fd3dbc773b2bc72153966adfc330c886c8c44#r40225372
=> Restored erroneously removed code.

SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LayeredLBStrategy.cpp
Actors which are not loaded into memory at the time of setting up the LB strat would be removed due to the soft pointer validity check. We don't require this as the actor will be loaded in by time of usage. 
@mattyoung-improbable @alastairdglennie @jennifer-at-improbable-io
=> [UNR-3624] Fix LB for unloaded actors

CHANGELOG.md
Tech writer review of changelog (from Google doc: https://docs.google.com/document/d/1Yeun9sm6Nnv4Ch5RA1yiJ2IfBYzztor4TZDMk0be15A/edit#)
No need for a thorough review - all the updates are copied directly from the Google doc (where we had the discussions).
=> DOC-2048 Tech writer review of changelog

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
=> Fix error message on spawn

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/OpUtils.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/OpUtils.h
Now, we will process all entity queries near startup.
N/A. Regression in rc.
Started local deployment with Compatibility runtime a lot.
N/A
Tomorrow.
=> [UNR-3791] Fix servers failing to properly connect to the deployment

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMovement/CharacterMovementTestGameMode.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMovement/CharacterMovementTestGameMode.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMovement/SpatialTestCharacterMovement.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMovement/SpatialTestCharacterMovement.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMovement/TestMovementCharacter.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMovement/TestMovementCharacter.h
This PR closes this [EngineNetTestPR ](https://github.com/improbable/UnrealGDKEngineNetTest/pull/69) and adds a test that tests if the movement of a character from a starting point to a Destination, performed on a client, is correctly replicated on the server and on all other clients.
Ran the test from the session front-end and made sure it passes when replication is working correctly. Broke replication and checked that the test failed, 
In-code documentation.
@ImprobableNic @mironec
=> Character movement test

SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Compare with https://github.com/spatialos/UnrealGDK/blob/de19dc32eec22c38cc9b7c0802e0830b394eb4f1/SpatialGDK/Extras/schema/server_worker.schema#L7-L11
=> Make field IDs match schema

SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDevAuthTokenGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCommandLineArgsManager.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorPackageAssembly.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialLaunchConfigCustomization.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/Utils/LaunchConfigurationEditor.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/Utils/TransientUObjectEditor.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditor/Public/Utils/LaunchConfigurationEditor.h, SpatialGDK/Source/SpatialGDKEditor/Public/Utils/TransientUObjectEditor.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKCloudDeploymentConfiguration.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp, SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp, SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Use `LOCTEXT` instead of `TEXT` for UI elements.
=> Make text localizable

SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
Some improvements to Test Framework Usability (namely Server / Client Id) based on NWX feedback
@mironec @jPinhao-Improbable
=> Improving BP comments and usability based on NWX feedback

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp
We are trying to read a schema object after handing it off. This can cause a crash in rare cases.
=> translator use after transfer crash

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyAndTombstoneTest/DormancyTestActor.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMovement/TestMovementCharacter.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/TestPossessionPawn.cpp
Fixing warnings in compilation of tests
=> Fixing warnings in Test classes

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMovement/CharacterMovementTestGameMode.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMovement/SpatialTestCharacterMovement.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMovement/SpatialTestCharacterMovement.h
Refactored the previously merged Character Movement Test to remove the timer.
In code Documentation
@mironec
=> Test Movement Character Refactoring

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
We were not checking before acking if the RPC was cross server or multicast.
=> [UNR-3872][MS] Ensure we do not attempt to ack cross-server and multicast RPCs.

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/RPCServiceTest.cpp
=> [UNR-3864][MS] Cleanup of RPCService unit tests

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKCloudDeploymentConfiguration.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Changed the edit box used in the dropdown to be less ambiguous.
@jessicafalk @oblm
=> [UNR-3866] Improve edit box in Start Deployment dropdown

SpatialGDK/Source/SpatialGDK/Private/Tests/RPCServiceTest.cpp
=> Automation functions only available with these definitions

SpatialGDK/Source/SpatialGDK/Public/Utils/GDKPropertyMacros.h
Seems to work either way, but other places include it as this so let's change this to be consistent.
@mironec
=> Fix Version.h include

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Dont' call VerifyAndStartDeployment if not running Spatial
@joshuahuburn @Vatyx
=> Suppress invalid error when running in native

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialWorldSettings.h
cherry-pick https://github.com/spatialos/UnrealGDK/pull/2409 back to master
=> reenable multi worker toggle button (#2409)

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
=> Add missing RPCService guard (#2412)

CHANGELOG.md
Associated engine PR: https://github.com/improbableio/UnrealEngine/pull/597
=> [UNR-3955] Update changelog to reflect 4.25.3

SpatialGDK/Source/SpatialGDK/Private/SpatialView/OpList/EntityComponentOpList.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/EntityComponentOpList.h
Op list builder needs a constructor. Missing from the previous merge.
=> Added a constructor to the EntityComponentOpListBuilder.

SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
Add a check missing from PR https://github.com/spatialos/UnrealGDK/pull/2428
=> [UNR-3992] additional replication check

.buildkite/premerge.steps.yaml
=> change windows agent queueid(bake from UNR-3668)

SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp
RPCs are now less likely to be dropped.
Not needed, should have worked.
We should probably have had a unit test, as this could have been caught, but hard to think of that in advance, as it's essentially identical to solving the bug outright. Can do a regression unit test as a follow-up.
N/A
=> [UNR-4008][UNR-3902] Fix RPCs being dropped randomly

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/ManagedWorkerCoordinator.cs
Fixes simplayer auotoconnection when using the DeploymentLauncher helper script.
=> Fix simulated player autoconnection

SpatialGDK/Source/SpatialGDK/Private/SpatialView/OpList/EntityComponentOpList.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/OpList/ViewDeltaLegacyOpList.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewDelta.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/WorkerView.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/EntityComponentTypes.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/EntityDelta.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/EntityView.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/ViewDeltaLegacyOpList.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewDelta.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/WorkerView.h
Changing the interface and implementation details of the view delta to be more useful for entity completeness work.
Internal detail
Not in this PR. Will be following up on this.
=> SpatialTwo

CHANGELOG.md
=> Update upgrade steps to reflect current docs

SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestLBDelegationInterface.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
Fixing poor implementation of Add/RemoveActorDelegation
=> Fixing Add/RemoveActorDelegation

CHANGELOG.md
Tech Writer edit for 0.11 changelog.
=> [DOC-2238] Tech Writer changelog 0.11 edit

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
Merging 4.25 NFR fixes into 0.11 rc
=> Fix for command-line arg in latency test (#2459)

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialViewWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/ConnectionHandler/SpatialOSConnectionHandler.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Added a missing line that was meant SpatialView had great bandwidth usage and terrible latency.
Set flushing to be default enabled.
Clang format changes to the settings header.
Flags involved are all experimental so none.
=> Fix SpatialView latency.

SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/CallbacksTest.cpp
ran them, and tests for callbacks (don't pass yet because the functionality will change to match the test)
=> callback: add tests

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
=> Fix hidden variable

SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
=> Hard Coded Entity Completeness Query Tag Components

CHANGELOG.md
Changed the branch.
*Description*
Tech Writer: Added 0.11 changelog translation.
=> [DOC-2238] Tech Writer: Added 0.11 changelog translation.

RequireSetup, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
whack the tags on the actors
(I thought there would be more to this, but not AFAICT, please correct me if that's wrong)
=> add tags to actors

CHANGELOG.md
Added the translation for changelog 0.10 to 0.11.0-rc. Updated the note section at the top of changelog page, from: v0.8.0 to v0.10.0
=> [DOC-2460] Tech Writer: Added 0.10 changelog translation to 0.11-rc.

SpatialGDK/Extras/git/post-merge
=> Fix post-merge

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
Quick cleanup I happened to notice.
=> Drive by formatting fix

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/Connection/SpatialWorkerConnectionTest.cpp
=> Default enable SpatialView

SpatialGDK/Source/SpatialGDK/Private/SpatialView/Dispatcher.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewCoordinator.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/DispatcherTest.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/SpatialViewUtils.h, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/ViewDeltaTest.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialView/Dispatcher.h
Adds basic tests to the dispatcher, and changes the API to make it slightly nicer to test
probably unnecessary
yes
sparse comments
@jessicafalk @samiwh
=> dispatcher tests

SpatialGDK/Source/SpatialGDK/Private/SpatialView/Dispatcher.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/ComponentTestUtils.h, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/DispatcherTest.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/SpatialViewUtils.h
Found a bug in the dispatcher, so added some more tests, as well as fixed that bug.
Lots!
@samiwh @jessicafalk @ImprobableNic
=> various dispatcher test improvements + fix bug

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/Dispatcher.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewCoordinator.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/CallbacksTest.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/ComponentTestUtils.h, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/DispatcherTest.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/SpatialViewUtils.h, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/ViewDeltaTest.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/Callbacks.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/Dispatcher.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewCoordinator.h
=> Added an entity delta dispatcher.

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverDebugContext.cpp
An assertion is raised in spatial view when sending incorrect instruction (removing or updating a component we do not have)
This is a quick fix to avoid doing that.
A proper fix would base the debug component management on top of a subview.
This was making a test fail, which now passes.
=> [UNR-4253] Fix test interface double removal issue

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DynamicSubobjectsTest/DynamicSubobjectsTest.cpp
Fix include path.
@mironec @eviK88
=> Fix compilation error on Mac

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/VisibilityTest/VisibilityTest.cpp
Reduce tolerance of the Character location and make sure that the move locations are correct.
=> Fix visibility test

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/Components/SpatialPingComponent.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/WorkerRegion.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h, SpatialGDK/Source/SpatialGDK/Public/Schema/SpawnData.h
Missing includes causing Android build failures.
@mironec @mimistiv
=> Fix missing includes causing Android compilation errors

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialOutputDevice.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/WorkerRegion.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/Connection/SpatialConnectionManagerTest.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Applied clang formatting.
I added everyone who last changed these files for you to check if your clang-format runs when making new commits. Please note that the way it currently works, the formatting changes will be in the unstaged diff after your commit, so you need to amend your commit, or add them in a new commit.
=> Run clang format on recent changes

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
Added server side log when client times out.
Servers now log a warning message when detecting a client has timed out.
@alastairdglennie @mironec
=> Add log message for client timeout

.buildkite/premerge.definition.yaml, .buildkite/release.definition.yaml
Switch to using teams which are automatically managed by groupsync.
If there are any mistakes or other manual teams that we missed, please feel free to add commits to this branch to resolve.
Immediately post-merge, roll out permission changes via `circle`:
OR
* Change generated via sourcegraph campaign https://code.i8e.io/users/ca-johnson/campaigns/Q2FtcGFpZ246MQ==
* Pre-merge pipelines may fail with "Authorisation Denied". Please click "Rebuild" in Buildkite to authorise the build to run.
* You may need to push pipelines individually with `circle ci pipeline push` where they do not appear in the output of `circle ci pipeline check`
* Contact @support-eng-velocity in #eng-velocity-support slack channel if you have questions or issues
=> Use Buildkite Auto-Managed Groupsync Teams

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
Make sure the bit in the startup system that signals the worker entity is ready works.
=> Added an authority self constraint to the server worker entity

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h
Cancel sending heartbeat component update when controller is destroyed.
@samiwh
=> Cancel heartbeat on controller destruction

SpatialGDK/Extras/schema/query_tags.schema, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/WellKnownEntitySystem.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h, SpatialGDK/Source/SpatialGDK/Public/Interop/WellKnownEntitySystem.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h, SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Moves startup logic and other well known entity logic to its own system.
=> well known entity system

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracer.cpp
=> Fix Android builds

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDKFunctionalTests.Build.cs, SpatialGDK/SpatialGDK.uplugin
FunctionalTesting part of public dependencies.
=> Fix user event tracing build errors

RequireSetup, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Fix when sending an rpc before the rpc service has ticked (actor beginplay)
@jacquese
=> [UNR-4439] Bugfix/rpc crash

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
=> Moved the bIsReadyCheck to before triggering begin play.

SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
Reapply a fix that was lost in the rework (https://github.com/spatialos/UnrealGDK/pull/2637)
@jacquese
=> Don't log 'Sent some but not all overflowed RPCs' if no RPCs were sent

CHANGELOG.md, Setup.bat, Setup.sh, SpatialGDK/Extras/core-sdk.version, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKModule.h, SpatialGDK/Source/SpatialGDK/Public/Utils/WorkerVersionCheck.h
[JIRA](https://improbableio.atlassian.net/browse/UNR-2544) - note: requests (on the Jira ticket) for better error logging in `Setup.bat` will come in a separate PR
At compile time, check the version of the Worker SDK against the version used by UE 
Enter incorrect version and it doesn't compile
=> UNR-2544: Worker SDK version check

SpatialGDK/Source/SpatialGDK/Public/Utils/WorkerVersionCheck.h
Better error log missed in https://github.com/spatialos/UnrealGDK/pull/2683
=> fix: error message

Setup.sh
Fix missing setup.sh changes that went into v15 update.
=> Update setup.sh to v15

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSnapshotManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialOSWorkerInterface.h, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/CommandRetryHandler.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/Connection/SpatialOSWorkerInterface/SpatialOSWorkerConnectionSpy.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/Connection/SpatialOSWorkerInterface/SpatialOSWorkerConnectionSpy.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/Connection/SpatialWorkerConnectionTest.cpp
Enables using the retry handler for some of the possible commands.
=> Enable command retry handler

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialWorkerFlags.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialWorkerFlags.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/SpatialWorkerFlags/SpatialWorkerFlagsTest.cpp
Instead of exposing the worker op in the worker flag api, we are now using FStrings directly.
=> Update worker flag api 

SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLatencyTracer.h
Build fix when using latency tracing
=> NFR build fix 

SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
Some what of a revert to a change that was made the fixes Example project android CI.
=> Example Project Android CI Fix

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Comes from: https://github.com/spatialos/UnrealGDK/pull/2765
=> Fix for 4.26

SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Should check existence of the spatial output window
=> Check existence of the output log

SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Same as: https://github.com/spatialos/UnrealGDK/pull/2771
=> Check existance of spatial output log

CHANGELOG.md, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestFlowController.h
Pulling this into the RC: https://github.com/spatialos/UnrealGDK/commit/88b353f1da8ab796bfa7ed3759e6b8eae1d9a6aa
=> Fix functional test race in RC

SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h, SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
https://improbableio.atlassian.net/browse/UNR-4694
Fixes transient issue introduced in v15 -- not required.
Ran tests generating schema after deleting Unreal object classes.
=> Sanitize schema database

SpatialGDK/Extras/schema/server_worker.schema
Update server worker component schema to match expectations. This didn't cause a problem because our schema usage was consistent, however we best to keep schema accurate.
=> Add system entity reference

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp, SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
same as https://github.com/spatialos/UnrealGDK/pull/2780 but targeting master
=> make inspector exe executable on mac

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h, SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
https://improbableio.atlassian.net/browse/UNR-4745
@improbable-valentyn @cmsmithio
=> Added flag for deleting previously generated schema in commandlet

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Adding Simon's PR here to the RC: https://github.com/spatialos/UnrealGDK/pull/2779
Did not add the test code to reduce the overall code added to the RC.
=> Adding UNR-988 fix into the RC

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
Description
Fix the wrong URL when starting cloud delopment in CN
Release note
N/A
Tests
CN
Creat Deployment
image
List Deployment
image
Documentation
N/A
=> Bugfix/unr 3349 Fix the wrong URL when starting cloud delopment in CN

CHANGELOG.md
Changelog for an engine fix 
4.26 https://github.com/improbableio/UnrealEngine/pull/761
4.25 https://github.com/improbableio/UnrealEngine/pull/768
4.24 https://github.com/improbableio/UnrealEngine/pull/763
=> Bugfix/unr 4478 windows dll crash fix 

CHANGELOG.md
Add bugfix changenote for https://github.com/improbableio/UnrealEngine/pull/757
=> Add bugfix changelog note

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
Pulling change over from master to RC
https://improbableio.atlassian.net/browse/UNR-4758
=> Reduce log verbosity

SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/ClientServerRPCService.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/ClientServerRPCService.h
This PR ensures RPCs which were previously not executed are executed on checkout 
Follow up
@m-samiec @jacquese
=> Ensure RPCs are executed on checkout

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracer.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingTest.h
Follow up ticket to investigate why the map is empty: https://improbableio.atlassian.net/browse/UNR-4818
=> Fixing incorrect assumption made in the event tracer.

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
Upgrade inspector to: 15.0.0-preview-2
=> Upgrading inspector version to fix RC issues.

SpatialGDK/Source/SpatialGDK/Private/Interop/ClientConnectionManager.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/ClientConnectionManager.h
Follow up PR comments on https://github.com/spatialos/UnrealGDK/pull/2852.
=> sami comments

SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
=> Fix schema gen tests in 012 rc

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
Reapplied UNR-4441 fix.
SpatialTestHandoverReplicationMap now passes.
Added a changelog entry.
=> UNR-4950: Reapplied fix from UNR-4441

SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h, SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SchemaGenObjectStub.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SchemaGenObjectStub.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Parsed the schema.json created after running the schema compiler in order to extract the actual content of the component sets.
Ran functional tests to ensure no regression.
=> [UNR-4666] Read schema bundle file to get the component sets

SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestRequireHandler.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialComponentTest/SpatialComponentTestCallbackComponent.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialComponentTest/SpatialComponentTestDummyComponent.h
Small things to fix tests maybe.
Mac CI will probably still fail while we have the GAS tests in there.
=> Fix nightly tests (maybe)

CHANGELOG.md, ci/unreal-engine.version
Remove 4.24 from our builds to make it official we don't support it on 0.12+
=> Remove 4.24 from builds

RequireSetup
Increment RequireSetup so `Setup.bat` runs automatically when pulling new schema changes.
@ImprobableNic
=> Increment RequireSetup for routing worker changes

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/SpatialTestPropertyReplication.cpp
Correctly state the number of clients in my test, 3.
Not required
This runs in CI as pre-merge.
https://brevi.link/how-to-test-unrealgdk
=> Correctly state the number of clients in my test.

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverDebugContext.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/WellKnownEntitySystem.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewCoordinator.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebuggerSystem.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/Interop/WellKnownEntitySystem.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewCoordinator.h
Generous amounts of copy pasting from one class (sender) to another (actor system). Removes some dependencies on static component view, but not all of them because I don't want to rabbit hole again.
=> Unr 4845 move sender

SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
=> Fix shipping builds

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/LifetimeComponent.cs
Test: https://buildkite.com/improbable/unrealgdk-nfr/builds/3916
=> Fix clients not starting in NFRs

SpatialGDK/Source/SpatialGDK/Private/SpatialView/ComponentData.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ComponentData.h
Fixed a bug where sending updates caused the memory used by the view to grow.
=> Changed ApplyUpdate to also resize the component.

ci/gdk_build.template.steps.yaml
=> [UNR-4369] Disable FastBuild for now, due to issues with the cache

.buildkite/premerge.steps.yaml
PR removes triggers for old CI and only runs new CI
@mironec @simonsarginson
=> Only use new CI

.buildkite/premerge.steps.yaml
CI versioning changes:
https://github.com/spatialos/UnrealGDKTestGyms/pull/347
https://github.com/spatialos/UnrealGDK/pull/3015
https://github.com/improbableio/UnrealEngine/pull/855
https://github.com/improbableio/UnrealEngine/pull/852
=> [UNR-5150] Update premerge.steps.yaml

SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestRequireHandler.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestRequireHandler.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestReplicatedStartupActor/SpatialTestReplicatedStartupActor.cpp
What it says above.
Not required, I think?
Ran the test 100 times.
Not needed.
@razvan-at-improbable @improbable-valentyn
=> [UNR-5326] Fix StartupActorTest and make Requires return bools

SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.h, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Old code, not used anymore (replaced by component sets).
@m-samiec @mironec
=> Remove unused arrays from schema db

.buildkite/premerge.steps.yaml, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
Add virtual override implementation of GetActorEntityId() to USpatialNetDriver()
Manual test.
=> [UNR-5365] Add SpatialNetDriver implementation of GetActorEntityId()

CHANGELOG.md, SpatialGDK/Extras/insights-proxy/InsightsProxy.py, SpatialGDK/Extras/insights-proxy/README.md
Cherry pick insights changes for 0.13
=> Cherry pick Insights work UNR-5207

SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
Removed unnecessary assert introduced in https://github.com/spatialos/UnrealGDK/pull/3030
Not required
Existing automated tests
None
=> UNR-5442: Removed unnecessary ActorSystem assert

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/AlwaysInterestedTestActors.h
Make always interested test actors, always replicate to fix rep graph test.
=> Fix Always Interested tests in rep graph

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialWorldSettings.h, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialTestSettings.cpp
Cherry-pick of https://github.com/spatialos/UnrealGDK/pull/3038
=> Cherry-pick - Feature/unr 5296 extend test setting overrides for groups of maps

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
=> [UNR-5424]Work around fix for spatial debugger crashing after client travelling

RequireSetup, Setup.bat
Copy schema compiler and snapshot converter to spatial/tools directory for easy access.
=> Copy tools to spatial dir

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
Instanced actor components can be null, who knew.
=> Fix package map crash

CHANGELOG.md
Updated CHANGELOG for 
https://github.com/improbableio/UnrealEngine/pull/916
https://github.com/improbableio/UnrealEngine/pull/915
=> [UNR-5223] Clean up references to bUseNetOwnerActorGroup

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingTest.h
Corresponding GDK PR: https://github.com/spatialos/UnrealGDKTestGyms/pull/376
=> Adding override settings to the event trace test

CHANGELOG.md
Update `CHANGELOG.md` about **_how to control sim players' lifetime_** feature.
@simonsarginson
=> Add how to control sim players' lifetime feature logs.

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
Calculate and cache worker id as hash in game instance.
Minor internal change - manual test.
=> [UNR-5544] Calculate and cache worker id as hash in game instance

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/OwnershipLockingPolicy/OwnershipLockingPolicyTest.cpp
Fixed a test flake stemming from an actor's role being changed.
I ran existing test suite.
Release note.
=> UNR-5429: Fixed test flake

.buildkite/premerge.steps.yaml
Moving forward to 1.3.
Fixes the floating head bug and enables NFR builds
=> Updating to new CI version 1.3

CHANGELOG.md
Updated CHANGELOG.md with Visual Logger support for multi worker scenarios.
=> [UNR-5594] Updated CHANGELOG.md with Visual Logger Improvements

CHANGELOG.md
Changelog entry for https://github.com/spatialos/UnrealGDK/pull/3074
=> UNR-4843: Added a changelog entry

SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
change requirenot test method parameters to be NotExpected instead of Expected
@miron
=> Rename test requirenotequal expected param to notexpected

CHANGELOG.md, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowControllerSpawner.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestFlowController.h
This reverts commit dff292c758656ac8d770e78fc0f8c4446c5f940e.
=> Revert [UNR-5579] (again)

SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Request from docs team. Removing mention of Runtime Variant as it's no longer relevant,
=> Update default template displayname

CHANGELOG.md, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp, SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
=> [UNR-5559] Fix: create snapshot folder at start of deployment, delete if empty for interop with squid snapshot endpoint

CHANGELOG.md
Make a 0.14.0-rc section in Changelog
=> Make a 0.14.0-rc section in Changelog

.buildkite/premerge.steps.yaml
Update default branches to 0.14.0-rc
=> Update default branches to 0.14.0-rc

CHANGELOG.md
Fixed changelog after erroneously added the changelog to the wrong section.
Fixed.
No changes to code added.
=> UNR-4849: Fixed changelog

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/OwnershipCompletenessHandler.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/OwnershipCompletenessHandler.h
Defer ownership completeness refreshes to be processed once per frame.
@improbable-dmitrii
=> Add Ownership Completeness advance

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
=> Fixed dormancy unresolved ref checking (#3208)

CHANGELOG.md
Add gameplay debugger multi worker support to changelog.
=> [UNR-5773] Add Gameplay Debugger to changelog

CHANGELOG.md, RequireSetup, SpatialGDK/Extras/schema/gameplay_debugger_component.schema, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverGameplayDebuggerContext.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverGameplayDebuggerContext.h, SpatialGDK/Source/SpatialGDK/Public/Schema/GameplayDebuggerComponent.h, SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
This PR contains the following changes against the 0.14.0-rc of the GDK branch:
- cherry-pick 1bb9b6ac1c0e64cd5dca653488d43eaa43f7af34: Add track player mode to gameplay debugger
- cherry-pick 6e658647f81414fa2940fae55754ac959c3c9f97: Add Gameplay Debugger to changelog
=> UNR-5777 gameplay debugger backports

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestMultipleOwnership/SpatialTestMultipleOwnership.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestMultipleOwnership/SpatialTestMultipleOwnership.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/VisibilityTest/VisibilityTest.cpp
Fix the visibility test flake by fixing the multiple ownership test.
None
Ran CI 4 times.
N/A
@joshuahuburn
=> [UNR-5726] Fix visibility test flake

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/ClaimPartitionHandler.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/InitialOnlyFilter.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSnapshotManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslationManager.h, SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h, SpatialGDK/Source/SpatialGDK/Public/Interop/ClaimPartitionHandler.h, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h, SpatialGDK/Source/SpatialGDK/Public/Interop/CreateEntityHandler.h, SpatialGDK/Source/SpatialGDK/Public/Interop/EntityQueryHandler.h, SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h, SpatialGDK/Source/SpatialGDK/Public/Interop/InitialOnlyFilter.h, SpatialGDK/Source/SpatialGDK/Public/Interop/ReserveEntityIdsHandler.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialCommandsHandler.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialOSDispatcherInterface.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSnapshotManager.h, SpatialGDK/Source/SpatialGDK/Public/Utils/EntityPool.h
A bit of refactoring around the various spatial command handlers, which IMO were unnecessarily scattered between different object, and using delegates where simple TFunction could be used.
=> Refactor command handlers

SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp
Fix test re-running.
N/A
Ran locally.
N/A
=> [UNR-5783] Fix test reruns

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverGameplayDebuggerContext.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverGameplayDebuggerContext.h
Gameplay Debugger tracks focused actor across interest boundaries.
Manual test gym.
=> [UNR-5791] Gameplay Debugger tracks focused actor across interest boundaries

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestMultipleOwnership/SpatialTestMultipleOwnership.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestMultipleOwnership/SpatialTestMultipleOwnership.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/VisibilityTest/VisibilityTest.cpp
Cherry-pick of 9c776e3fc293d4eab23f9c674763221748a043bc for the RC to reduce flakiness.
=> [UNR-5726] Fix visibility test flake - cherry pick for RC

.buildkite/premerge.steps.yaml
Complementary PR to improbableio.atlassian.net/browse/UNR-5765
=> Update default CI branch to 0.14.0-rc

SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/RegisterAutoDestroyActorsTest/RegisterAutoDestroyActorsTest.cpp
Some better logging, small refactors.
We should get more information if this fails.
Not required.
Ran the tests 300 times.
N/A
idk
=> [UNR-5638] Add better logging for the RegisterAutoDestroyActor tests

SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/GameModeReplicationTest/GameModeReplicationTest.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestLoadBalancingData/SpatialTestLoadBalancingData.h
Fix offloading by adding some special considerations for it and fixing statics querying layered lb strategy directly.
Also hides some things in dropdowns, just bothered me.
N/A? Should have worked
Ran the example project
N/A
idk
=> [UNR-5809] Fix offloading

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/Utils/SchemaBundleParser.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/Utils/SchemaBundleParser.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h, SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/SpatialTestReplicationConditions.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Feature added support for DOREPLIFETIME_ACTIVE_OVERRIDE for better unreal 4 parity. Does not work with clearable types, currently this is only TArrays / lists.
Added note to Release notes.
Uncommented relevant section in SpatialTestReplicationConditions
Tested by running functional test: SpatialTestReplicationConditions, this is also run by CI on premerge.
@m-samiec @samiwh @mironec
=> [UNR-5212] Feature/add rep override capability

SpatialGDK/Source/SpatialGDK/Private/Interop/ClaimPartitionHandler.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingStrategy.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/PartitionManager.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/ClaimPartitionHandler.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialCommandsHandler.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyLoadBalancingStrategy.h
Refactoring : Remove some boilerplate code in favour of delegates through the use of SpatialGDK::FCommandHandler
=> Cleanup the centralized load balancer by using SpatialCommandHandler

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
=> [UNR-5843] Update SpatialActorChannel.cpp

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
This will make it easier for us to notice if the ensure is triggered. Relevant for https://improbableio.atlassian.net/browse/UNR-5844
@ImprobableNic as you requested 😄
=> Change packagemap warning to ensure.

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/AlwaysInterestedTestActors.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/RelevancyTestActors.cpp
Tweak framework to use correct NCD values
=> Cleanup NCD values

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialHandoverManager.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPartitionSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPartitionSystemImpl.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPartitionSystemImpl.h, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStrategySystem.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LBDataStorage.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingPartitionSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingStrategy.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/PartitionManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Schema/StaticSymbols.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialHandoverManager.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPartitionSystem.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LBDataStorage.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyLoadBalancingCommon.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyLoadBalancingPartitionSystem.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyLoadbalancingComponents.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LoadBalancingTypes.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/PartitionManager.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
Add the ability to add and access load balancing metadata on partitions.
Needs https://github.com/improbableio/UnrealEngine/pull/1027
=> [UNR-5632] Add partition metadata subsystem

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/AlwaysInterestedTestActors.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/RelevancyTestActors.cpp
Re-add https://github.com/spatialos/UnrealGDK/pull/3282
Additional TestGyms PR - https://github.com/spatialos/UnrealGDKTestGyms/pull/459
=> Cleanup NCD values (#3282)

CHANGELOG.md, RequireSetup, SpatialGDK/Extras/core-sdk.version, SpatialGDK/Source/SpatialGDK/Public/Utils/WorkerVersionCheck.h
**UE 426**: https://github.com/improbableio/UnrealEngine/pull/1039
**UE 425**: https://github.com/improbableio/UnrealEngine/pull/1040
**GDK**: https://github.com/spatialos/UnrealGDK/pull/3308
**Example**: https://github.com/spatialos/UnrealGDKExampleProject/pull/298
**Test Gyms**: https://github.com/spatialos/UnrealGDKTestGyms/pull/465
**Engine Net Test**: https://github.com/improbable/UnrealGDKEngineNetTest/pull/98
**NFR Benchmark**: https://github.com/improbable/nfr-benchmark-pipeline/pull/181
=> [UNR-5875] upgrade to worker sdk 15.3.1

SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
This PR fixes the logic of checking required runtime ports in LocalDeploymentManger.cpp
=> Bugfix for UNR-5934

SpatialGDK/Source/SpatialGDK/Private/Interop/CrossServerRPCHandler.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/CrossServerRPCSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/CrossServerRPCHandlerTest.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/CrossServerRPCHandler.h
Better randomness by abusing FGuids, and larger buffer by increasing retention to 30 seconds.
Both of these changes worsen performance, but I don't think it will be too significant.
N/A ?
Ran tests a LOT of times.
N/A ?
idk yet
=> Make cross-server RPCs more reliable

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialConditionMapFilter.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/SpatialTestReplicationConditions.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/TestReplicationConditionsActor.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/TestReplicationConditionsActor.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SchemaGenObjectStub.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SchemaGenObjectStub.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
This reverts commit c221e51375761230218e797e745a5c0e0985e7d9.
=> Revert "Add Authoritative Server Only Replication (#3331)"

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp, SpatialGDK/Source/SpatialGDK/Private/Schema/UnrealObjectRef.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h
So don't post or commit non-public information.
Replaces all usages of PendingKill with the clearer and more safe IsValid.
N/A
Normal tests. Shouldn't cause any issues.
N/A
=> [INT-57] Replace all usages of IsPendingKill with IsValid

SpatialGDK/Source/SpatialGDK/Public/EngineClasses/Components/SpatialPingComponent.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialInterestConstraints.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialDebugger.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetricsDisplay.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialStatics.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestHandoverReplication/SpatialTestHandoverActorComponentReplication.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestReplicatedStartupActor/ReplicatedStartupActor.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestWorldComposition/SpatialTestWorldComposition.h
So don't post or commit non-public information.
Just to get rid of some cooking warnings.
Also needs an example project and test gyms version.
N/A
Normal tests, should be harmless.
N/A
???
=> [INT-57] Zero-initialize UProperties to remove some warnings

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Session log recording is only available post 15.3.0. Disable by default, and hide from config menu.
@mironec @improbable-dmitrii
=> Default disable session log recording

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialWorkingSetSubsystem.cpp
=> Fix working set subsystem include
