spatialos/UnrealGDK

docs/setup-and-installing.md
Update setup-and-installing.md to cite BuildWorker.bat instead of Build.bat, which is not a file.
It works now.
=> Update setup-and-installing.md to cite BuildWorker.bat

Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.cpp
Fixes a missed ```GetName()``` -> ```GetPathName()``` for recognising components in Actors and their associated spatial type binding files.
Manually tested with vehicles to see that the WheeledVehicleMovementComponent4W replicates (automated tests broken for now).
No documentation needed
@danielimprobable
=> Fix TypeStructure ComponentClasses

Source/SpatialGDK/Private/SpatialActorChannel.cpp
-------
We have incorrectly provided the class name instead of path name in `UpdateGlobalStateManager`. This PR fixes that.
=> Use path instead of class name in GSM update

Source/SpatialGDK/Private/SpatialInterop.cpp
Fixes a small bug with UNR-493, where classes which have typebindings never call OnCreateEntityResponse().
Manually tested with a class which had typebindings and observed that OnCreateEntityResponse was called.
No documentation needed.
@mpmisko
=> Add callback for classes with typebindings

Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.h, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.h
-------
https://improbableio.atlassian.net/browse/UNR-499
Currently, if you nest a blueprint-defined struct in an array (or array of structs of arrays of structs...), our generated typebinding will contain invalid Types which refer to the blueprint struct in memory. The same problem happens with passing in blueprint-defined structs to RPC calls.
Since BP structs don't get compiled into C++ code, we will generate their definition manually inside the header file of generated typebindings. To get `SerializedBin` to work, we will load the BP asset at runtime instead of calling …
=> Support Blueprint Defined Rep Structs

Source/SpatialGDK/Private/SpatialNetDriver.cpp
Allowed multicast RPCs to be invoked from servers on objects that don't have owners. This corresponds to native Unreal's functionality.
Testsuite PR: https://github.com/spatialos/UnrealGDKTestSuite/pull/98
TestSuite already has suitable tests, which now run correctly.
=> Fix multicast rpcs so they can be issued without an owner on servers

Source/SpatialGDK/Private/SpatialPackageMapClient.cpp
The editor could crash on closing a play-in-editor session, due to trying to find a removed actor.
Closed a PIE session and it did not crash.
None
=> Remove unused Actor reference

Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/SpatialGDKEditorInteropCodeGenerator.cpp, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.h, Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.h
Blueprint class typebindings had compile errors when referencing other blueprint actors and structs in certain permutations. Further support has been added.
This change also moved the dependent header includes to the header file so they can be utilized by the forward blueprint type declarations.
Testsuite PR: https://github.com/spatialos/UnrealGDKTestSuite/pull/100
Testing blueprint classes with -
Replicated blueprint structs that contain blueprint actors
Replicated blueprint structs that contain blueprint structs
Rpcs with blueprint actors
Rpcs with blueprint structs
@improbable-valentyn @wanqizhu
=> Furthered blueprint typebinding support

Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeStructure.cpp
Based on the bug report from UNR-526, there was a bug with subobject classes having their correct SchemaTypes file being overwritten by the recursive call of `GetRPCTypeOwners`. This bugfix simply prevents the recursive call so the correct file is always present and not overwritten.
Added a subobject component to TestSuiteCharacter and confirmed that the SchemaTypes file is correctly generated after the fix.
TestSuite still runs correctly.
=> UNR-526 Fixed RPCTypeOwners overwriting correct Schema Types file

Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp, Source/SpatialGDK/Private/SpatialMemoryWriter.cpp
Include all replicated property includes, not just those originating from a non-native class.
This PR also includes a drive-by for spatial memory writer creating stably named references that I discovered when investigating the ability system compatibility.
Ran testsuite tests.
@girayimprobable @danielimprobable
=> UNR-529: Increased scope of type binding includes.

Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/InteropCodeGenerator/TypeBindingGenerator.cpp, Source/SpatialGDK/Private/SpatialTypeBinding.cpp, Source/SpatialGDK/Public/SpatialTypeBinding.h
UStruct::SerializeBin() doesn't respect replicated properties. Replace it with the implementation that was created by @improbable-valentyn for dynamic type bindings.
This was also required for the ability system component.
Ran TestSuite, and it's all okay.
=> unr-351: Replace use of UStruct::SerializeBin() with custom SerializeStruct

Source/SpatialGDK/Private/SpatialNetDriver.cpp, Source/SpatialGDK/Public/SpatialNetDriver.h
This reverts commit e7e00cf08b418ea3cb6db5899ffc5e68e1ce765e.
Needed to pass CI, until we get a new engine build.
=> Revert UNR-518 to unblock CI

Source/SpatialGDK/Public/Interop/SpatialTypebindingManager.h
UPROPERTY() to avoid references being garbage-collected.
=> Add UPROPERTY

Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, Source/SpatialGDK/Private/Interop/SpatialView.cpp, Source/SpatialGDK/Public/Interop/SpatialView.h
I was running into this issue during the last Scavengers visit but I just commented out the checkf which was the problem and moved on. Finally found it.
Anytime a entity is moving between a checkout radius, when the entity came back, the subobjects would clash with their pre existing NetGUIDS
=> Fixed lingering Subobject GUIDs when an Actor is deleted

Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
If we don't remove it from the map, you later retrieve the pointer to a channel that was or is being destroyed.
=> Remove actor channel from EntityToActorChannel map on cleanup

Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Cleanup would crash when the NetDriver or World didn't exist.
=> Fixed SpatialActorChannel::Cleanup from crashing in editor

Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, Source/SpatialGDK/Private/Interop/SpatialView.cpp, Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h, Source/SpatialGDK/Public/Interop/SpatialReceiver.h, Source/SpatialGDK/Public/Interop/SpatialView.h
This is what was happening before dynamic typebindings. Backported the code.
=> Remove subobject NetGUIDs during RemoveComponent

Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, Source/SpatialGDK/Private/Interop/SpatialSender.cpp, Source/SpatialGDK/Private/Interop/SpatialTypebindingManager.cpp
Reasons for this change:
1. Lets say there was Actor Component `AnimalComponent` and `DogComponent` and `CatComponent` both extend off of it but you only generate typebindings for `AnimalComponent` and `CatComponent`. You put a `DogComponent` and `CatComponent` on an Actor. You then receive an update for `AnimalComponent`. Which Actor Component does this update belong to?
2. If a derived class has more replicated properties, and is using base class schema, it won't work due to handle checking.
=> Schema for a specific class has to be generated for it to replicate

BuildGDK.bat, Source/SpatialGDK/Private/EngineClasses/SpatialNetBitWriter.cpp, Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp, Source/SpatialGDK/Private/Utils/ComponentFactory.cpp, Source/SpatialGDK/Private/Utils/ComponentReader.cpp, Source/SpatialGDK/Public/Schema/UnrealObjectRef.h, Source/SpatialGDK/Public/Utils/ComponentReader.h, Source/SpatialGDK/Public/Utils/SchemaOption.h, Source/SpatialGDK/Public/Utils/SchemaUtils.h
This PR introduces our own in-house GDK `Option` type called `TSchemaOption`, which will be used to represent `option` in schema types and components.
**Why are we introducing our own type?**
Since dynamic typebindings has let us completely switch over to the C API, we're trying to remove our dependency on the C++ worker SDK. `worker::Option` was one of the last places we were depending on it.
**Why aren't we using `TOptional` which comes with Unreal?**
`TOptional` would be great to use but unfortunately is implemented by holding an instance of `T` rather than a pointer to `T`. Which means a `TOptional` can't hold a type which has a `TOptional` of itself, which is exactly what UnrealObjectRef does so it's not suitable for our use case.
**Why not use TUniquePtr?**
`TUniquePtr` would …
=> TSchemaOption Implementation :eyes:

Plugins/SpatialGDK/SpatialGDKEditorToolbar/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorGenerateSnapshot.cpp, Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp, Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, Source/SpatialGDK/Private/Interop/SpatialSender.cpp, Source/SpatialGDK/Private/Interop/SpatialView.cpp, Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, Source/SpatialGDK/Public/Interop/SpatialReceiver.h, Source/SpatialGDK/Public/Interop/SpatialSender.h, Source/SpatialGDK/Public/Interop/SpatialView.h, Source/SpatialGDK/Public/Schema/Component.h, Source/SpatialGDK/Public/Schema/DynamicComponent.h, Source/SpatialGDK/Public/Schema/Rotation.h, Source/SpatialGDK/Public/Schema/StandardLibrary.h, Source/SpatialGDK/Public/Schema/UnrealMetadata.h
Reason for the change is that the `Metadata` component was clashing with a symbol found in some Xbox libs.
=> Prefixed "Spatial" to all hand written components

SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
-------
Fix crash on missing UnrealMetadata when closing PIE instance.
This still has the problem of deleting the stably replicated entities.
@joshuahuburn
=> Fix crash on missing UnrealMetadata when closing PIE instance

SpatialGDK/Source/Private/EngineClasses/SpatialGameInstance.cpp
-------
Log an error when you have `Spatial Networking` checked but `SpatialNetDriver` is not found so it's easier for developers to notice if they didn't set up the GDK correctly.
=> Error log if SpatialNetDriver not set up correctly

SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/Private/EngineClasses/SpatialGameInstance.cpp, SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/Public/EngineClasses/SpatialActorChannel.h
Added a retry for reserving an entity id for an Actor channel. Since this should be reliable, it will keep on retrying until it succeeds. I've added this since I would see reserve entity ids fail in Scavengers due to the large amount of processing that happens at startup.
=> Added a retry for reserving an entity

SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/Private/Interop/SpatialView.cpp, SpatialGDK/Source/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/Public/Interop/Connection/SpatialWorkerConnection.h, SpatialGDK/Source/Public/Interop/SpatialSender.h, SpatialGDK/Source/Public/Interop/SpatialView.h, SpatialGDK/Source/Public/Schema/StandardLibrary.h
-------
Implemented the component interest. The logic is pretty much the same as in static typebindings, except this also takes subobjects into account.
There is a race condition caused by checking out the entity before having authority, which is also present in the master. [Miron's fix](https://github.com/spatialos/UnrealGDK/pull/309) for it is in review.
It may make sense to port the fix onto DTB and add it do this branch before merging this PR.
1. Add a replicated property with a condition `OwnerOnly`.
1. Increment it on the server.
1. Observe that only the owning client …
=> Dynamic component interest

SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
If the actor has an owner, use the owner to dictate it's spatial position. Fixes position issues in Scavengers.
@girayimprobable @m-samiec
=> Use Owner for Spatial Position

SpatialGDK/Source/Private/EngineClasses/SpatialGameInstance.cpp
-------
Fix native networking not working after running with Spatial networking once.
UnrealEngine PR: https://github.com/improbableio/UnrealEngine/pull/26
1. Run with Spatial networking.
1. Toggle Spatial networking.
1. Run with native networking, observe it doesn't break.
1. Run with Spatial networking, observe it still works.
@joshuahuburn
=> Fix native networking not working after running with Spatial networking once

SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp
Check should not crash if subobject is duplicated. Should just return.
=> Fixed check for subobject

Setup.bat
-------
This is following feedback that pause is triggered at the end of the Setup.bat
Run the command `set NO_PAUSE=1 && Setup.bat` successfully without a pause and ran Setup.bat without additional variable with a pause.
No docs required
=> Update the setup.bat to include a pause

SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/Public/Interop/SpatialSender.h, SpatialGDK/Source/Public/Schema/StandardLibrary.h
-------
Re-adding the functionality for resending reliable RPCs.
The crash observed by @Vatyx was fixed by initializing the RPC params before copying. `SpatialSender.cpp:33`
Also took the opportunity to move the response handling into the `SpatialReceiver`, as well as add some missing includes that went unnoticed because of unity build.
=> [UNR-556] Re-add resending reliable RPCs

SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
-------
An error message when receiving component data for unknown components wasn't properly printing out the component ID.
Manually tested with missing components in the snapshot.
=> Fixed error message around unknown components

SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp
We weren't including blueprint inherited components in a Class's subobject, so we weren't attaching the proper Spatial components. This fixes that.
=> Include blueprint inherited components in a Class's subobjects

SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
As soon as we know the entity id for an actor, we can at this point refer to it and all of its subobjects through UnrealObjRefs. Therefore we can register an Actor with the PackageMap on entity id reservation rather than during the AddEntityOp.
=> Resolve actors as soon as possible

SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/Public/Interop/Connection/SpatialWorkerConnection.h
-------
In the locator connection flow, If getting the deployment list fails, it will continue to attempt to connect and usually crash with a cryptic error. This is a temporary fix that just early-outs from the connection attempt, as a workaround until a proper solution for UNR-576 is completed.
Tested manually by connecting with a bad login token, and to a deployment that doesn't exist.
n/a
@m-samiec @girayimprobable
=> Early-out of connection attempt if getting deployment list fails.

SpatialGDK/Source/Private/Utils/ComponentReader.cpp
As we don't support net delta serialization within spatial, to enable functionality of the FFastArraySerializerItem callbacks (see NetSerialization.h), we do a dummy serialize which does a brute check on the array elements and calls the appropriate add/remove callbacks. As we've lost the array context, it's not possible to deduce a change event. We could add this by including the replication id with each element, but as we're only supporting the ability system component, hopefully this will suffice.
This change set also requires a engine change - https://github.com/improbableio/UnrealEngine/pull/23
Works with my local ability system test, but ideally we test this against scavengers.
Incoming - I'll add a section on us not supporting Net Delta Serialize.
@improbable-valentyn @Vatyx
=> Use spatial fast array serialize

SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.cpp
This removes the red warnings we get when launching Spatial since we were including core_types.schema when it didn't need to be.
=> Only include core_types.schema if it's needed

SpatialGDK/Source/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/Public/Utils/ComponentReader.h
-------
We were using the same ObjectReferencesMap (in `ComponentReader`) to mark unresolved references to root level objects and the ones within arrays. Which meant that upon resolution, `SpatialReceiver` just memcpy'd using the in-array offset, which is usually where the `vtable` of the parent object would be. Now we properly use a hierarchy of ObjectReferenceMaps.
Made a branch of StarterProject (`gym-array-of-uobjects`) that exhibits the behavior, verified that references got replicated correctly afterwards. 
No need
@davedolben …
=> Fix corruption caused by replication of obj references in arrays

SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/Private/Interop/SpatialSender.cpp
When spawning on a server which wasn't authortative over the spawner, the PlayerState wasn't resolved by the time `SpatialActorChannel::SpatialViewTick` was called the first time, leading the client to lose authority over the character. This fixes that by making the condition for `bNetOwned` to be true to be when an Actor has a corresponding PlayerState.
@improbable-valentyn @danielimprobable
=> Be able to spawn on workers which don't have authority over the spawner

SpatialGDK/Documentation/content/singleton-actors.md
This doesn't show up as an error on the github version of the docs because I guess it automatically detects a list then generates the numbers, but on the Spatial Docs page both numbers of the list are "1."
=> fixed numbering of list in singleton actors doc page

SpatialGDK/Source/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/Public/Schema/Component.h
-------
TL;DR: Stuff was broken. This fixes it.
The first one is the compilation error hidden by unity build.
The second is a crash caused by `UPROPERTY` being removed from `EntityRegistry`, which results in `EntityRegistry` being garbage collected.
=> Fix broken stuff

SpatialGDK/Source/Private/Interop/SpatialStaticComponentView.cpp, SpatialGDK/Source/Public/Interop/SpatialStaticComponentView.h, SpatialGDK/Source/Public/Schema/Component.h
Fixes Linux build support.
Klang compiler was not happy with uneeded `typename` identifiers in `Component.h` and `SpatialStaticComponentView.h`
Tested? Linux Development works on my machine.jpeg
Reviewers:
@danielimprobable @Vatyx
=> Fix linux build support - Removed uneeded typename identifiers

SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
-------
We weren't cleaning up actor channels when destroying actors as a result of a remove entity op, which resulted in us running out of channels and crashing.
The fix makes sure the channels are cleaned up when the entities are destroyed or go out of view, and also we don't crash if we run out of channels (though you won't be able to replicate that many actors).
https://improbableio.atlassian.net/browse/UNR-659
@davedolben @m-samiec
=> UNR-659 Clean up actor channels

SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp
If a subobject is deleted locally, it can still receive updates from Spatial. In that case we shouldn't crash.
=> Fix crash for when subobject doesn't exist

SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp
Was causing a crash in Scavengers. We should only be merging changelists if something has changed.
=> Only call MergeChangeList if something has changed

SpatialGDK/Source/Private/EngineClasses/SpatialNetBitReader.cpp, SpatialGDK/Source/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/Private/Utils/SchemaUtils.cpp, SpatialGDK/Source/Public/EngineClasses/SpatialNetBitReader.h, SpatialGDK/Source/Public/Utils/ComponentReader.h, SpatialGDK/Source/Public/Utils/SchemaUtils.h
-------
Stably-named actor resolution can fail if the referred actor is in a streaming level that hasn't been loaded yet. Change checkfs that would crash under these circumstances to early outs with error logs.
Validated against local streaming level test case and Scavengers, where the problem was initially discovered.
n/a
=> UNR-658: Switch checkfs to early-outs on failed statically-named actor resolution

SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/Public/Interop/SpatialStaticComponentView.h
-------
Singletons were not resolved on non-authoritative servers because the call to `ResolveEntityActor` was removed from the bit in `ReceiveActor` where the actor already exists.
=> Resolve singletons on non-authoritative servers

SpatialGDK/Source/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/Private/Interop/SpatialSender.cpp, SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
-------
Don't send component updates unless you have authority and warn if we're trying to do so. This was causing the bug in the ThirdPersonShooter where the shot effect RPCs would be looped on the non-authoritative server, and broadcasted to the clients whenever the shooter crossed the server boundary.
Also, add the EntityACL component write ACL to the EntityACL component (EntityACLception).
=> Don't send component updates unless you have authority

SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp, SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Call `CallPreReplication` before saving out actor's in the snapshot.
Also driveby in SpatialReceiver.
Tested a startup actor with simulate physics.
@davedolben @Vatyx
=> UNR-621: Call `CallPreReplication` before saving out actor's in the snapshot

Setup.bat
-------
Setup.bat will clean the schema folder completely. This is to make sure our users who were working with the GDK before the recent schema changes don't have to manually clean their schema folder.
=> Make Setup.bat clean the schema folder

SpatialGDK/Source/Private/Utils/ComponentReader.cpp
REPNOTIFY_Always should only be called if we aren't applying the initial component data associated with an Actor. This was causing issues with OnRep_ReplicatedMovement where startup actors were having their location set to the origin.
=> Only trigger REPNOTIFY_Always if not applying initial data

SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp, SpatialGDK/Source/Public/Utils/SchemaDatabase.h, SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.cpp, SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.h, SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
-------
`ResolveClass` doesn't do anything if the class isn't loaded, so the client ends up without the classes it needs.
Run a local deployment with external workers, see no crash.
=> Revert the revert of #493 and fix the crash due to not loading classes

SpatialGDK/Source/Private/Interop/SpatialDispatcher.cpp, SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/Public/Interop/SpatialReceiver.h
-------
If objects get resolved in a critical section, they get queued up and were meant to be resolved after we leave the critical section. Instead, they were resolved after we process all the ops, which causes problems if an entity gets added and removed in the same frame.
=> Fix order when ProcessQueuedResolvedObjects is called

SpatialGDK/Source/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/Public/Schema/UnrealMetadata.h, SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
Scavengers have a static subobjects that can get deleted in the construct script dependent on other variables. This prevents them from being written to the startup actors component data.
=> Allow static subobjects to be deleted in constructors

SpatialGDK/Source/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/Private/Interop/SpatialTypebindingManager.cpp
Ensure the target object is resolved before sending RPCs on it.
@improbable-valentyn @joshuahuburn @Vatyx
=> Check against unresolved objects before sending rpcs

SpatialGDK/Source/Private/Utils/ComponentFactory.cpp, SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/TypeStructure.cpp
Delegates can be marked as replicated, but Unreal doesn't support any type of network replication. Only added it to the component factory, as the component reader will never have it written to in fabric to read from.
@joshuahuburn @Vatyx
=> Prevent delegates from causing runtime check failures

SpatialGDK/Source/Private/Interop/GlobalStateManager.cpp
Inherited singletons was causing multiple actor channels to be created for the same actor. It now searches existing singleton actor/channel pairs when setting up singletons. This will all be refactored in the inherited spatialtype feature.
=> Search for actor in existing singletons

SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/TypeStructure.cpp
We were using the property's class rather than the object's class to create the type structure for a subobject. It should be the subobject's class since a subobject can be a derived class of the property's class.
=> Use correct class to create type structure

SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
-------
If the user has not set a snapshot option in their travel URL then we will now automatically get one based on the map name.
Additionally moved code around to prevent failing server travel in the case that the `SpatialNetDriver` is not ready for server travel yet (`OnMapLoadedAndConnected` not called yet). This fixes and issue with calling `ServerTravel` early like in a `GameInstance`.
Tested by not setting a snapshot option in URL and also calling ServerTravel very early which then used native server travel rather than crashing.
What automated tests are included in this …
=> ServerTravel - Auto snapshot selection

SpatialGDK/Source/Private/EngineClasses/SpatialNetDriver.cpp
-------
When checking the correct map is loaded on connection to a server we need to make sure the map names aren't affected by PIE prefixes. 
The PIE prefix is different for every client / server in a PIE instance and so was causing uneeded client travel and warnings to be printed.
Tested starting up in PIE, no client travel or warnings happened unnecessarily.
@jacqueslebrun @Vatyx
=> Removed PIE prefixes from map checking when connecting to a server.

SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SchemaGenerator.cpp, SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp, SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/Utils/DataTypeUtilities.h
-------
Recently we started checking for non-alphanumeric characters in RPCs and variable names and then removing them from the translated schema name. This allows for potential name collisions within schema.
This PR checks that there will be no naming collisions after removing non-alphanumeric characters before generating schema.
=> Check for duplicate RPCs and field names in schema

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
-------
We pass the game name into `BuildWorker.bat` anyway, so there's no reason users should also update their worker config (linux managed worker arguments).
`StarterProject` PR: https://github.com/spatialos/UnrealGDKStarterProject/pull/39
`TestSuite` PR: https://github.com/spatialos/UnrealGDKTestSuite/pull/131
`ThirdPersonShooter` PR: https://github.com/spatialos/UnrealGDKThirdPersonShooter/pull/44
=> No need to pass game name in worker config

SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
-------
Print out more information when generated schema names collide.
Tested manually with colliding names (by adding underscores) for each of: RPCs, handover properties, replicated properties, and class names.
n/a
@girayimprobable @Vatyx
=> Improve error messages around name collision for schema types

Setup.bat
-------
It's easy to forget to run `Setup.bat` when you pull the GDK.
On the first run, `Setup.bat` will generate git hooks that will then run `Setup.bat` every time you merge or checkout (including fast-forward, which is usually what happens when you `git pull`).
To make sure that doesn't take too long, it will skip downloading the CoreSDK packages if the latest version has already been installed. For that to work, `Setup.bat` will:
- Before downloading the CoreSDK packages, check against `core-sdk.version` inside the temporary `SpatialGDK\Build\core_sdk` directory.
- After …
=> Git hooks for running Setup.bat, don't re-download same version CoreSDK

SpatialGDKEditorToolbar/Source/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDKEditorToolbar/Source/Private/SpatialGDKEditorGenerateSnapshot.cpp
-------
When generating schema, generally two things can go wrong: deleting the generated schema folder, and rewriting the schema database.
When generating snapshot, we were already reporting the errors, but we leaked the SnapshotOutputStream if any errors happened. Also, we only started checking for errors after trying to write the Spawned entity instead of checking right after creating the SnapshotOutputStream, which is when the write access error is reported.
[JIRA ticket](https://improbableio.atlassian.net/browse/UNR-670)
Set files read-only. Run the schema generator. Run …
=> [UNR-670] Report write access failures when generating snapshot or schema

SpatialGDK/Source/Private/Interop/SpatialOutputDevice.cpp, SpatialGDK/Source/Public/Interop/SpatialOutputDevice.h
Adding this command will stop logging to Spatial. Important to do if there are a lot of logs since it can affect performance.
=> NoLogToSpatial Param to stop logging to Spatial

Setup.bat
This is causing more trouble than benefit. We should copy over dependencies each time.
=> Remove cached worker SDK

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
-------
Change USpatialReceiver::HandleActorAuthority to only assign ROLE_AutonomousProxy to APawn or APlayerController. This is a quick fix for UNR-824, which caused owned actors to be set as AutonomousProxy and broke movement replication. A larger re-work of USpatialReceiver::HandleActorAuthority is probably still required.
Tested manually against UnrealGDKStarterProject and UnrealGDKTestSuite locally.
n/a
@girayimprobable @joshuahuburn
=> UNR-824: Quick fix for aggressive ROLE_AutonomousProxy assignment

RequireSetup, SpatialGDK/Extras/schema/spawndata.schema, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/Schema/SpawnData.h
-------
TL;DR: Location was broken for actors with an owner, rotation was broken if the template actor has rotation.
For actors with an owner, we assign the spatial position to the position of the owner. However, when spawning the actor, we then use that spatial position as the spawn location, so it used the wrong location for actors with an owner. Now, the spawn location is written into SpawnData, and spatial position will not be actually read from by workers (only by Spatial itself to decide authority).
This has a caveat that was already there for rotation, scale, and …
=> Fix spawn location and rotation

RequireSetup, Setup.bat
-------
When `Setup.bat` runs inside `eval` inside `bash`, it doesn't have permissions to write a new git hook. Replacing `eval` with `exec` fixes the problem.
- Reset to a previous git commit
- Do a `git pull`
- Setup.bat does not generate error messages
The above flow works for both `bash` and `cmd`
@joshuahuburn @danielimprobable
=> Fix 'Access is denied' when Setup.bat is run from git hook

SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
-------
After the changes to the spawn flow (https://github.com/spatialos/UnrealGDK/pull/391) WorkerAttribute is used instead of WorkerId to represent the owning client. Some variables weren't updated to reflect this.
=> Fix variable names missed when changing WorkerId -> WorkerAttribute

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Delay SpatialTypebindingManager init until after map is loaded. This prevents ALevelScriptActors from having an incorrect outer if loaded before the normal level package flow loads them. This can potentially be moved back to InitBase once we have lazy FClassInfo loading - https://improbableio.atlassian.net/projects/UNR/issues/UNR-833
Tested editor work flow, and connecting with a standalone game application.
@improbable-valentyn @joshuahuburn
=> Delay SpatialTypebindingManager init until after map is loaded

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
-------
UNR 762
Adding a special case when updating Spatial Position. If the entity is an AController, we instead use it's Pawn's position. This is to prevent players checking out areas of the world they do not require due to their controller being spatially separate from their pawn.
This is an alternative fix to the previous engine change, so that we can revert the engine change.
For reference: 
https://github.com/improbableio/UnrealEngine/pull/61
https://github.com/improbableio/UnrealEngine/pull/64
Connect a player to a deployment, without moving, check in the inspector that …
=> If updating the spatial position of a controller, use its Pawn's position

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
-------
Reliable Multicast RPCs are not currently supported by Unreal GDK, but we don't explicitly disable them, only print a warning.
Code for detecting out-of-order RPCs assumed that Multicast RPCs can't be reliable so it broke when encountering those.
@m-samiec @BenNaccarato
=> Fix errors on reliable Multicast RPCs

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
Fixed misspelling of "EntityQuery" in SpatialWorkerConnection, was "EntiyQuery"
Rebuilt my project after the change to make sure nothing was broken by fixing this spelling.
None
@girayimprobable
=> fixed misspelling of EntityQuery in SpatialWorkerConnection

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
-------
Various reports of missing singletons came through which are a result of actor replication throttling. When these actors were not replicated for some time and not marked as relevant, their actor channels would be deleted as an Unreal optimisation. Deleting SpatialActorChannel also sends a delete entity request, this could happen to any entity under high load. 
Built, ran, no bugs.
@m-samiec
=> Fixed entities being deleted when not relevant for any amount of time.

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
When attempting to port a different project, the game crashed on begin play, due to a stack overflow from a pawn calling GetActorSpatialPosition on its owner (the Controller), which in turn called it back on the pawn. The logic has been updated to explicitly get the position from the pawn, rather than calling the method on the pawn.
In editor mode for the ported game. The crash no longer happens
=> Fix stack overflow from pawn's owner being its controller

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
If spatial networking is enabled, override the GameNetDriver with the SpatialNetDriver to save doing this in config ini files
Tested with StarterProject in editor and externally, NetDriver was overridden successfully when spatial networking was enabled
=> [UNR-878] - Override GameNetDriver with SpatialNetDriver

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
(See https://improbableio.atlassian.net/browse/UNR-881 for context)
For `ResetOutgoingUpdate`. make a list of invalid objects, to remove after iterating on the set.
For `CreateRPCCommandRequest` and `CreateMulticastRequest`, `UnresolvedObjects.Remove(Object);` is useless here because the set is only used to get the first element then return.
For `QueueOutgoingUpdate`, it is not expected to ever have invalid subobjects, so the remove has been removed, but if it is ever found to be reached, we should deal with it properly.
Running for a while in UnrealTournament, attempting to trigger the use case that caused the issue. It is no longer reached, and the QueueOutgoingUpdate log was not reached.
@improbable-valentyn @joshuahuburn
=> Bug fix - removing from a set whilst iterating over it.

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Soft references to blueprints can cause referenced actors to not be loaded, leading to no schema generated for them which in turn means we can't replicate them. This will potentially help with finding what classes aren't being replicated.
=> Added error when replicating with no schema.

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
The ragdolls (actors) were not being cleaned up because their role was not set to ROLE_AUTHORITY (which is done when the actor channel is closed/cleaned up). Calling ConditionalCleanUp on the channel when the entity is removed fixes this.
Works on the UnrealGDKShooterGame. (visually is cleaned up)
=> Bug fix - clean up the entity and actor channel when torn off.

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
-------
Bits, bytes.
If we wanted to be more correct, we could send the exact number of bits that was used to serialize the UniqueId, but that would mean adding bandwidth that isn't necessarily useful.
Bytes * 8 >= (Bits actually used)
Ran ShooterGame against this, and the `FBitReader::SetOverflowed` errors go away.
@m-samiec
=> Fix FBitReader::SetOverflowed being called due to using the number of bytes instead of bits

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
-------
Makes it easier to tell if something is wrong or if the error is benign.
In the case of ShooterGame, this gets triggered with the level scripts actors' DefaultSceneRoot objects, which are present for schema generation, but removed at runtime.
Also, make this a warning instead of error (this will trigger consistently for LevelScriptActor's DefaultSceneRoot).
@m-samiec
=> Add more info to the 'invalid sub-object' error log

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitWriter.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp
-------
https://improbableio.atlassian.net/browse/UNR-938
When constructing component updates we would check for the object not being null but not whether the object is invalid (IsPendingKill()).
Then when adding UnresolvedObjects to our unresolved maps, we WOULD check for `IsPendingKill()` and never add that UnresolvedObject to our maps.
`LogSpatialSender: Error: Invalid UnresolvedObject passed in to USpatialSender::QueueOutgoingUpdate`
Then when running `USpatialSender::ResetOutgoingUpdate` we would look for the UnresolvedObject inside of the component update using …
=> UNR-938 Critical with unresolved objects

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
-------
It's possible for actor channels to be closed when receiving reserve ID or create entity responses. This PR checks actor channel validity before using them to prevent crashing.
Also converted PendingActorRequests to use TWeakPtrs since the channels can be closed and GC'd.
=> Added checks for actor channel validity when creating entities

SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
In SpatialSender.h changed type of the key of a TMap from Worker_EntityId to int64, as the former was causing clang to throw errors for linux builds.
I tried to build a server worker after the changes and the build succeeded (instead of failing as it did before). I also launched a deployment and it runs successfully.
none
@BenNaccarato @improbable-valentyn
=> changed type of key in TMap so linux build will not give errors

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
StartWorker.sh now redirects its stdout and stderr to the worker log file. This in turn also makes it so that the worker shell script also redirects its output to the log file.
This requires another change in the project repos in their worker files.
https://github.com/spatialos/UnrealGDKTestSuite/pull/135
https://github.com/spatialos/UnrealGDKStarterProject/pull/46
https://github.com/spatialos/UnrealGDKThirdPersonShooter/pull/55
=> Redirect logging in the cloud to output to the correct file

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
USpatialGameInstance::StartPlayInEditorGameInstance() was not calling OnStart() on every path it can takes, that is, when not calling Super::StartPlayInEditorGameInstance() that call it for us.
Bugfix: StartPlayInEditorGameInstance() now correctly call OnStart() on PIE_Client
void UCorvusGameInstance::OnStart() derived class was not called on PIE_Client if running on Spatial Networking, while it was called when playing in raw unreal engine networking
Now our logs (and features) are showing that it work.
=> Fix USpatialGameInstance::StartPlayInEditorGameInstance() to properly call OnStart() if on Client

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h
-------
Imitate the native Unreal login logic from `PendingNetGame.cpp` and pass the player's nickname and login options with the URL.
Feature: Pass player name and login options in the login URL.
(Documentation changes are exempt)
In native Unreal in ShooterGame, the players are given names based on the name of their machine, and that shows on the leaderboard. With this PR, that functionality is also present in Spatial.
@m-samiec @BenNaccarato
=> [UNR-911] Pass player name and login options in the login URL

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Fixed an issue in https://github.com/spatialos/UnrealGDK/pull/623 which caused character controllers to be treated as startup actors when it comes to removing the actor.
Bugfix: Fixed an issue which caused a character controller to not be destroyed when leaving the view of an observing client.
Tested locally in Starter project.
QA: Adjust client checkout radius to something small, connect two clients, move one of them outside the view of the other (use inspector to make sure it's out), ensure that the pawn is no longer visible. Move the client back into view, ensure that the pawn is visible again. 
Release note
@Vatyx
=> UNR-982: Actor not destroyed when entity removed

RequireSetup, SpatialGDK/Extras/schema/heartbeat.schema, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/Schema/Heartbeat.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
-------
Allow the server to tell when a client disconnects from the deployment.
This is implemented using heartbeats using events. Client is authoritative over the heartbeat component and sends heartbeat events at regular intervals. The server will reset the timeout each time it receives a heartbeat event.
Feature: Server will identify clients that have been disconnected from Spatial and trigger the cleanup on their NetConnection.
Tested with ThirdPersonShooter and ShooterGame by running a PIE server + client and connecting an external client, then closing the external client …
=> [UNR-874] Heartbeats, player disconnection

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
-------
This fixes my error in https://github.com/spatialos/UnrealGDK/pull/656.
The real reason for the crash observed in multiserver PIE shutdown is still unidentified, tracked in UNR-989.
@Vatyx
=> Fix the fix for the multiserver PIE shutdown

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
There was a crash bug due to having a null netdriver when attempting to quit from a built out client. Adding a null check before the call stops this crash arising.
Tested on shooter game, in editor, and in playtest (13/02/19 - will wait until QA confirm it doesn't occur when using this fix before merging it.)
=> Wrap with null check to avoid crash bug on quit for deployments

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Ensure DeleteDynamicEntities is queried correctly.
Also ensure BeginPlay is only called on received actors if the world has dispatched the call.
Bugfix: Fix DeleteDynamicEntities not getting used correctly in shutdown
Bugfix: Only call BeginPlay() on Actors if the World has begun play
Ran locally with multiple clients.
@improbable-valentyn @BenNaccarato
=> Fix delete dynamic entities check

RequireSetup, SpatialGDK/Extras/schema/global_state_manager.schema, SpatialGDK/Extras/schema/heartbeat.schema, SpatialGDK/Extras/schema/singleton.schema, SpatialGDK/Extras/schema/spawndata.schema, SpatialGDK/Extras/schema/spawner.schema, SpatialGDK/Extras/schema/unreal_metadata.schema, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
In order to avoid pain in the future, make handcrafted component ids decrease from 9999, avoiding any future clash with dynamic components
Feature: Dynamic Component Ids now start from 10000, Gdk Components will now use 9999 - 0 to avoid future clashes
=> UNR-996 Handcrafted Component ids start at 9999 and decrease. dynamic start at 10000

SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
If the SchemaDatabase doesn't exist on generation of schema, ClassPathToSchema is emptied to reset what classes are supported.
Bugfix - Deleting the schema database reset the starting component ID
@m-samiec @BenNaccarato
=> If schema database is manually deleted, reset internal state for schema generator

SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.h, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp
-------
Fail schema generation if there are replicated/handover properties, RPCs, or subobjects that contain only non-alphanumeric characters, or leading digits, since they will produce invalid schema names.
Also, report all the errors that are found across all supported classes rather than early outing on the first error.
Bugfix: Report invalid name errors during schema generation instead of when launching a deployment.
Create replicated/handover properties, RPCs, or subobjects with invalid names:
- names only consisting of non-alphanumeric characters
- leading digits after …
=> [UNR-927] Better error reporting during schema generation

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
The bug was that there was some native Unreal code that would check an OpenPacketId, and use this to mark the repflag as being the initial update. However, since OpenPacketId is not used in spatial, this is simply always true, so initial only updates are sent every time. This PR overrides the native check with spatial's CreatingNewEntity.
To note - there is some legacy native code that could be removed (regarding a FOutBunch). This could be relevant to look into with this bug fix, but maybe it's better to ignore for now.
Bugfix - COND_InitialOnly are only replicated once at the start.
Fixes the bug reported in UT
=> Bug fix - COND_InitialOnly not doing anything

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
-------
UNR-965 standalone clients not connecting to spatial automatically is fixed.
Bugfix: Fixed a bug where standalone clients run locally would not connect to spatial.
Tested connecting locally and in the cloud. Both worked.
=> Fixed standalone local client connection.

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
-------
Fix default port being overridden by map URL when using receptionist.
Bugfix: Fix default port being overridden by map URL when using receptionist.
Test connecting to any receptionist and works without having to change default port.
No docs update required.
@girayimprobable @m-samiec
=> Fix default port override 

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
This is a duplicate of #694 for CI purposes
=> Duplicate of #694 - Remove legacy flag in generated default config to fix warning when launching SpatialOS

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
-------
Fix Spatial connection destroy on PIE and allow map name as first argument.
Bugfix: Fix spatial connection being destroyed and recreated when connecting with PIE.
Tested standalone and PIE connections.
STRONGLY SUGGESTED: Launch PIE and standalone clients to different IPs.
=> UNR-1010 Fix Spatial connection destroy on PIE and allow map name as first argument.

SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
-------
Memory allocation issues with the `Ipv4RegexPattern` was causing segfaults. Changing it's initialisation resolves this issue.
Bugfix: Fixed regex segfault.
Tested locally and on the cloud
STRONGLY SUGGESTED: Client does not segfault when booting.
@girayimprobable @m-samiec
=> Fix boot segfault with packaged clients.

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
We were incorrectly using the FClassInfo to find out what component to use when it should be the client endpoint component. This was breaking Linux builds.
This should not be included in release notes. This was an oversight.
@mattyoung-improbable @m-samiec
=> Fixed using incorrect component ID and Linux builds.

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Remove inline replicate subobjects logic and use existing Actor::ReplicateSubobjects. 
Bugfix: Actor::ReplicateSubobjects is now called in a replication flow
Tested this in test suite, and with additional GAS tests
@BenNaccarato  @Vatyx
=> Replace inline logic with call to replicate subobjects

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
We should still generate schema if we have blueprints that haven't compiled. We report what blueprints haven't compiled after generating schema.
Bugfix: Still generate schema even if some blueprints have failed to compile.
Made a blueprint that didn't compile and then generated schema.
@m-samiec @BenNaccarato
=> Still generate schema even if some blueprints haven't compiled

RequireSetup, SpatialGDK/Extras/schema/core_types.schema, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h, SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
-------
Client is supposed to load streaming levels when the server tells it to. Instead, we could load them when resolving an UnrealObjectRef to an object inside a streaming level. This led to strange behavior and crashes when restarting the game.
Now, the server will include a flag inside UnrealObjectRef to indicate whether client should load any given objects. Since this only matters for objects loaded by path, I put the path and this flag together in an optional field inside UnrealObjectRef to reduce the bandwidth overhead.
Bugfix: Fixed an issue where a reference to an …
=> Prevent loading levels when resolving UnrealObjectRefs

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
-------
If you mark an actor as `NotSpatial`, we should not try to replicate it.
Right now, attempting to replicate an unsupported actor results in a failed `checkf` in `SpatialClassInfoManager`.
Bugfix: Fix crash when trying to replicate an actor marked "NotSpatial".
Mark something as `NotSpatial`. Run the game. Don't crash.
=> Don't try to replicate actors not supported by Spatial

RequireSetup, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Common/Common.cs
We are renaming "fake client" to "simulated player" to align terminology across (upcoming) projects.
The build script has the option to build headless Linux (fake) clients. This PR renames the option to build these headless Linux clients from FakeClient to SimulatedPlayer.
For backwards compatibility the build script will still support FakeClient as a GameName (which results in `UnrealFakeClient@Linux.zip` as the created assembly), but will show a warning to use SimulatedPlayer instead. Using SimulatedPlayer as the GameName will result in the same assembly being created under a different name: `UnrealSimulatedPlayer@Linux.zip`. 
No release notes: the FakeClient/SimulatedPlayer option in the build script is currently for internal use only.
Tested this change by building both a FakeClient …
=> Update build script to use SimulatedPlayer instead of FakeClient

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
-------
With `Use Single Process` unchecked, the server would ignore `Delete dynamic entities` setting because the `World` pointer is set to null before the actor channels are cleaned up. Instead, we can check `GIsRequestingExit` which is true when the server is shutting down.
This has a side effect of triggering with external servers that are built with editor, e.g. in the standard local deployment flow, which may or may not be a useful feature. If necessary, we can modify this to only trigger on non-PIE servers if they're terminated from `ReceiveShutdownMultiProcessRequest`. …
=> Make 'Delete dynamic actors' work with servers as a separate process

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h, ci/unreal-engine.version
-------
In order to open up for future support for offloading, this PR associates a game instance with a spatial worker type. 
Associated engine branch: https://github.com/improbableio/UnrealEngine/pull/99
Feature: It is now possible to access the worker type through the game instance.
Validated the normal connection flow.
Do a local and a cloud deployment and validate that the workers spun up have the correct worker types.
None required, non breaking change.
=> WorkerType stored in GameInstance

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
JIRA: https://improbableio.atlassian.net/browse/UNR-1083
With https://github.com/spatialos/UnrealGDK/pull/682 a non-authoritative server also tries to handle unreliable RPCs because it receives events. This causes an assertion to fail in the character movement controller which expects to have the authority network role. I assume many other RPCs will also fail.
Also brings latest master into hydra.
Bugfix: Handle unreliable RPC only on worker with authority
launched starter project with a two-server config
raised the added log to a warning to see how often it fires (too often to be anything other than verbose)
release note
@danielimprobable
=> [UNR-1083] Handle unreliable RPCs only if worker has authority

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
-------
The authority check in `HandleUnreliableRPC` is only needed for Client and Server RPCs. For NetMulticast, any Unreal client or server should execute the RPC upon receiving the event (except the sender itself, who will skip it at the beginning of `OnComponentUpdate` as they have authority over the component).
Call multicast RPCs on other player's characters and actors in the world. See them execute on the client.
@mattyoung-improbable @Vatyx
=> Fix multicast RPCs not being called

SpatialGDK/Extras/schema/unreal_metadata.schema, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
Actors that are placed into a level but aren't saved to disk, will not have the flag `RF_WasLoaded` set. This means we need to check against both the RF_WasLoaded flag (in the case of bNetLoadOnClient = false) and against bNetStartup to see if we need to put the path into the UnrealMetadata in the cases where the map isn't saved.
This will cause issues in the edge case of Actors with bNetLoadOnClient = false, and the map wasn't saved. No path will be in the UnrealMetadata so the server will not know to link up the entity when it connects. We can solve this edge case in the future.
Related Engine PR: https://github.com/improbableio/UnrealEngine/pull/108
=> Check against bNetStartup to see if path should be in UnrealMetadata

SpatialGDK/Source/SpatialGDK/Public/Utils/RepLayoutUtils.h
-------
Having multiple EventGraphs can cause RPCs to be iterated in a different order by different Unreal instances. Sorting the RPCs alphabetically should produce a consistent order (since no two RPCs can have the same name).
Bugfix: Fixed an issue where having multiple EventGraphs would sometimes result in wrong RPCs being called.
Have multiple EventGraphs with RPCs. Call RPCs and check that the correct RPC is being called on the receiving side.
Also, print out the list of RPCs generated in `SpatialClassInfoManager` by different Unreal instances (e.g. by running as separate …
=> Sort RPCs by name since multiple EventGraphs can produce different order

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Use the EntityToChannel map in the netdriver to stop crashing
Bugfix - fix crashing on SpatialDispatcher::ProcessOps
=> Use the EntityToChannel map the netdriver already has in the dispatcher

SpatialGDK/Extras/schema/spawner.schema, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h
Temporary local state work around to stop multiple players being spawned.
Also added the ability to send command failures to the USpatialWorkerConnection.
Removed unused and unnecessary state from the player spawner response.
Bugfix: Fixed an issue where clients could crash after being assigned multiple players.
Tested locally by sending multiple spawn requests at a time, then sending a new one on each response.
Reproduced the multiple client crash by sending concurrent requests without this fix.
release note
@improbable-valentyn @Vatyx
=> Added a local state record for which players have been spawned

SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
Switching the default connection protocol to TCP. Will make changes to the worker configs for each project.
Feature: The default connection protocol is now TCP.
=> Switch default to network protocol to TCP

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialOutputDevice.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialOutputDevice.h
-------
Use `GPlayInEditorID` to filter logs that are sent to Spatial when running in PIE.
Bugfix: Fix duplicated log messages in Spatial when running in PIE.
Log a unique warning on client and server (e.g. in PlayerController's BeginPlay, print its memory address), run in PIE with 2 clients and 2 servers.
Observe the logs only reported in Spatial once for each worker.
Release note
=> [UNR-442] Don't send log messages to Spatial if PIE index doesn't match

SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
-------
When deserializing strings containing Chinese characters in component updates, extra unreadable characters were present at the end of the final string. This was due to runtime not providing null-terminated strings in the byte stream, when calling `Schema_IndexBytes` we would read past the end of the desired string and into garbage until a null character was reached. The bytes (including the garbage) would then be converted to `TCHAR*`, and the final `FString` would be created using `Schema_IndexBytesLength` as the length which was also incorrect.
New implementation uses …
=> [UNR-1239] - Fix String Deserialization from Schema

SpatialGDK/Documentation/content/get-started/dependencies.md
Microsoft launched Visual Studio 2019 on April 2 and in the process they broke the Visual Studio 2017 link we provide in [/get-started/dependencies](https://docs.improbable.io/unreal/alpha/content/get-started/dependencies#step-3-software).
I've replaced this link with https://visualstudio.microsoft.com/vs/older-downloads/
Rendered and linted in `improbadoc`
=> Fix Visual Studio 2017 download link

SpatialGDK/Documentation/content/get-started/dependencies.md
The DirectX runtime is a dependency for running built out clients that are downloaded when running a cloud deployment. I've added it to the dependencies list.
Rendered and linted in `improbadoc`
=> Add Direct X to dependencies

SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
Bug fix for https://improbableio.atlassian.net/browse/UNR-1181
Bug reported by (and fixed working from the suggestion of) GitHub user Antialiased
The issue was due to when resolving an actor, when attempting to create the offset map, we previously used the `GetDefaultSubobjectByName` method. The method looks as follows:
```UObject* UObject::GetDefaultSubobjectByName(FName ToFind)
{
UObject* Object = nullptr;
// If it is safe use the faster StaticFindObjectFast rather than searching all the subobjects
if (!GIsSavingPackage && !IsGarbageCollecting())
{
Object = StaticFindObjectFast(UObject::StaticClass(), this, ToFind);
if (Object && !Object->IsDefaultSubobject())
{
Object = nullptr;
}
}
else
{
TArray<UObject*> SubObjects;
GetDefaultSubobjects(SubObjects);
for (UObject* SubObject : …
```
=> Bugfix - get subobject if not default

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md, SpatialGDK/Documentation/content/get-started/gdk-template.md
* Correctly use `<YourProject>` in docs.
* Correctly stylise `UE4Editor.exe`
* Fix the rendering of numbered steps in `/get-started/build-unreal-fork#step-4-build-unreal-engine`
Linted and rendered in `improbadoc`
=> Fix numbering and styling in setup docs.

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
-------
UNR-1231 "SchemaDatabase not found!"
Seems that `TSoftObjectPtr.LoadSynchronous();` would not guarantee we load the asset.
Switched to `FSoftObjectPath.TryLoad();` and now the SchemaDatabase is no longer missing during initialisation.
Bugfix: Fixed potential loading issue when attempting to load the SchemaDatabase asset. 
Tested with high repro case Editor build where SchemaDatabase was consistently missing at initialisation.
After switching to TryLoad I no longer encountered the issue after many tests.
QA: Attempt to load a server (outside of the editor) using a large …
=> Fix missing SchemaDatabase

SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialWorkerFlags.h
Fix header file
Bugfix: Add pragma once directive to header file.
Can `#include "Interop/SpatialWorkerFlags.h"` in two different places and compile
release note
@Vatyx
=> Add pragma once directive to header

SpatialGDK/Documentation/content/get-started/dependencies.md
Following a comment from David A in Slack - removed the mention of "13.2" from the instruction to download SpatialOS (the link goes to the latest SpatialOS version, I believe).
=> Remove mention of 13.2

SpatialGDK/Documentation/content/cloud-dev-workflow.md, SpatialGDK/Documentation/content/local-dev-workflow.md, SpatialGDK/Documentation/toc.md
Adds two new workflow docs
* Local Dev workflow - google diagram [here](https://docs.google.com/drawings/d/1g7NNbHiTYKNAeu7X_BvwnpPgDBx5Op7MigwEpBP7T8s/edit) - paired on it with @m-samiec 
* Cloud Dev workflow - google diagram [here](https://docs.google.com/drawings/d/1JnpViwBGxIJa5S8bEN3nspaBKGNqmebZkLmgNdn2A_c/edit) - paired on it with @Vatyx 
The Google diagrams areembedded in improbadoc - this means they update live from the diagrams
Additionally renamed the Troubleshooting section of the docs to Workflow:
=> Docs - Adds Local and Cloud dev workflows docs, create Workflow section of TOC

SpatialGDK/Documentation/content/get-started/porting-unreal-project-to-gdk.md
Adds a callout suggesting ShooterGame as a reference project to consult while porting.
(the green box below)
* Added the ported ShooterGame as a reference project in the Porting Guide.
Tested with Improbadoc
=> Docs - Add ShooterGame as a Reference in the Porting Guide

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
-------
Fix a crash caused by loading SchemaDatabase when async loading is suspended, for example when resuming the rendering thread which flushes the tasks on the GameThread, triggering `OnConnectedToSpatial` which would eventually try to load the SchemaDatabase.
Release note.
@m-samiec @oblm
=> Fix crash when loading SchemaDatabase with async loading suspended

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
We were crashing on a client travel since we were calling the OnConnectedDelegate on an old SpatialNetDriver. We now directly call OnConnectedToSpatialOS on the current NetDriver directly rather than binding to a delegate.
@improbable-valentyn @aleximprobable
=> Call OnConnectedToSpatialOS directly rather than binding to a delegate

RequireSetup, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
If you use BuildWorker.bat to build an UnrealClient twice for a project, it'll fail. This removes the implicit iterate from a build script (it can still be passed as an optional parameter), and explicitly deletes the old exe if it still exists.
Ran client builds multiple times.
@joshuahuburn @Vatyx
=> Remove iterate from worker build

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
We were not wrapping the launch config directory in quotes, causing `spatial` to not correctly parse the path being passed in.
=> Wrap launch config path with quotes in order to properly launch

SpatialGDK/Documentation/content/get-started/gdk-template.md, SpatialGDK/Documentation/content/spatial-type.md
Minor update to reflect the UI: the "Spatial Type" checkbox is no longer under "Advanced".
(This is also mentioned in the Singleton Actors doc, but there are bigger changes in progress for that one, so I haven't touched it for now.)
=> Spatial Type doc: remove mention of Advanced section

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
-------
RPC order checking is false by default so that development and shipping builds are compatible, but if there's a gameplay issue that we suspect is caused by out-of-order RPCs, you can flip the setting on and test with development build.
TODO: Test development server with shipping client and vice …
=> Add reliable RPC order checking to settings

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.cpp, SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.h
Now that schema generation does a full scan, only run it once before generating snapshots.
Tested locally using sample project.
Run commandlet and verify it takes less time than before:
`%UNREAL_HOME%/Engine/Binaries/Win64/UE4Editor.exe %PATH_TO_UPROJECT% -run=GenerateSchemaAndSnapshots -MapPath=Path/To/MapOne\;Path/To/Other/Map`
=> [UNR-1350] Bugfix: GenerateSchemaAndSnapshots: Run full schema gen once, then generate snapshots

SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp
Skip over UInterfaceProperty when replicating since it's not replicated.
Bugfix: fix crashing when a replicated Actor has a replicated UInterfaceProperty
Tested it locally
=> Ignore UInterfaceProperty replication

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
During schema generation, avoid loading assets & selecting classes that are inside packages marked as 'Never Cook' in packaging settings.
- Fixed an issues where schema generation was not respecting "Directories to never cook"
Tested Full & in-memory schema generation in editor & tested via commandlet.
1. Add a new folder to a project
2. Add a replicated actor to the new folder
3. Add the new folder to Project Settings -> Project - Packaging -> Directories to never cook
4. Run schema generation (full or incremental)
5. Verify that no .schema file was generated for the new actor & that it has not been added to the schema database.
If …
=> [UNR-1371] Bugfix: Do not generate schema for assets in 'Directories to Never Cook'

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
-------
This adds the auto-populated list property to SpatialGDKSettings
The list property gets reconstructed from the list of server worker names from the Launch Config Description property
Internal changes
Test: an offloaded SearchablesWorker still works - can read from entities and write to appropriate ones.
Internal changes
=> Remove hardcoding of AIWorker

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
https://improbableio.atlassian.net/browse/UNR-1410
Schema generation crashes if schema database asset is readonly. This PR adds a check before doing any schema generation and fails early if the asset is not writable, printing an informative error message.
- Fixed an issue causing the editor to crash during schema generation if the database is readonly.
Tested in editor with database set to readonly via explorer.
=> [UNR 1415] Bugfix: Readonly Schema Database crashes editor during generation

SpatialGDK/Documentation/content/get-started/gdk-template.md
-------
[DOC-1086] - add "Server" to Linux server worker build
This fixes a defect where users are instructed to build a useless standalone Linux client.
With this fix this command works and I was able to cloud deploy. Without it I received a fatal error (cannot find UnrealWorker@Linux.zip)
This is documentation lads.
=> [DOC-1086] - add "Server" to Linux server worker build

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp
-------
Don't crash if a subobject class can't be resolved when creating ClassInfo. This could potentially happen if the actor's blueprint isn't fully loaded, though the crash has not been reproduced on our side.
@m-samiec
=> Fix crash when resolving subobject class in ClassInfoManager

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h
-------
Fixed a crash when retrying reliable RPCs with UObject arguments that got destroyed before the RPC was retried.
I set up a test in ThirdPersonShooter where I would spawn a box, shoot at it, and destroy the box.
In one case, I made 20% of commands timeout by doing a random early return in `SpatialReceiver::OnCommandRequest` that would not send a command response (effectively making Runtime think the command timed out). The commands were then retried and applied correctly.
In the other case, I made all `ServerDidHit` RPCs timeout by doing an early return for this …
=> [UNR-1010] Fix crash when retrying reliable RPCs with destroyed argument

ci/purge.ps1
-------
Clean up `UnrealHeaderTool` if it's still running after the testing is finished. Otherwise this leads to locked files on the BK agent, which causes all later builds to fail.
@oblm
=> Extend BuildKite cleanup

SpatialGDK/Documentation/content/glossary.md, SpatialGDK/Documentation/content/spatialos-concepts/authority-and-interest.md, SpatialGDK/Documentation/content/spatialos-concepts/introduction.md, SpatialGDK/Documentation/content/spatialos-concepts/schema-and-snapshots.md, SpatialGDK/Documentation/content/spatialos-concepts/what-is-spatialos.md, SpatialGDK/Documentation/content/spatialos-concepts/workers-and-load-balancing.md, SpatialGDK/Documentation/content/spatialos-concepts/world-entities-components.md, SpatialGDK/Documentation/content/technical-overview/how-the-gdk-fits-in.md, SpatialGDK/Documentation/toc.md
Added a brief intro page to the SpatialOS concepts section, plus a few other updates (e.g. changed "Concepts" to "SpatialOS concepts" at the start of each of the pages, to help with orientation).
@ElleEss
=> Add SpatialOS concepts intro page

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetricsDisplay.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetricsDisplay.h
Added option to auto spawn spatial metrics display
Added runtime option to auto spawn the ASpatialMetricsDisplay for remote debugging of server metrics - bEnableMetricsDisplay.
@joshuahuburn @cmsmithio
=> Add auto spawn option to spatial metrics display

CHANGELOG.md, SpatialGDK/SpatialGDK.uplugin
-------
[UNR-1327](https://improbableio.atlassian.net/browse/UNR-1327): a tiny change to remove `Unreal GDK Content` from Unreal Editor Content Browser, as Unreal GDK plugin does not contain any game content.
After launching the editor, navigate to the content browser and mark plugin content to be shown (under _View Options_ in the bottom right hand side). Then navigate to `Content` directory and display the source panel by clicking on the button left of `Filters` option. This will display all the game and plugin content. Notice that `SpatialGDK Content` is not listed there …
=> Hide Unreal GDK from content browser

RequireSetup, Setup.bat
-------
Fixed a few issues with setup automation and related build issues.
- Fixed `-depth` not working correctly in `Get-ChildItem` when looking for games `.uproject`. `-Include` was overwriting this flag.
- Fixed finding the UnrealEngine when GDK is installed as a project plugin but with no engine association (so game is nested in UnrealEngine folder). Was caused by no delayed expansion.
- Fixed using the wrong UnrealEngine folder in the `Build.cs` when engine association is set. Caused by a bad refactor.
Issue not present in last release, no note required.
Tested with GDK …
=> Bugfix: Fixed build issues related to new setup flow

SpatialGDK/Documentation/content/get-started/dependencies.md
Removed mention of Visual Studio 2015 from https://docs.improbable.io/unreal/alpha/content/get-started/dependencies.
=> docs/Remove Visual Studio 2015 link

Setup.bat, SpatialGDK/Build/Scripts/FindMSBuild.bat
-------
Setup.bat had some huge code that was used to find the engine which in turn was only used to find the MSBuild install. Made a custom script to find it for our supported version and this simplifies the code.
Not needed: Customers shouldn't notice a change.
Ran Setup.bat and worlds
How can this be verified by QA?: Run Setup.bat from the UnrealGDK and any project using it should work.
@mattyoung-improbable @m-samiec
=> Use custom FindMSBuild.bat which suits our needs

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialFastArrayNetSerialize.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitWriter.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetBitWriter.h, SpatialGDK/Source/SpatialGDK/Public/Utils/RepLayoutUtils.h
-------
If we failed to `NetSerialize` a struct in Spatial we would crash on a `checkf`, in native they simply print a warning. Matched this behaviour.
Bugfix: - Fixed a crash when failing to NetSerialize a struct in spatial. Now print a warning instead which matches native Unreal behavior.
Ran with bad serialization and doesn't crash.
How can this be verified by QA?: Game does not crash with NaN data in component updates.
@m-samiec @padhansell
=> Bug fix Handle bad NetSerialize

Setup.bat
-------
With `EnableDelayedExpansion`, you need to escape `!` with `^^!`. We only needed `EnableDelayedExpansion` for the complicated logic retrieving the engine association which is no longer needed, so it's easier to just remove it altogether.
=> Fix post-merge hook

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Each client now gets a unique IP address using a counter so that when a connection is removed from the MappedClientConnections map, only one entry gets removed. This requirement is in 4.22.2 inside UNetDriver::TickDispatch
=> Give each UNetConnection a unique IP address to not crash.

CHANGELOG.md, RequireSetup, SpatialGDK/Extras/schema/rpc_components.schema, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
-------
Client and Server unreliable RPCs that happen on the same frame don't need to be sent as separate component updates. Packing them as multiple events in a single component update can save bandwidth, though the events will now all be going through the player controller entity.
This functionality is currently optional and can be toggled with `Pack Unreliable RPCs` in the Spatial GDK Settings.
Release note.
=> Pack server and client unreliable RPCs in one update

ci/purge.ps1
I noticed in [this CI run](https://buildkite.com/improbable/unrealengine-premerge/builds/825#2b26d651-58d7-4f93-84b9-0b934baa093c/3385-3387) that the purge script was failing to run when it tried to execute because the `path` it tried to cd to was unset.  Since hooks are run from the repo root anyway, this doesn't need to cd anywhere, so I just removed that call.
Once this passes and is mergeable here, I'll make the same fix on the UnrealEngine repo.  It's just easier to prove that it works here with the shorter per-build execution time.
The post-command hook ran successfully on [this build](https://buildkite.com/improbable/unrealgdk-premerge/builds/2635#d663020e-ed10-41fa-9c90-e05ddbd6fd0e/556-557).
Internal CI detail, does not require docs.
=> Fix post-command purge script invocation

SpatialGDK/Documentation/content/tutorials/deployment-manager/tutorial-deploymentmgr-authentication.md
Updated the deployment manager tutorial docs to make it clear that the DAT Secret should be used and *not* the ID.
Unfortunately the screenshot still says `development_authentication_token_id` but I'm not in a position where I can make a new one.
=> Update docs to clarify DAT secret should be used instead of the ID

SpatialGDK/Documentation/toc.md
These three pages are actually reference materials which are better suited in the Reference section than workflows, which is more about "workflow for achieving something":
* Command line arguments
* Helper scripts
* Directory structure
Tested with Improbadoc:
@ElleEss for review
cc @Vatyx following discussion
=> Moves workflow reference docs to Reference section

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
The wiki link we point to hasn't been updated in ages and will not be helpful for users on versions beyond 4.20, so updating it to point to the equivalent docs.unrealengine.com page
=> Link to docs.unrealengine.com as opposed to wiki

SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/ActorGroupManager.h
Which workers to start is now determined by SpatialGDKSettings::DefaultWorkerType, which defaulted to None.
=> [Bugfix] Add defaults to ServerWorkerTypes & DefaultWorkerType

SpatialGDK/Source/SpatialGDK/Public/Utils/ActorGroupManager.h
When running the GDK as an Engine Plugin, all UPROPERTYs exposed to Blueprint / Editor must have a Category specified.
=> [bugfix] Add UPROPERTY Category to ActorGroupManager properties

SpatialGDK/Documentation/content/get-started/dependencies.md
-------
This PR removes all references to the Visual Studio component **Unreal Engine Installer**. Epic list this as a dependency for installing UE4 from source but it is actually superfluous (it’s used by Epic to manage engine and plugin versions, which are not used in the GDK).
I successfully local launched and cloud deployed the example project without the "Unreal Engine Installer" VS component installed.
This is documentation bro.
@m-samiec
=> UNR-1294: Removes unnecessary dependency: Unreal Engine Installer

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
We now clean up the worker entity on the NetDriver being destroyed. The connection basically always exists at this point so we will clean it up.
=> Clean up worker entity on destroy

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
-------
If the class is marked `NotSpatial`, it still ended up replicated if e.g. a multicast RPC was called. Now we explicitly check for that and early out if the calling object is `NotSpatial`.
Release note
@m-samiec
=> Early out when trying to call RPC on NotSpatial type

SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
-------
Turns out that the working directory is not required for Spot and Execprocess does not have this on 4.20.
@m-samiec
=> Remove working directory for Spot

SpatialGDK/Extras/templates/WorkerJsonTemplate.json, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp, SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp, SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesModule.h
When launching, verify worker.json files exist for all server worker types defined in launch config, copy over default if no file exists.
=> Feature: Create default spatialos.WorkerType.worker.json files.

SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
We skip over subobjects that aren't supported for schema
=> Skip over non-supported subobjects when generating schema for subobjects.

SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialInterestConstraints.h
In order to match the schema Interest component on the SpatialOS side, we're going to hide the frequency field until it's supported.
=> Hide frequency from being exposed in the editor

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
-------
Fixes broken link within the cloud launcher popup, which redirects the user to build their workers: https://docs.improbable.io/unreal/alpha/content/get-started/gdk-template#step-2-build-your-workers
@girayimprobable
=> [UNR-1688] - Update broken link for the building workers

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ActorGroupManager.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/Utils/ActorGroupManager.h
New Client<->Server RPC packing breaks RPCs that should be sent to a different worker from the one that has authority on the PlayerController when offloading is enabled. This fix checks that the Channel Owner and the Target Actor are on the same worker type before packing.
Also adds a new UActorGroup::IsSameWorkerType method for checking 2 actors are owned by the same worker type.
Testing Locally with Client + Server RPCs with Offloading on/off
1. Enable offloading and create a 2nd worker type and an actor group owned by that worker type.
2. Define a new actor class called 'Proxy' and set it to replicate. Add a client + server RPC to it.
3. Add the actor class to the actor group owned by the 2nd worker type.
4. In player controller …
=> Bugfix: [UNR-1693] Do not Pack RPCs that are destined for a different worker type

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
-------
In some cases RPCs might be sent to AActor that's been tornoff. This PR eliminates such cases.
Fix for an issue that didn't get to known issues yet.
This was experienced when a ragdoll was caught in an explosion.
No doc update.
@mattyoung-improbable @improbable-valentyn
=> UNR-1710 Fixed a crash that may happen if rpcs are sent to tornoff actor

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
-------
Preserve URL options when sending the URL to the server through a ClientTravel. They were being replaced.
Manually tested theoretically exhaustive list of possible ClientTravel scenarios to validate that URL options are propagated …
=> UNR-1677 : Preserve URL options on ClientTravel

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
-------
There might be cases when RPCs other than client and multicast are sent on entity creation. This PR fixes it.
Fix for issue that wasn't in known issues.
Tested that it works as expected.
No doc update,
=> UNR-1718 Only send client and multicast RPCs on entity creation

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Reverts spatialos/UnrealGDK#1153
**Reviewers:**
@mattyoung-improbable @m-samiec
=> Revert "UNR-1710 Fixed a crash that may happen if rpcs are sent to tornoff actor"

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md
As [raised](https://improbable.slack.com/archives/C0TBQAB5X/p1563194079148500) by @tenevdev, the [new link](https://docs.unrealengine.com/en-US/Platforms/Linux/GettingStarted/index.html) we were using for downloading Clang requires docs changes - it's no longer a zip & no longer requires setting the LINUX_MULTIARCH_ROOT env variable. These changes should be made as part of our next release (updating the link and changing the docs) so reverting back to the tried and tested Unreal wiki page download links.
=> Docs - revert clang install to wiki page

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h, SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h, ci/unreal-engine.version
GameplayTagContainer used InternalAck as a soft check if we were in a replay connection. We use InternalAck for it's actual purpose, so created a new function - NetConnection::IsReplayConnection().
Engine PR - https://github.com/improbableio/UnrealEngine/pull/214
@girayozil @improbable-valentyn
=> Add IsReplayConnection func

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
-------
Disable replication for tornoff Actor, to stop RPCs from being sent.
Bugfix for yet unknown issue.
Followed the repro steps here https://improbableio.atlassian.net/browse/UNR-1710
No doc update.
@girayozil @m-samiec
=> UNR-1710 Disabled replication for tornoff Actor

CHANGELOG.md, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
-------
The script generated for local launch did not have the path to game interpreted correctly, so the local launch flow for launching server outside of Editor did not work correctly. This PR fixes it by making sure that the script has the game path output to it.
Build out a server worker for local deployments (`Game\Plugins\UnrealGDK\SpatialGDK\Build\Scripts\BuildWorker.bat <YourGame>Editor Win64 Development <YourGame>.uproject`) and check that `StartEditor.bat` script in `spatial/build/assembly/worker/UnrealEditor@Windows.zip` contains the right path to your game. …
=> UNR-1747: fix build script for local launch

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
-------
Actor's replicator is also contained in `ReplicationMap`. We weren't explicitly checking for it, and that caused the unresolved objects to be added twice, which shouldn't happen.
On a side note, the only reason we had an unresolved object was because of a torn off actor which was referenced by the actor whose entity was being created.
@m-samiec
=> UNR-1757 Skip actor itself when iterating ReplicationMap when creating entity

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Dynamic subobjects now get removed correctly from the package map.
=> Bugfix/unr 1705 crash on dynamic component re-add

SpatialGDK/Documentation/content/actor-readiness.md, SpatialGDK/Documentation/toc.md
Added Actor readiness doc. 
Drive-by: removed "and load balancing" from the "Workers and load balancing" heading in the TOC.
Primary reviewers: @NotRobSheridan @Vatyx (Sahil - feel free to add more code samples if you have them)
FYI: @ernopp
=> DOC-1160 Add Actor readiness doc

SpatialGDK/Documentation/content/actor-readiness.md, SpatialGDK/Documentation/toc.md
Adding "Actor readiness" work to `docs-next` now that it's been merged into `docs-release`.
=> Add Actor readiness docs to docs-next

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
-------
Moved the block emptying LoadedAssets and running garbage collection after the logging of errored blueprints to prevent the pointers from being invalid when getting their path.
Fixed an issue with logging errored blueprints after garbage collection which caused an invalid pointer crash.
Running full schema generation from the Editor with blueprints that fail to compile.
=> UNR-1772 - Bugfix: Log errored blueprints before running GC

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp, SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
-------
We have a flag for disabling auto deployment launching but this would mean editor clients would always wait forever, this fixes that.
Already in changelog
How can this be verified by QA?: Enable Auto launch deployment in GDKEditorSettings and press Play, local deployment should start and you should connect. Disable the option and then click Play, no deployment should launch and you should fail to connect. 
@m-samiec 	@mattyoung-improbable
=> UNR-1773 - Bugfix: Don't always wait for deployment 

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
The link used is no longer valid
Link to [here](https://docs.improbable.io/unreal/alpha/content/cloud-deployment-workflow#upload-assembly) which is a clearer page for this
**No testing done**
=> Working link for docs assembly upload instruction in Deploy window

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
-------
This prevents an absolute path for the snapshot folder from being checked in. Users should only ever save to the `spatial/snapshots` folder and so now we always get the path dynamically rather than having it as a configuration setting.
Bugfix: Removed the ability to configure snapshot save folder. Snapshots should always be saved to `<ProjectRoot>/spatial/snapshots`. This prevents an issue with absolute paths being checked in which can break snapshot generation.
Generated snapshot worked fine
How can this be verified by QA?: Generate a snapshot and it runs …
=> UNR-1758 Removed SnapshotPath setting to prevent it being checked in

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Two fixes.
1. Startup actors are cleanup correctly when leaving view, so they don't error when getting readded.
2. Don't incorrectly process remove component ops when both add and remove entity ops are received in the same ops tick.
Ran on the offloaded ai project which was erroring regularly previously
@Vatyx @samiwh
=> Fixes for various netguid resolution issues

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
-------
Found a crash when adding more dynmaic components than our limit allows. Added an early out when replicating SubObjects so we don't attempt to replicate an invalid ObjectRef.
Tested during workflows testing. Added more components of the same type than allowed and it no longer crashes during replication.
How can this be verified by QA?: Dynamically attach an ActorComponent to an Actor with replication turned on during gameplay. Ensure that the component is dynamically attached to entity in the Inspector, and that the client creates the component locally.
@Vatyx …
=> UNR-1792 Prevent crash on dynamic components

SpatialGDK/Documentation/content/cloud-deployment-workflow.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md, SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-local.md, SpatialGDK/Documentation/content/local-deployment-workflow.md
Explains the local workflow in the getting started guides. Provides an in context workflow diagram. Remove captions which duplicate a lot of text and don't add much.
=> Docs - Explain local workflow better 

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Fix player movement on zoned servers (UNR-1820).
The symptom fixed by this PR was that, on a zoned deployment, one or more players would occasionally not have control of their player after joining a session. This was because the player movement component was not initialized, which is further caused by the client not processing the ClientRestart RPC.
The root cause is that the sending worker had two channels for the Actor for the RPC, and was checking the incorrect channel to determine if the channel is ready to receive RPCs.
Also made some changes to validate preconditions for private functions and avoid creation without first checking for existence of a channel.
In CHANGELOG.md
Run a deployment with multiple server workers and clients.
=> Fix player movement when on zoned servers

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/CodeGenerator/Unreal/SourceGenerator.cs, SpatialGDK/Build/Scripts/ExternalSchemaCodegen.bat
Fix in generated code for non-Unreal workers so fields to clear are correctly deserialized
David tested the dbsync work when deserialize events, and Ally tested his original test project which deserializes component updates.
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for reviewing this …
=> UNR-1814 - Fixing event fields to clear deserialization

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp, SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp, SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h, SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesModule.h
-------
This PR refactors some existing logic that retrieves the SpatialOS project from the spatial.json file and other utility functions from the `FLocalDeploymentManager` to the `FSpatialGDKServicesModule` and making them static. It also removes duplicated code from the Cloud settings that retrieves the SpatialOS project name.
@joshuahuburn
=> Refactor utility functions

SpatialGDK/Build/Scripts/ExternalSchemaCodegen.bat
=> Updated ExternalSchemaCodegen.bat to take a project path argument

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
-------
Fix the text overflow in the cloud deployment configuration popup window by splitting the text in two different slots.
@girayozil
=> Fix cloud deployment text overflow

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/Schema/ClientRPCEndpoint.h, SpatialGDK/Source/SpatialGDK/Public/Schema/ServerRPCEndpoint.h
-------
Changing the way IsListening check is performed for ActorChannel.
This should fix a bug, when SpatialActorChannel never started listening.
Testing with Scavengers and ExampleProject.
No doc update.
=> IsListening and ownership fix

SpatialGDK/Extras/internal-documentation/release-process.md
-------
Add step to release process to ensure availability of XBox Worker SDK DLLs.
n/a
n/a
n/a
@ernopp @oblm @m-samiec
=> Add XBox DLL step to release process

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
-------
Fixes sim player launch configs not being valid when using an Engine Plugin.
Bugfix: Fixed Simulated Players launch configurations not being valid when using an Engine Plugin installation.
*How can this be verified by QA?* Use the Deploy button, click `Add Simulated Players`, no error should occur to do with invalid launch configs.
@m-samiec @claireimprobable
=> UNR-1864 Use GetPlugin helper method to resolve sim player launch config

SpatialGDK/Documentation/content/actor-handover.md, SpatialGDK/Documentation/content/authority.md, SpatialGDK/Documentation/content/cross-server-rpcs.md, SpatialGDK/Documentation/content/get-started/introduction.md, SpatialGDK/Documentation/content/glossary.md, SpatialGDK/Documentation/content/spatialos-concepts/schema-and-snapshots.md, SpatialGDK/Documentation/content/technical-overview/gdk-concepts.md, SpatialGDK/Documentation/content/technical-overview/gdk-principles.md, SpatialGDK/Documentation/content/tutorials/multiserver-shooter/tutorial-multiserver-intro.md, SpatialGDK/Documentation/content/tutorials/offloading-tutorial/offloading-gameplay-changes.md, SpatialGDK/Documentation/content/tutorials/porting-guide/tutorial-portingguide-logs.md, SpatialGDK/Documentation/content/workers/offloading-concept.md, SpatialGDK/Documentation/index.md, SpatialGDK/Documentation/unreal-features-support.md
-------
- updated multiserver shooter name
- improved some definitions in the glossary (offloading, authority, zoning) and in the GDK concepts page (Actor groups, zoning, offloading)
- improved offloading definition in the new offloading page intro (for consistency) but DIDN'T touch the rest of that page
- added info where necessary, about (1) offloading and zoning being two multiserver options, (2) zoning being in pre-alpha, and (3) single server being the default
- some driveby updates
@ElleEss
=> DOC-1256 clarify status of zoning and offloading

SpatialGDK/Extras/schema/core_types.schema, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitReader.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitWriter.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetBitWriter.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.cpp, SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaUtils.h
-------
If the singleton entity is not checked out at the time we want to set a property or call an RPC with a singleton actor as the argument, use its class path to make an UnrealObjectRef instead, indicating that it's the singleton actor with a bool.
This allows us to remove the queuing logic on the sending side, as the other cases have already been handled by the EntityPool.
Tested by having a non-GSM-authoritative server spawn a cube and assign a property to GameState. The property is replicated using the singleton class path and correctly resolved on the client when it …
=> UNR-1456 Use class path to refer to singleton actors

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
Running a cloud deployment within the editor could result in an non-descript "Deployment configuration is not valid" error. This was because the default snapshot and launch config files that are used to populate the window aren't used in the validity checks when running. Switching the validity check to use the same method that populates the window fixes this.
Ran cloud launch from within the editor
@WVerlaek @joshuahuburn
=> UNR-1942 - Switch validity checks to use whats defaulted

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
-------
UNR-1644: Change SpatialGDKGenerateSchema to cause the window to display "schema generation failed" if schema compilation failed.
Bugfix: When schema compiler fails, schema generation correctly shows an error.
Running schema generation normally succeeds as normal. Deleting GDK schema files and running an iterative schema gen correctly produces an output.
How can this be verified by QA? 
Run an iterative schema gen that should succeed and confirm the window displays the succeed message, then force the iterative schema gen to fail (e.g. by deleting GDK schema files) and …
=> UNR-1644: Schema compiler failure should fail schema generation

CHANGELOG.md, README.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/Schema/ClientRPCEndpoint.h, SpatialGDK/Source/SpatialGDK/Public/Schema/ServerRPCEndpoint.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp
This pull request releases patch version `0.6.1` into `preview`.
- The [Multiserver zoning shooter tutorial](https://docs.improbable.io/unreal/alpha/content/tutorials/multiserver-shooter/tutorial-multiserver-intro) has been updated to use the Example Project.
- Simulated player launch configurations are no longer invalid when the GDK is installed as an Engine Plugin.
- RPCs that have been queued for execution for more than 1 second (the default value in `SpatialGDKSettings QueuedIncomingRPCWaitTime`) are now executed even if there are unresolved parameters. This stops unresolved parameters from blocking the execution queue.
- Offloading is no longer enabled by default in the Example Project. You can toggle offloading on using [these …
=> 0.6.1 hotfix

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaCommandlet.cpp
-------
Change IsEditor = True in GenerateSchemaCommandlet.cpp to fix crash with GenerateSchemaCommandlet.
Fixed crash with GenerateSchemaCommandlet.
Run GenerateSchemaCommandlet and verify that the program does not crash.
@joshuahuburn  @mattyoung-improbable
=> UNR-1957: Generate schema commandlet crashes because editor is missing

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
-------
Added SAVE_NoError save flag to SavePackage() to prevent the error being thrown that was locking up the editor when trying to access a locked file.
Modified some of the logic behind error messaging to ensure this case was correctly reported as a failed schema generation.
Generating schema when the schema database is locked by another process will no longer crash the editor.
Successfully reproduced the bug following steps in associated ticket prior to fix. Bug no longer occurs when following the same steps or when attempting to lock the schema database in other ways.
Bug …
=> UNR-1878: Generate Schema Crashes if SchemaDatabase is locked by another process

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h
-------
Unreal produces a warning (rather than crashing the game) if the game attempts to replicate an unsupported type (such as TMap). This PR changes the GDK to match this behaviour.
Attempting to replicate unsupported types (such as TMap) produce a log error rather than crashing the game.
Tested by replicating a TMap in GDKCharacter in the example project and verifying that the game no longer crashed but produced an error.
How can this be verified by QA?
Create an actor that contains a replicated TMap property and play with spatial. The game should run normally with an error …
=> UNR-1402: Crash when attempting to replicate a non supported type

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
Entity creations can timeout locally, and still be processed by the runtime. In these instances, we get an error when our follow up entity creation command fails. Attempt to detect this scenario and suppress error. Also moved the bCreatedEntity set value to a path that's sure to be caught in the same scenario.
Bugfix: Additional create entity requests don't erroneous error
@cmsmithio @improbable-valentyn
=> Check for entity in view before erroring in create response

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
-------
Fixes an issue where we try to register the level actor twice as it's both a singleton and a stably named actor.
This was triggering a checkfslow in `FSpatialNetGUIDCache::RegisterObjectRef` when running in debug
Bugfix: No longer register level actors twice in the GUIDCache.
Had consistent repro on registering level actors twice when booting to any map. Post fix the level actor is only registered once.
How can this be verified by QA?: Boot into a debug build of any map and the checkf at `FSpatialNetGUIDCache::RegisterObjectRef` does not trigger. …
=> No longer register actors which are singletons and also stably named

SpatialGDK/Documentation/content/cloud-deployment-workflow.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-cloud-deployment.md, SpatialGDK/Documentation/content/get-started/example-project/exampleproject-local-deployment.md, SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-cloud.md
This explains to users going through the Template and Example Project Cloud Deployment guide how to use BuildProject.bat based on whether they have a project or engine plugin.
The Cloud Deployment Workflows page is also updated to reflect both options (engine and project plugin) as that was missed out (feedback raised by Tom Looman [here](https://docs.google.com/document/d/1kx02Jw1GdGQpMWgwaMKChvoxPpCnh4rqFBI7e9e-4ik/edit))
=> UNR-1937 - BuildProject.bat filepaths for engine and project plugin

SpatialGDK/Documentation/content/get-started/manual-engine-build.md
In the manual fork installation instructions we have linux cross compliation instructions although theyre already part of the dependencies page which we say is a prerequisite step
=> Docs - remove duplicate linux cross compilation instruction

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialDispatcher.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
-------
Added a simple multicast delegate that users can bind to in `SpatialMetrics` when a Worker Metrics Op is received. 
Feature: Added a delegate to `SpatialMetrics` which triggers when worker metrics have been received.
Printed the result of the map passed to the delegate and it works.
@m-samiec 	@mattyoung-improbable
=> UNR-1993 Worker Metrics Delegate

SpatialGDK/Documentation/content/tutorials/tutorial-porting-guide.md
The shootergame reference project is on 4.20 so no longer valid now that users default to 4.22
This PR removes the docs mention of it. We also need to remove it from the fork UNR-2094
=> UNR-2094 Remove shootergame reference (it's on 4.20)

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
-------
Add net relevancy check to replicating actors. When prioritizing actors for replication, the position of each actor is checked against the NetViewCullDistance of each player controller present in the game. If the actor is not withing these ranges or is not bAlwaysRelevant, it will no longer be replicated.
Tested this branch and master branch in a large scale game with Unreal performance stat capturing enabled to diff and performance gain.
=> Actor Replication Net Relevancy

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
When running a deployment with multiple server workers, it's possible for a worker to gain authority over a player controlled pawn, its player state, and its player controller in an arbitrary order. This change adds handling for the case when the worker gains authority over the pawn before receiving the player state.
Added to changelog
Found, debugged, and tested in Edmonton project. 
@m-samiec @cmsmithio
=> Fix initial player control in a multi-worker (zoned) deployment.

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
Previously, there was no way to disconnect from SpatialOS as a client once you've connected to it. We now destroy the SpatialWorkerConnection when destroying the NetDriver if we don't persist it.
=> Destroy SpatialWorkerConnection when destroying the NetDriver to be able to disconnect from SpatialOS

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
-------
Fixes issue that caused a error messages using level streaming with QBI whenever a client gained visibility of a level and owned an unreplicated actor.
Streaming levels with QBI enabled no longer produces errors if the player connection owns unreplicated actors.
Set up level streaming and notice that errors are produced when a level is streamed in (since CameraManager is a child of PlayerController and is not replicated). Errors disappear with this fix.
@m-samiec
=> UNR-2010: Streaming levels causes error messages with QBI

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Check for world before dereferencing
Transient issue introduced in https://github.com/spatialos/UnrealGDK/pull/1358 - no release note required.
Shutdown game in editor without crash.
=> Check for world before dereferencing

.buildkite/premerge.steps.yaml
Changing to trigger the Example Project not the Third Person Shooter build as a postmerge into master, preview or release branches.
Related ticket: UNR-2019
No need, it's a BuildKite fix.
No need, it's a BuildKite fix.
=> CI: correct triggered pipeline name

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md, SpatialGDK/Documentation/content/get-started/manual-engine-build.md, SpatialGDK/Documentation/content/get-started/starter-template/get-started-template-local.md
* Better explanation of auto-install
* Remove wrong GDK clone instruction https://docs.improbable.io/unreal/alpha/content/get-started/manual-engine-build#step-2-clone-and-install-the-spatialos-gdk-for-unreal-plugin - at this stage you don't yet have a project to set up so you can't clone the GDK into it
* Link to manual example/starter projects install guides from the manual install build 
=> Docs - fix the manual install flow

CHANGELOG.md
-------
Added a breaking change entry to CHANGELOG for replicated subobjects that don't inherit from ActorComponent or GameplayAbility.
@oblm @m-samiec
=> Add breaking change entry for replicated subobjects

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
-------
This is an issue that I reproduced in an offloading scenario where the weapon actor had a `ServerNotifyHit` with a parameter of type `FHitResult` that could sometimes end up at the front of the queue of incoming RPCs for the actor and never be applied. This caused other RPCs such as reloading to stop being applied too. This change uses the already existing setting `QueuedIncomingRPCWaitTime` to periodically process incoming RPCs.
Bugfix: Fixed an issue that could cause queued incoming RPCs with unresolved references to never be processed.
Reproduced fail to reload issue …
=> UNR-2154: Queued RPCs with unresolved references are never processed in some cases

SpatialGDK/Extras/schema/spawndata.schema
Quick bug fix to allow schema gen to proceed with the SpatialOS 14 upgrade.
Not required, as this should have been part of the previous merge.
Tested with UnrealGDKExampleProject, ThirdPersonShooter.
N/A
@samiwh @m-samiec
=> Fix schema generation with SpatialOS 14

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/Components/ActorInterestComponent.cpp
Drive-by fix to ensure that queries created by the ActorInterestQueryComponent specify a result type. Fixes an issue in Edmonton prototype where queries weren't returning any result.
@m-samiec
=> Ensure that ActorInterestQueries specify a result type

SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
Switch from regular kcp to the modular udp networking stack.
todo - Potential bandwidth saving
Currently only testing on cloud deployments. For actual bandwidth tuning there is a different plan.
=> Use the modular upd networking stack

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Switching an actor from awake → dormant → awake can crash UE4 when handover data is enabled. This bug was caused by SpatialActorChannel not being properly reset when reused (from pool). The fix initializes all state in the Init function that is called by the pooling system.
Tested locally with modified crashbot gym with & without offloading enabled.
=> [UNR-2187] Bugfix Handover causing crashes in net dormancy

CHANGELOG.md, SpatialGDK/Extras/schema/authority_intent.schema, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp, SpatialGDK/Source/SpatialGDK/Public/Schema/AuthorityIntent.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
-------
Add a managed component to track the virtual worker ID. This is the first step in UnrealGDK-controlled zoning behavior. In this PR, we create the component in schema, add functionality to read and set the component value, and create the component with a value when we create a new entity. Future PRs will restrict worker behavior based on the value of the component and will track the physical worker ID to virtual worker ID mapping.
- Added an AuthorityIntent component to be used in the future for UnrealGDK code to control loadbalancing.
How did you test these changes …
=> Add an AuthorityIntent component

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
-------
Fixed a bug with multicast RPCs, that were not processed if called close to entity creation.
Updated CHANGELOG.md.
Mutlicast called close to entity creation are now processed.
Mutlicast called close to entity creation are now processed.
=> UNR-2193 Dropped Multicast RPCs Fix

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
-------
This fixes the issue where projectiles would have their Spatial position at origin.
Fixed an issue where the owner's Spatial position was used even if it wasn't replicated.
@m-samiec @oblm
=> UNR-2194 Only use Owner's Spatial position if the owner is replicated

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
When an actor wakes up and updates a replicated variable at approximately the same time, it is possible that on the receiving side these updates arrive in reverse order, causing the update to the variable to be dropped. This change fixes this issue by creating a channel on component update - anticipating the wake up.
Should not need one, as it should just go under dormancy fixes.
An intially dormant actor with a repnotified variable - manual.
May need more investigation, which I believe @aleximprobable may do.
N/A.
@aleximprobable @m-samiec
=> [UNR-2195] Fix component updates being dropped when waking up an actor

SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp, SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.h, SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.cpp, SpatialGDK/Source/SpatialGDKEditorCommandlet/SpatialGDKEditorCommandlet.Build.cs
CookAndGenerateSchema commandlet will crash if bSpatialNetworking is false, so this PR forces it to true before running.
This PR also includes:
- A `SkipSchema` switch added to GenerateSchemaAndSnapshots commandlet to skip over schema generation
- Some initial documentation (in header comment) to CookAndGeneratSchema
=> [UNR-2220] Bugfix: Force bSpatialNetworking in CookAndGenerateSchema

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
-------
It's possible to have an actor channel be ticked when it's actor has been deleted. Remove unneeded check which can crash when an actor channel which is pending dormancy has a deleted actor.
=> Bugfix - Deleted actor dormancy check

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
-------
Recent changes might have invalidated an old assumption about having a valid GUID in `PreReceiveSpatialUpdate`. Removing the check for now and adding a warning log to have more context in case this causes a crash further down the line.
@joshuahuburn @oblm
=> Replace an outdated check with a warning log

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Fixed a crash that would occur when checking out an entity that deletes a static subobject on rep notify for a replicated variable inside the actor before trying to apply component data for that subobject.
Fixed a crash upon checking out an actor with a deleted static subobject.
@joshuahuburn @oblm
=> UNR-2243 Fix a crash when applying component data for deleted static subobject

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
A new `Worker` component `60` has been added to the runtime and we're trying to process it. In order to avoid issues like this going forward we should ignore the entire reserved range defined here: https://docs.improbable.io/reference/14.1/shared/schema/reference#ids
=> Ignore ops for components in the spatial reserved range (<100)

SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerTest.cpp
-------
In this tiny PR I'm increasing the `MAX_WAIT_TIME_FOR_LOCAL_DEPLOYMENT_OPERATION` in `DeploymentManagerTest.cpp` from 10 to 20 seconds. Shortly after Unreal startup, starting the deployment manager takes slightly longer, which caused the test to fail for me. This change gives some more time for the deployment to start up.
I haven't added a release note for this tiny change to the testing suite.
The initial unit test after Unreal startup stopped failing for me after this change.
No documentation has been added.
If your change will take a long time to review, you can name …
=> give deployment more time to start

SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Fix static initialization that's failing ExampleProject CI.
This was breaking because the editor tried to init these global variables regardless of whether the tests module was loaded.
=> UNR-2311 Fix static initialization in SchemaGen tests

CHANGELOG.md
-------
I've updated `CHANGELOG.md` to detail a work around for a breaking change that I believe Microsoft introduced in Visual Studio Installer **16.3.6**.
The breaking change re-maps component dependencies so that **MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.23)**  is treated as a dependency for:
* **Game development with C++**
* **Unreal Engine installer**
* **C++ CMake tools for Windows**
* **C++ profiling tools**
* **Graphics debugger and GPU profiler for DirectX**
We previously worked around a separate breaking change that Microsoft had [inadvertently …
=> Add MSVC install workaround to CHANGELOG

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Fixes an issue where entity creation fails when under load. The problem is that SpatialReceiver only calls the delegate in EntityPool on success, but EntityPool has error handling for retries, as well as all local handling for expiring the existing pools.
Added to changelog
Testing in NWX. Requires entity id batch reservation to fail to reproduce.
=> Call ReserveEntityIdsDelegate unconditionally.

SpatialGDK/Documentation/unreal-features-support.md
As per https://improbable.slack.com/archives/CG3HFTK8T/p1572381238246600
=> Docs - add replicated blueprint timelines to the features support page

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
Improved our handling of create entity response ops to give slightly better logs.
Improved error messages relating to creating entities.
Testing this properly requires more framework.
Will test this in a deployment known to have issues with creating entities timing out.
Release note.
=> Better create entity response handling

.buildkite/premerge.steps.yaml
-------
Due to a recent Buildkite, scheduled builds no longer have an associated user account - which caused authentication to fail. Engineering Foundations has since introduced an update to fix this, but this requires using a newly baked image and its associated queue. This PR implements the new queue.
This change is not customer-facing and thus not included in the release notes
A green scheduled build can be found here: https://buildkite.com/improbable/unrealgdk-premerge/builds/6345
What automated tests are …
=> Update buildkite queue

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
-------
Epic's code usually passes `GARBAGE_COLLECTION_KEEPFLAGS` to `CollectGarbage`, which resolves to a `RF_Standalone` in editor and `RF_NoFlags` otherwise.
I believe this is the reason schema generation sometimes caused ensures to be fired in `FSoftObjectPath::SetPath` (`Cannot create SoftObjectPath with short package name <something>! You must pass in fully qualified package names`)
@mattyoung-improbable @m-samiec
=> Fix garbage collection during schema generation

SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp
bIsAwaitingResponse is being towards the end of the response callback in EntityPool. If a timeout occurs, the callback will attempt a retry _before_ resetting the flag, causing a check to fail.
=> Bugfix: EntityPool fails if call times out

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Schema database was outdated and there was no generated schema for a static subobject. Print a warning instead of crash (there will already be errors printed for schema database so the user will know to regen schema and try again).
=> Fix editor crash when running with outdated schema (no schema for subobject)

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslator.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/EngineClasses/SpatialVirtualWorkerTranslator/SpatialVirtualWorkerTranslatorTest.cpp
-------
Update the VirtualWorkerTranslator to query for worker system entities to assign virtual workers to.
Some automated tests included. Really want to have a fake NetDriver to test with, but that's outside the scope of the PR. Can't be tested by QA until the glue task is done.
Code comments, no public …
=> Update the translator to query for connection entities

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h
-------
The server no longer crashes, when received RPCs are processed recursively.
Updated CHANGELOG.md.
Tested with Scavengers
Updated CHANGELOG.md.
@m-samiec
=> UNR-2364 Crash in ProcessRPCs

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
When a startup actor is deleted as its entity comes into view with a Tombstone
component, it won't have an ActorChannel created yet.
=> Reduce log severity when deleting an actor with no channel

.buildkite/premerge.steps.yaml, CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp, SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp, SpatialGDK/Source/SpatialGDKTests/Private/SpatialGDKTestsModule.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/Misc/SpatialActivationFlags.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp, SpatialGDK/SpatialGDK.uplugin, ci/gdk_build_template.steps.yaml
Uses accessors for bSpatialNetworking instead of the class member.
Add a test which checks we get the correct setting for Spatial networking early in the startup process.
Depends on PR : https://github.com/improbableio/UnrealEngine/pull/287
Added two tests : 
- SpatialActivationReport, which logs the state of the SpatialActivation flag
- SpatialActivationOverride, which launches a sub-process running SpatialActivationReport with various combination of settings and reads the log to determine if we got the flag state we expect.
=> UNR-2363 Use accessors to get Spatial Networking flag from settings

SpatialGDK/Documentation/content/get-started/build-unreal-fork.md, SpatialGDK/Documentation/content/get-started/dependencies.md, SpatialGDK/Documentation/content/pricing-and-support/versioning-scheme.md, SpatialGDK/Documentation/content/upgrading.md, SpatialGDK/Documentation/unreal-features-support.md
-------
Updated the Keep your GDK up to date guide to:
* Acknowledge the existence of `preview`
* Tell users that they must re-build when upgrading Unreal Engine version.
https://github.com/spatialos/UnrealGDK/pull/1494
Rendered and linted in improbadoc.
This is documentation. It looks like this (ignore the asset lint errors, that's a known lint bug):
=> Updated the Keep your GDK up to date guide

ci/setup-gdk.ps1
-------
A previous change removed default arguments from the `setup-gdk.ps1` script. However, as the CI in other repositories made use of this script in isolation, removing the default arguments was a breaking change for these pipelines. This PR restores the defaults for these arguments.
This change is not customer facing, no release note has been added.
A new build was kicked off on the `UnrealGKDExampleProject` CI that uses this branch of the UnrealGDK. The new build is passes the `build-editor` step that previously broke due to missing arguments.
Example of broken build: …
=> UNR-2419: make gdk setup self-contained

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDK/Public/Utils/RPCContainer.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectSpy.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/ObjectSpy.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/RPCContainer/RPCContainerTest.cpp
-------
RPC types were previously in ESchemaComponentType, but they didn't actually correspond to separate schema components (reliable and unreliable RPCs went through the same component). This will also make things cleaner for the ring buffer PR.
Additionally, I removed the old reliable RPC order checking as it hasn't been used for a while and the functionality is going to be redundant once we have ring buffers.
@m-samiec @aleximprobable
=> Move RPC types into separate enum, remove old reliable RPC checking

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitReader.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetBitReader.h
When replicating structs containing references to actors for which their entity had yet to be created, the field remained unresolved, even if we receive the entity later.
The code in ComponentReader::ApplyProperty did not take into account the array of unresolved references, instead relying on the bHasUnmapped flag, which was not flipped when there was unresolved reference.
Also, in SpatialActorChannel::RemoveRepNotifiesWithUnresolvedObjs, the rep notify was removed in the presence of unresolved references in arrays. The spec is to allow partial states in arrays, and rely on the customer to check the reference validity (I would be in favor of having an option for that, to be able to handle only fully resolved arrays).
Manually tested with an array of structs on the GameState populated …
=> UNR 1132 Correct handling of unresolved reference in structs

SpatialGDK/Extras/fastbuild/README.md
* Explains to external users they need to use their own fileshare
* Explains to internal users they first need to authenticate to our network drive
* References the GDK's fastbuild install scripts not the remote ones which external users can't use (tested, they work)
Feel free to contribute other additions to this!
=> Update fastbuild readme

RequireSetup, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
Don't try to force SpatialNetworking if using pak files, since the staged file is not present.
Tested with BuildWorker.bat locally.
Using UnrealGDKTestGyms project:
1. Run BuildProject.bat
2. Verify that ```Forcing bSpatialNetworking to True``` appears in logs for all workers built.
3. Edit BuildProject.bat, add `-pak` to BuildWorker.bat lines (before `|| goto :error`)
4. Run modified BuildProject.bat
5. Verify that ```Cannot force bSpatialNetworking with -pak argument.``` appears  in logs for all workers built (and it succeeds)
=> Bugfix Skip forcing spatial networking if -pak argument is present

SpatialGDK/Documentation/index.md
Improves the flow on the welcome page for the GDK documentation by removing duplication, streamlining discussion of multiserver networking and clarifying the Find out more section
You can see this staged here https://docs-staging.improbable.io/unreal/alpha (ignore the link at the top of the page, which snuck in but has since been removed by an additional commit -- in this PR)
This is the ticket https://improbableio.atlassian.net/browse/DOC-1358
=> Fixes DOC-1358 Work to tidy up welcome page

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
A static code analyser brought up this issue that we don't consistently check for NetDriver existence. If I recall, the original check was added when this code was invoked while the world was being torn down. Extended the check to the whole function.
=> Added netdriver check in SpatialActorChannel::Cleanup

ci/report-tests.ps1
-------
Tiny change to upload the correct number of tests
Not customer facing. No release note has been added.
The slack messages are displaying the correct amount, that value is now used.
No new documentation has been added.
@michelefabris @mironec
=> Fix tracking of number of tests

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
-------
Removed Validity check for LoadBalancer, since it can be null if not specified in UE4 settings.
No release note update.
Verified that UE4 doesn't crash when the LoadBalancer is not specified.
No doc update
@ImprobableNic @m-samiec
=> Removed Validity check for LoadBalancer

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h, SpatialGDK/Source/SpatialGDKEditorToolbar/SpatialGDKEditorToolbar.Build.cs
-------
This PR enables adding & modifying iOS command line arguments to installed packages instead of having to hardcode all arguments in code.
still need to do that.
tested manually on mac & windows. 
will be added to the iOS guide.
=> Enabling pushing iOS command line arguments to builds

Setup.sh
-------
The domain env for Setup.sh was missed during the merge from 0.7.1-preview into master. This adds it back in.
@improbable-danny @oblm @jessicafalk
=> Add domain env var to setup.sh

SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
In this diff when user start a local deployment I check that it's running in the correct directory. If it's running from a wrong directory I show dialog and stop the service which is already running.  
1. Start a spatialos service from another project. 
2. Go to the target project and try to start a local deployment.
3. See the dialogue to stop an already running service. 
4. Click yes
5. Service which is running in a wrong project is stopped. Local deployment and spatial service started successfully. 
Do we need a …
=> UNR-2318 stop spatial service which runs in different project

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
Don't initialize worker translator if load balancer disabled.
This PR is just for the 0.8.0-rc, and a related fix has already gone into master, however as the fix was wrapped in a larger refactor, I've just re-implemented the required bits. This will cause a conflict when we merge back into master.
@MatthewSandfordImprobable @oblm
=> Don't initialize worker translator if load balancer disabled

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/ReferenceCountedLockingPolicy.cpp, SpatialGDK/Source/SpatialGDK/Private/Schema/UnrealObjectRef.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLockingPolicy.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/ReferenceCountedLockingPolicy.h, SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/GridBasedLBStrategyTest.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/ReferenceCountedLockingPolicy/ReferenceCountedLockingPolicyTest.cpp
Review in COMMIT ORDER for MAXIMUM CLARITY
This is in `AbstractLockingPolicy` and `ReferenceCountedLockingPolicy` and is ready for review. The relationship between these two classes is very similar to the relationship between the abstract and grid-based LB strategies. They are set in the same settings location and instantiated in the same net driver code. The `SpatialActorChannel` conditional for changing auth intent now also checks that an actor is not locked before sending an update.
Currently, actors are made lockable through manually adding a new ActorComponent `SpatialLockingComponent` which effectively exposes the LockingPolicy for that actor. This was the fastest path to having a working test gym, as well as having a way to replicate the locking state to the client for the …
=> UNR-2352 Pop & locking actors

CHANGELOG.md
Changelog was incorrect. Fixed it up for the 0.8.0-preview release. 
The PRs with the original mistakes (these did not go into 0.7).
https://github.com/spatialos/UnrealGDK/pull/1367
https://github.com/spatialos/UnrealGDK/pull/1387
https://github.com/spatialos/UnrealGDK/pull/1408
=> Move bad changelog edits to correct position

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
-------
Fix SpatialDebugger crash fetching virtual worker color with GDK-space load balancing disabled.
CHANGELOG.md updated.
Verified when using PIE with GDK-space load balancing disabled and SpatialDebugger enabled, it no longer crashes.
As described under Tests above.
release note
@alastairdglennie
=> Bugfix/unr 2607 SpatialDebugger crashfix

SpatialGDK/Documentation/content/get-started/dependencies.md
-------
Based on feedback from testers and a few mis-steps I have updated the dependancies page to include the requirements of signing up to microsoft dev essentials in order to access the Visual Studio 2017 installer. 
This updates this page in docs - 
https://docs.improbable.io/unreal/latest/content/get-started/dependencies
UNR-2577 Docs change to make VS 2017 download steps clearer
Tested locally using docs serve
Updated dependancies page - https://docs.improbable.io/unreal/latest/content/get-started/dependencies 
If your change will take a long time to review, you can name …
=> UNR-2577 Docs change to make VS 2017 download steps clearer

SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/Connection/SpatialWorkerConnectionTest.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.h
This fixed compilation issues when running the GDK as an engine plugin, still needs testing as a project plugin (CI should be sufficient).
=> Fix includes in worker connection tests for engine plugin build

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitReader.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetBitReader.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h, SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentReader.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Unlike what the vanilla net driver was doing, we did not track references to replicated actors in replicated properties. It allows restoring pointer in replicated properties to the right actor when they become relevant again.
This is is an addition to how we currently handle unresolved references, since it works only the first time a property is replicated.
This PR essentially add tracking to properties referencing replicated actors, similar to what Unreal was doing, only with FUnrealObjectRef instead of NetworkGUID.
FObjectReferencesMap are extended to also remember the mapped references, and they are wrapped into a utility class, FSpatialObjectRepState.
Then, for each reference, we will add this additional RepState to a map, USpatialReceiver::ObjectRefToRepStateMap.
When an actor is …
=> [UNR-2275] Track references to replicated objects in order to restore them when they move out and in relevance.

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
Worker region Actors collide with some actors it seems, discovered in GASTest where the player can stand on top of the worker region:
One line fix adding `WorkerRegion->SetActorEnableCollision(false)` to the spawning logic:
=> Fix worker region collision

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
When an actor channel is cleaned up/closed multiple times, it can happen that the invariant that the channel's Ref map and the receiver's ref map are in bijection is broken, because we forgot to empty the reference map when cleaned up from USpatialNetDriver::RemoveActorChannel
An annoying non-fatal assertion was triggered on the second call to CleanupRepStateMap.
=> [UNR-2275] Assert called when an actor channel is cleaned up multiple times

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
- Added CN locator endpoint
- Moved ServerRegion from SpatialGDKEditorSettings to SpatialGDKSettings
-------
Locator endpoints can now follow the Server Region setting.
Updated.
Change the Region Settings in SpatialOS GDK for Unreal > Runtime Settings to CN and see if it connects to the CN environment.
N/A
=> [UNR-2612] Added CN Locator endpoint

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
The changed code could cause a null pointer exception in release. It may have happened in a Scavenger playtest in a case when both maps would have been desynchronized (the cause of the desync has been corrected).
The new code is safer in release while still catching error in test.
=> Change FindChecked call by code that would not crash in release

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h, SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.cpp
If creating a subobject and setting a replicated reference to it in approximately the same tick, the reference would be set to null forever. This fixes the issue by resolving the dynamic subobject earlier in replication.
Replicated references to newly created dynamic subobjects should now be resolved correctly.
Created DynamicComponentTest in EngineNetTest.
TODO: maybe more in-code docs, maybe more logs to alert us when things fail.
@Vatyx @m-samiec @improbable-valentyn
=> [UNR-2738] Fix dynamic subobject references not being set correctly

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
This is a safe approach to the fact that changing AuthorityIntent indicates you're about to lose authority via the enforcer and will reduce the likelihood that you try to act in an authoritative manner while SpatialOS is taking away your authority.
We're always setting Role to SimulatedProxy and RemoteRole to Authority (regardless of autonomous proxies).
This could simplify checking whether you can acquire a lock to just checking the ROLE_Authority, making UNR-2770 quite trivial. 
This would also simplify GAS ability locking in UNR-2531 which already respects ROLE_Authority.
=> Set ROLE_SimulatedProxy when setting a different authority intent

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
-------
RepNotifies for newly created subobjects were called with empty state (because ResolvePendingOperations was called before applying component data)
@mironec @m-samiec
=> [UNR-2696] Resolve pending operations after applying component data

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
-------
Some of the work I've been doing to add the dev auth flow properly into the GDK.
It also refactors the flow a bit by making it a bit simpler and isolating the construction of the different connection configs into one method instead of starting to construct it in one and finish constructing it in the other.
PR can be read in commit order.
REQUIRED: Add a release note to the `##Unreleased` section of CHANGELOG.md. You can find guidance for writing useful release notes [here](../SpatialGDK/Extras/internal-documentation/how-to-write-good-release-notes.md). Documentation …
=> Adding dev auth flow into SpatialNetDriver

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialOSDispatcherInterface.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/Utils/EntityFactory.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/SpatialOSDispatcherInterface/SpatialOSDispatcherSpy.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/SpatialOSDispatcherInterface/SpatialOSDispatcherSpy.h
READ IN COMMIT ORDER FOR THE BEST OF TIMES
Adds the ability to delete initially dormant startup actors. When such an actor is deleted a tombstone entity is created containing a minimum number of components. In order to be able to retry creating these entities we have to store the component data in the sender and copy it for each attempt.
Currently ownership is denoted by a unique pointer with a custom deleter. Likely improvements to this would be to have an RAII type for worker components rather than just on the array however this seemed like the larger change in this PR.
Fixed an issue where deleted, initially dormant startup actors would still be present on other workers.
Test gym 
Release note.
@m-samiec
=> Ability to delete initially dormant startup actors

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/ConnectionConfig.h
-------
Making it possible to parse in command line arguments for player id, display name and metadata.
added a changelog entry (for this and the last dev auth PR)
still need to test it
documentation will happen with UNR-2757
=> Make the Dev Auth Config more configurable

SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp, SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaAndSnapshotsCommandlet.cpp, SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/GenerateSchemaCommandlet.cpp
Our commandlets could cause dialog prompts (ie. due to in memory blueprints changes), so defaulting them to `unattended` mode to ensure default actions are taken.
@mattyoung-improbable @improbable-valentyn 
cc: @ImprobableVlad
=> Default unattended mode in commandlets

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
Exposing all the different fields that can be set for the dev auth flow for when using Map URL only instead of command line args.
=> Exposing dev auth fields as URL options

Setup.sh
-------
Error log: conditional binary operator expected.
That is caused by `-v` only support bash 4.2 and above.
Modify it to `-n` to check for non-null/non-zero string variable here.
Verified it on MAC laptop.
Bash version: bash-3.2
System: Mojave 10.14.6
=> MBL-23 Setup.sh does not work on mac system.

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorLayoutDetails.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Adds a button to the Spatial GDK Editor Settings to generate the dev auth token directly inside the Unreal Editor. 
added it
Tested the button both when being authenticated against SpatialOS and when not
no documentation yet
=> Adding a Generate Dev Auth Token Button

RequireSetup, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Common/LinuxScripts.cs
I had to apply this fix due to running out of disk space in a test worker node with a game client that was just over 20GB (with a 11GB zip file). I'm not sure if the same applies when launching simulated player deployments (in worker nanny nodes of a separate deployment).
Tested by adding a command to output disk usage on the runner before and after the remove command. Also searched simulated client logs for previously seen errors about running out of disk space and didn't find any.
in-code
If your change will take a …
=> Remove simulated player zip from runner on startup

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
When an authority change happens, RPC can be dropped during the transition. That is what happened in UNR-2714, where a missing RPC call from the client caused the server-side character to not move at all when the client-side character moved.
Now we force the usage of RPC ring buffer when Load Balancing is enabled, since it mitigates the issue of lost RPC calls.
WIP
=> [UNR-2714] Force RPC ringbuffer when zoning is enabled

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
-------
We used to call `InitShadowData` in 4.22 and `InitRepStateStaticBuffer` in 4.23 every time before applying replicated state, which constructed the properties in shadow data and allocated memory for TArrays etc.
Corresponding engine PRs:
4.23 https://github.com/improbableio/UnrealEngine/pull/341
4.22 https://github.com/improbableio/UnrealEngine/pull/343
@mattyoung-improbable @mironec
=> [UNR-2736] Don't construct shadow data every time when receiving update

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Have more explicit message about pulling load balancer configuration from SpatialWorldSettings
Relates to engine PRs : 
https://github.com/improbableio/UnrealEngine/pull/339
https://github.com/improbableio/UnrealEngine/pull/340
=> [UNR-2842] Have a more explicit error message when pulling load balancing strategy from world settings

CHANGELOG.md, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp
-------
DeploymentLauncher returned 0 if it failed to launch a deployment. We also weren't printing out the error output from DeploymentLauncher if there was stuff there (e.g. if the project name is wrong which causes the deployment list command to fail).
@MatthewSandfordImprobable @mironec
=> [UNR-2735] Correctly report errors when cloud deployment fails to launch

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
The RepStateUpdateHelper keeps a reference to a TMap entry. In USpatialReceiver::ApplyComponentUpdate, there is a case where if a specific flag has been set, we cleanup the channel. This caused the referenced TMap to be cleared, leaving a dangling pointer which was accessed later in RepStateUpdateHelper::Update
The fix moves the call to update before the channel has an opportunity to be cleaned-up.
The crash was 100% reproducible in the Shooter Game
=> [UNR-2872] Fix crash on dangling pointer

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStaticComponentView.h, SpatialGDK/Source/SpatialGDK/Public/Schema/Component.h
-------
Code cleanup. `ComponentStorage` was unnecessary because there was already a base class `Component` that all other components derive from.
=> Remove unnecessary wrappers from static view storage

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
This functionality was added in 4.22, but we didn't add it to our port.
This allows USpatialActorChannel::ReplicateActor() to safely abort when encountering Actors that shouldn't be replicated etc instead of crashing.
https://improbableio.atlassian.net/browse/UNR-2849
https://github.com/improbableio/UnrealEngine/pull/346
https://github.com/improbableio/UnrealEngine/pull/347
@improbable-valentyn @MatthewSandfordImprobable
=> Dup functionality from DataChannel::ReplicateActor

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/InspectionColors.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialStatics.h
Exposes the get inspection color function to blueprints- required for a server to server RPC visualisation in a test gym which will follow this PR
The test gym works, you can see the colors
@alastairdglennie
=> expose colors to blueprints

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
-------
Move the logic that creates a Spatial connection out of `StartGameInstance` so that the game's GameInstance has an alternative to calling `Super::StartGameInstance` (e.g. when it doesn't want the logic inside `UGameInstance::StartGameInstance`)
@mironec @mattyoung-improbable
=> [UNR-2896] Move the initialization for Spatial connection into a separate function

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorLayoutDetails.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditor/SpatialGDKEditor.Build.cs, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
-------
Adding a section in the Editor Settings that allows you to configure the command line arguments needed to connect your mobile device to a SpatialOS deployment.
can be read in commit order
added
Will be written after merging this PR
=> Adding a mobile settings section

CHANGELOG.md, RequireSetup, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp, SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h, SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.cpp
Commands to spatial from the GDK for Unreal now explicitely specify a runtime version to use. A default runtime is chosen by the GDK version, and settings allow the user to change that.
WIP
=> [UNR-2818] Pin runtime version

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Given a configuration where some workers would need to be manually started, the Cloud Deployment launcher reports that the deployment won't start any worker.
The message reported has been changed to tell which workers won't be started by parsing the configuration file.
Launching Cloud Deploy in the example project, with the one_worker.json config file should report that the DeploymentManager worker needs to be manually started.
=> [UNR-2796] Enhance deployment startup report

SpatialGDK/Build/Scripts/FindMSBuild.bat
Updating the FindMSBuild.bat script to work properly with VS2019, the format of the vswhere command changed at some point.
=> Fixing the ms build script to work properly with vs2019

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/Components/SpatialPingComponent.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
We previously reset the entire object's shadow data in `USpatialActorChannel::PreReceiveSpatialUpdate`. This was mostly wasted effort. With this change, we only reset the shadow data for the updated property.
This should keep parity with Unreal, as the worrisome scenario was this:
1) Let's say replicated X starts at 1 on both the server and client
2) Client changes X locally to 10
3) Server changes X locally to 10
4) Client receives replicated X from the server, but it's the same as the local value so a RepNotify wouldn't be fired on spatial
It turns out, this RepNotify also won't fire on native, because native copies the current value of the property to the shadow data before receiving the property from the wire.
Do we need one? It's an optimisation.
Added a new automated test for …
=> [UNR-2372] Do not reset shadow data for the entire object on every update

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp
-------
Convert variables between THCAR and UTF8 string.
Tested it on macos.
@jessicafalk
=> MBL-32 Fix a crash issue that Unreal Editor will crash when click `Push SpatialOS settings to Android device`.

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
Previously, if trying to create and attach a dynamic subobject to an actor near its creation point, the fields of the dynamic component would not replicate properly after initial creation.
The reason for this was that we were not setting component write ACLs properly for these subobjects. This was due to the change made earlier, to resolve dynamic components earlier, which caused the code trying to check if the subobject is dynamically attached to think it was not dynamically attached, since it has already been resolved. This is fixed by decoupling the writing of ACLs from the resolution of the dynamic object in `SpatialSender::CreateEntity`.
Also a drive-by fix for $lld spam in logs.
Also a drive-by fix for authority queuing not checking which component we got authority over and …
=> [UNR-2887] Fix: Dynamic subobjects attached near actor creation would not be able to replicate their properties

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Quick drive by to remove an overzealous assert I added a while back. IsPlayerControlled checks whether the Pawn's internal PlayerState member is set. That member is set in OnRep_PlayerState, so if we receive the PlayerState actor before the PlayerState property of the pawn is replicated, the assert would fire. Pawn::SetPlayerState catches the replication and sets the pawn's role.
=> Remove overzealous assert

SetupIncTraceLibs.bat, ci/setup-gdk.ps1
-------
This change adds the ability for command line parameters to be passed through SetupIncTraceLibs.bat to Setup.bat (for example --china or --mobile). This change updates ci/setup-gdk.ps1 to pass the --mobile flag when calling Setup or SetupIncTraceLibs. It is necessary to setup the worker_sdk with --mobile in order to build Android and iOS.
Related Jira Tickets:
MBL-4
UNR-2684
This is part of a collection of changes necessary to successfully build Android versions of the Unreal GDK Example Project (GDKShooter). This change is prerequisite to other changes being merged. …
=> Pass --mobile flag when installing GDK for CI builds

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialDebugger.h
Currently, the SpatialDebugger only shows a colour representing a virtual worker for both authority and authority intent. Having the debugger should the actually virtual worker ID would probably be useful.
The code uses the virtual worker colour luminance to determine whether we should have dark or light text for the number.
I'm currently just figuring out how to make this look nice for larger virtual worker IDs
@jennifer-at-improbable-io
=> Add virtual worker IDs to spatial debugger

SetupIncTraceLibs.bat
If the script is started from a directory different than its own, it fails because it can't find Setup.bat
=> GV-230: Fix SetupInTraceLibs.bat to call Setup.bat from the correct directory

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
The SpatialDebugger overhead lock icon currently doesn't work. The SpatialDebugging SpatialOS component property IsLocked was never being set by the authoritative server so never displayed.
It does now:
Follow the instructions for the LockingGym and above the same behaviour as the gif.
@jennifer-at-improbable-io
=> UNR-2926 Fix lock icon on spatial debugger

SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialConnectionManager.h
-------
Before the SpatialWorkerConnection/SpatialConnectionManager refactor, RequestDeploymentLoginTokens was public in SpatialWorkerConnection. As part of the refactor, I made it private on SpatialConnectionManager, not realizing that it was being used by the UnrealGDKExampleProject, so this change broke the Example Project.
As a quick fix to get the Example project working again, I'm just making the function public in the ConnectionManager.
REQUIRED: Add a release note to the `##Unreleased` section of CHANGELOG.md. You can find guidance for writing useful release notes …
=> Make RequestDeploymentLoginTokens public in SpatialConnectionManager

SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/GridBasedLBStrategyTest.cpp
I noticed that the v2 inspector was showing odd results for which worker had auth for an actor when using a 2-row strategy for the runtime and gdk together. Before this change, I would see this:
with these changes, I see this:
=> Fix coordinates in GridBasedLBStrategy

SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
-------
I will be modifying BuildWorker.bat in our projects to remove the building of SimPlayers. This reflects what we say in the docs (that BuildWorker does not build SimPlayers).
https://github.com/spatialos/UnrealGDKExampleProject/pull/104
https://github.com/spatialos/UnrealGDKTestGyms/pull/42
=> [UNR-2978][MS] Added warning on deploying SimPlayers without it being built on your machine.

SpatialGDK/Source/SpatialGDK/Public/Schema/SpatialDebugging.h
VS2019 doesn't like the loss of information when going from an int8 to bool. This fixes our usage of this.
Not required, should have worked from the get-go.
N/A
N/A
@joshuahuburn
=> Fix int8 -> bool compile error in VS2019

.buildkite/premerge.steps.yaml, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialLoadBalanceEnforcer.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialLoadBalanceEnforcer.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalanceEnforcer/SpatialLoadBalanceEnforcerTest.cpp, ci/gdk_build.template.steps.yaml
Actors should only be spawned from an entity at the end of a critical section if we see the unreal metadata component. Otherwise it is _only_ a load balancing entity, and should be treated as such. Entities can dynamically match the definition of each type of entity depending on the authority over the ACL component and the presence of the unreal metadata component.
Handover gym
EDIT: Now with added unit tests!
@m-samiec @samiwh
=> robust actor and not actor receiving

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/GridBasedLBStrategy.h, SpatialGDK/Source/SpatialGDK/Public/Schema/StandardLibrary.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/GridBasedLBStrategyTest.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/TestGridBasedLBStrategy.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/TestGridBasedLBStrategy.h
-------
Server QBI now makes workers express a single interest query. This query is defined by the load balancing strategy. Also moves the worker entity position based on the LB strategy. 
Added sane interest for grid LB based on @yumnuska's changes. 
Enabling the Unreal GDK load balancer now creates a single query per server worker, depending on the defined load balancing strategy.
Unit tests for the grid LB interest
cross server RPC gym depends on this after https://github.com/spatialos/UnrealGDKTestGyms/pull/45 is merged
In code comments
@m-samiec @alastairdglennie
=> server qbi that CAN'T be turned off

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
-------
Previously we got the PlayInEditorID inside ConnectToReceptionist by trying to get the NetDriver and take it off that. Issue with that is that the Example project was making the SpatialWorkerConnection->Connect call before PendingNetGame was set resulting in a crash.
USpatialNetDriver* USpatialWorkerConnection::GetSpatialNetDriverChecked() const
{
UNetDriver* NetDriver = GameInstance->GetWorld()->GetNetDriver();
// On the client, the world might not be completely set up.
// in this case we can use the PendingNetGame to get the NetDriver
if (NetDriver == nullptr)
{ …
=> [CHINF-886][MS] Fixing a crash caused by the merge into release related to the jira issue.

SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp
-------
If you have never ran a local deployment the Spatial Output creation would error on attempting to set up a Directory Watcher. This PR simply attempts to create that log directory if it does not exist. This has became an issue since Spatial Output is now enabled by default.
Transient bug fix
Deleted `spatial/logs/localdeployment` folder. Started editor. No error. Spatial Output worked when creating deployment.
How can this be verified by QA?
Delete `spatial/logs/localdeployment` folder. Start editor. No error. Spatial Output works when creating deployment.
@mironec …
=> Create log directory if it doesn't exist for the spatial output

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h
-------
Need to remove all reference to the net driver from the connection. These are changes from master. Simply use a delegate on spatial worker connection that people can bind to if they want to know about successful or failing spatial connection attempts.
=> Removing the netdriver from the spatial worker connection.

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/Components/SpatialPingComponent.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/Components/SpatialPingComponent.h
-------
SpatialPingComponent can now also report average ping measurements over a specified number of recent pings. You can specify the number of measurements recorded in `PingMeasurementsWindowSize` and get the measurement data by calling `GetAverageData`. There is also a delegate `OnRecordPing` that will be broadcast whenever a new ping measurement is recorded.
Added a UI to display these measurements in LatencyGym:
https://github.com/spatialos/UnrealGDKTestGyms/pull/47
@m-samiec @improbable-danny
=> [UNR-2763] Add avg/min/max ping measurements

CHANGELOG.md
* Removes 0.6.5 from the CHANGELOG as we decided not to ship that patch release.
* Adds a speculative ship date for 0.8.1-preview.
* Clarifies CN region settings.
=> Remove 0.6.5 from CHANGELOG

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKServices/Private/Interop/Connection/EditorWorkerController.cpp, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp, SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp, SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp, SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h, SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h, SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesModule.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerTest.cpp
-------
This aids in fixing an issue where the editor has not yet fully opened but we make a call to spatial that does not call the environment arg correctly for China.
=> [UNR-2964][MS] Ensure spatial commands are run with correct environment arg.

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/Schema/StandardLibrary.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h
A player leaving a deployment can leave its actor behind on the server. It happens because a player leaving is detected through an update to the Heartbeat component. This update could be skipped because the network stack has several background threads, which are not necessarily flushed in case of disconnection.
Another way to detect a disconnection would be to catch the disappearance of the entity associated to a client worker.
Several things need to happen : 
1) Server worker need to be interested in worker system entities.
2) Worker components need to be read.
3) USpatialNetConnection need to be associated to their corresponding system entity (this is loosely done by matching workerId)
(also include a driveby fix for cleanup code which asks for object references after the world has been …
=> [UNR-1954] Use System entity for connection cleanup

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/Components/ActorInterestComponent.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/Components/ActorInterestComponent.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialInterestConstraints.h, SpatialGDK/Source/SpatialGDK/Public/Schema/Interest.h, SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h, SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
-------
Adds a result type to user interest queries. The result type is for client non auth actors because we assume clients only want to know about actors
Also refactors a little bit.
?
lots of little in code comments
@m-samiec @MatthewSandfordImprobable
=> user query Result type additions and some refactoring +comments

CHANGELOG.md, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp, SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp, SpatialGDK/Source/SpatialGDKServices/Public/SSpatialOutputLog.h
-------
PR adds the ability to read runtime errors that come from the Spatial Service.
We parse the error and do some minor formatting to present it to the user in the Spatial Output. 
Before these errors would not be printed to the `launch.log` or displayed to the user and so the user would need tribal knowledge of how to get their Spatial Service logs. The user would simply see `Local deployment startup failed! Deployment status: STOPPED` with no additional information.
What is shown to the user in the case of startup failure:
Feature: The Spatial Output Log window now …
=> UNR-3000 Spatial Output shows startup errors

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
NCD interest has been vetted, and is now enabled by default.
Feature: The new Net Cull Distance client interest model is now enabled by default.
@improbable-danny @MatthewSandfordImprobable
=> UNR-2813 - Default enable ncd interest

SpatialGDK/Source/SpatialGDKEditor/Private/EditorExtension/GridLBStrategyEditorExtension.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/EditorExtension/GridLBStrategyEditorExtension.h, SpatialGDK/Source/SpatialGDKEditor/Private/EditorExtension/LBStrategyEditorExtension.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/EditorExtension/LBStrategyEditorExtension.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
We want to be able to launch a local deployment with the right amount of workers to satisfy the load balancing strategy's requirements. While we could add virtual methods to the load balancing strategy to do that, we would need to add another structure to bridge the gap between editor-only structs.
This could happen eventually, but this part of the GDK is still in flux at the moment. So the "virtual" part of getting the right amount of workers for the editor is done in an editor only extension. This is just register a class instance against a strategy's UClass.
It does not prevent us from adding these facilities to the strategy itself eventually, but it keeps both notions separated for the time being.
=> [UNR-2809] Add editor extension to get the number of workers to launch from a load balancing strategy

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Shadow data could be uninitialised when resolving objects, add call to initialise if required.
Validated by internal teams
@mironec @yumnuska
=> Fixed crash caused by uninitialised shadow data

SpatialGDK/Source/SpatialGDKEditor/Private/EditorExtension/LBStrategyEditorExtension.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/EditorExtension/LBStrategyEditorExtension.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKDefaultLaunchConfigGenerator.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.cpp
When starting a local deployment, the current opened map's load balancing strategy will be checked to create the right amount of workers, instead of having to change the editor's settings as it is now.
Along this change, the launch configuration will be saved with the map's name, as well as a version for the cloud, which will make it more convenient to have the right configuration out of the box.
Another PR will follow up to have a cleaner user experience around launch co,figurations.
TODO : How to check the the current running deployment has to be restarted ?
TODO
=> [UNR-2809] Use map's load balancing strategy when starting local deployment

SpatialGDK/Extras/schema/component_presence.schema, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialLoadBalanceEnforcer.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialLoadBalanceEnforcer.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/Schema/ComponentPresence.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDK/Public/Utils/EntityFactory.h, SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalanceEnforcer/SpatialLoadBalanceEnforcerTest.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
This PR enables the use of dynamic components in a zoned environment.
This GIF shows a new gym where the Character EntityACL is authoritative on a different worker to the rest of the simulated components. Pressing R adds a new ActorComponent to the character, which is visible in the component list (and also in the ComponentPresence list, and then in the write ACL mapping, resulting in the authority assignment). Pressing T removes the component, causing the data to unset in the Inspector (however the write ACL assignment intentionally remains).
The dynamic components GDK implementation relies on the EntityACL being authoritative on the game server that performs the SpatialSender::GainAuthorityThenAddComponent call. Most of the time, this won’t be true in zoned deployments, because the …
=> [UNR-2859] Multi-worker dynamic components using component presence

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
Support using a custom locator host in the URL.
Previously, URLs that use the locator flow must start with `locator.improbable.io`, with the option to overwrite the locator host as a cmd line arg. This change allows for custom locator hosts by having any URL with the `?customLocator` option go through the Locator login flow and using the URL's host as the locator host. This makes it possible to have a dynamic locator host that might not yet be known at startup and cannot be passed as a command line arg.
Have considered the alternative of adding a `?locatorHost=` URL option but think that's less preferable for the following reasons:
* The URL then needs to be escaped by the user
* Seems counterintuitive that the URL starts with a different host, e.g. …
=> UNR-2811 Custom Locator URL

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Early exit processing a server RPC if the Actor role has changed to SimulatedProxy (as would be the case if we were migrating the Actor to another work via updating the AuthorityIntent). This previously resulted in engine code spamming errors every time you cross a boundary for the RPCs that it attempts to process. Furthermore, I think it just fails to process the RPC but may still update the endpoint RPC count meaning those RPCs don't get validly processed by the next worker either. 
Now, exiting early should prevent the errors, and doesn't update the count, meaning these RPCs should be processed by the worker receiving authority.
Before:
After:
=> Early exit processing a server RPC if the Actor role has changed to SimulatedProxy

SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/WorkerViewTest.cpp, SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs, SpatialGDK/Source/SpatialGDKEditor/SpatialGDKEditor.Build.cs, SpatialGDK/Source/SpatialGDKEditorCommandlet/SpatialGDKEditorCommandlet.Build.cs, SpatialGDK/Source/SpatialGDKEditorToolbar/SpatialGDKEditorToolbar.Build.cs, SpatialGDK/Source/SpatialGDKServices/SpatialGDKServices.Build.cs, SpatialGDK/Source/SpatialGDKTests/SpatialGDKTests.Build.cs
In order to have the same build settings between project and engines plugins, we set the bLegacyPublicIncludePaths to false.
This PR's CI should be broken right now.
=> Disable legacy include

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Currently, we preemptively set local role to SimulatedProxy when sending an AuthorityIntent update since we know we're going to lose authority imminently. However, we don't trigger the OnAuthorityLost callback. Instead, this would be triggered when SpatialOS eventually sends us the op, however, having a state where we've changed from Role_Authority to SimulatedProxy but not yet triggered OnAuthorityLost seems bad.
There's an additional change to the code where we receive the AuthorityLost op to make sure we don't call OnAuthorityLost twice.
=> Call OnAuthorityLost callback when sending auth intent

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
This change sets the trace prefix (which I will probably be renaming to "trace identifier" in the future) to the `tracePrefix` command line arg (if it has been passed in). I'm merging this into your branch because I'm testing it with your branch as well.
=> Add tracePrefix command line argument

ci/gdk_build.template.steps.yaml, ci/setup-build-test-gdk.ps1
We have renamed this var to correctly describe what it contains.
We had to change how UnrealEngine is symlinked in ExampleProject and TestGyms ci pipelines as the differences in symlink path caused build issues.
These have been resolved in https://github.com/spatialos/UnrealGDKExampleProject/pull/135 and https://github.com/improbable/TestGymBuildKite/pull/52
To match these PRs we renamed the var.
@m-samiec @mironec
=> Rename unreal_path to unreal_engine_symlink_dir for consistency

SpatialGDK/Source/SpatialGDKServices/Private/Interop/Connection/EditorWorkerController.cpp, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp, SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp, SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp, SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h
Cleaning up SpatialCommandUtils so that calls to it only contain parameters. Essentially all string manipulation is handled inside SpatialCommandUtils.
Tested local deployment which tests StartSpatialService and StopSpatialService. 
Opening editor tests SpatialVersion.
Modified files in PROJECT/spatial/worker whilst editor was open to test BuildWorkerConfig.
Would like to know how to test LocalWorkerReplace.
=> [UNR-3010][MS] Modifying SpatialCommandUtils so that it better wraps up spatial cli commands.

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
- Remove `Expose local runtime` in GDK settings.
- Remove `Exposed local runtime IP address` in GDK settings.
- In place we will use new settings in GeneralProjectSettings to decide whether we should expose local deployment to outside.  
The above picture is the screenshot for SpatialOS mobile launch flow, when user check `Connect to  local deployment` and input the correct  local `Deployment IP`, the local deployment started by click `Start` button will listen on the specified IP address, or else it will only accept local connection.
=> UNR-3199 Remove obsolete code about exposing local deployment IP.

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialStatics.h
Added the option to either get an int64 entity ID from an actor, or a convenience method to get an FString directly.
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for reviewing …
=> Split up actor entity ID functions

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
This fixes a really infrequent bug where the player controller and state migrate server before the character does. 
When gaining authority over the player state's position we do this:
```
if (const APlayerState* PlayerState = Cast<APlayerState>(Actor))
{
// The following check will return false on non-authoritative servers if the Pawn hasn't been received yet.
if (APawn* PawnFromPlayerState = PlayerState->GetPawn())
{
if (PawnFromPlayerState->IsPlayerControlled() && PawnFromPlayerState->HasAuthority())
{
PawnFromPlayerState->RemoteRole = ROLE_AutonomousProxy;
}
}
}
```
This leaves the character Actor on the server that _will_ gain auth in a state where the role is simulated proxy and remote role is autonomous proxy.
This hits a check when trying to replicate the player controller which …
=> Avoid crash trying to update non-auth pawn

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
MW changes and requests -
Return slightly eariler in actor receive code, to prevent unnecessary channel creation.
Made USpatialMetrics::WorkerMetricsRecieved static.
Feature: USpatialMetrics::WorkerMetricsRecieved was made static.
@joshuahuburn @mironec
=> Ported mw changes and requests

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
Discovered in UNR-3230 - External process connections were not working. 
Root cause is configuring the receptionist with an empty hostname if parsing commandline args did not find any hostname.
Correct behaviour is to use the default receptionist IP specified in user settings.
This PR fixes this.
@MatthewSandfordImprobable @m-samiec
=> [UNR-3230] Fix external process connections 

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Reverted https://github.com/spatialos/UnrealGDK/pull/1961 to allow more time to coordinate with customers before removing the "Expose runtime IP" setting.
Made the value in the general settings (that you can set in the Launch dropdown) override the value in SpatialGDKEditorSettings.
Tested manually by changing the settings and restarting the local deployment.
@jessicafalk @raymonwang
=> Revert #1961 + Override exposed runtime IP

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLatencyTracer.h
This PR is is one of four related ones (from major to minor):
* [NFR Framework](https://github.com/improbable/nfr-benchmark-pipeline/pull/116)
* [UnrealGDK](https://github.com/spatialos/UnrealGDK/pull/1975)
* [TestGymBuildkite](https://github.com/improbable/TestGymBuildKite/pull/57)
* [UnrealGDKTestGyms](https://github.com/spatialos/UnrealGDKTestGyms/pull/68)
These PRs implement/accommodate two changes to NFR latency testing:
**New required "trace descriptions" parameter**
Users now have to supply "trace descriptions". The framework will now only include traces whose root span names include one of the user-cupplied trace descriptions. This gives users more control over what exact interactions they want to log.
**Span name format change**
The format of span names has been updated so that …
=> Feature/GV-329 New NFR parameter and new span name format

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/RPCServiceTest.cpp
Shadowing variables causes issues when building for Android using NDK 14. This fixes it. 
Tested it by building Android successfully using NDK 14.
=> UNR-3252: Remove shadowing variables

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp
This fixes the issue where we generate a dev auth token sometimes fails due to having more than 2 lines. The last line always contains the json response with the token, so we change the split to search from the end to definitely get the last line.
=> UNR-3244: Fixing dev auth token generation

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
If the server stops receiving heartbeats from the client, it close the client's connection and delete the PlayerController and all associated Actors. However the client could still be connected to SpatialOS when this happens. In this case, we should notify the client of a network failure and allow the developer to hand the fail condition.
Test locally and on Android
=> Call BroadcastNetworkFailure when the PlayerController gets deleted by the server.

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
Ensuring we always have a runtime version string when launching a deployment. Previously using an empty runtime version would result in a vague error.
Also changed up how the string is retrieved for the deployment options. The value can be empty which reflects the settings in editor settings. If "Use GDK Pinned version" is enable the string will display the pinned version.
=> Ensuring empty runtime versions are not used when deploying.

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Removing RemoveComponentOps that have already been queued that have the same entityId and componentId as an incoming AddComponentOp. 
This fixes an issue where a component was not being added correctly. This is due to the fact that we immediately add a component to the view upon receiving an add component op but queue a remove component op. In the case you receive RemoveComponent -> AddComponent the ops will be processed in the reverse order. 
Tested in test gyms using multiple ownership gym.
@improbable-valentyn  @m-samiec
=> Remove and Add component ops processed in the wrong order.

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Removing an addition that was recently made in this PR https://github.com/spatialos/UnrealGDK/pull/1762 
We don't want to set the channel authority this early (and leave it at the false defaults), because it means when we're applying component data in `ApplyComponentDataOnActorCreation` we won't swap the role and remote role inside `ComponentReader::ApplySchemaObject`. This required the role to be explicitly set before BeginPlay was called.
We can rely on the authority being set correctly after the entity is checked out when we process the authority op inside `HandleActorAuthority`
Bugfix to a recent change - no release note
Ran test gyms, and resumed from snapshots.
@mironec @improbable-valentyn
=> Don't prematurely set channel authority on entity checkout

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Reverts spatialos/UnrealGDK#1957
This breaks server travel
=> Revert "Call BroadcastNetworkFailure when the PlayerController gets deleted by the server."

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
This error appears if you do not have SimPlayers built on your machine. This does not necessarily mean that deploying a SimPlayers deployment would fail. You might be using an uploaded assembly the does have SimPlayers and you just locally deleted you zipped SimPlayers folder.
Old:
New:
=> [UNR-3313][MS] Giving users the option to cancel SimPlayer deployments if built Simplayers can not be found.

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
https://improbableio.atlassian.net/browse/UNR-1349
Unreal names that begin with a leading digit are now prefixed with `ZZ` when being converted to a schema name to make them valid.
Also fixed various by-value `FString` parameters that should be `const&`.
Created a new blueprint actor with a leading digit in its name and generated schema. Schema generation is now successful.
release note
=> Schema names for unreal names with leading digits are prepended with ZZ

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h
After a server travel on the client the GSM singleton map contain garbage data. This was causing checks to fire. We now clear the GSM singleton map when we are about to load a map.
Will cherry pick this into the RC.
=> [UNR-3230][MS] Fixing assert on server travel by clearing client GSM singleton map.

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/GridBasedLBStrategy.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/GridBasedLBStrategyTest.cpp
- Add API to UAbstractLBStrategy to indicate whether a strategy requires handover data replication.
- Implement said interface for grid based loadbalancing.
- Force handover property replication when required by the strategy if load balancing is enabled.
- Switch bEnableHandover off by default.
Tested in handover gym with and without load balancing, with and without the handover setting enabled.
@m-samiec
=> Force-enable handover properties when required for load balancing.

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
It's easy to connect to a wrong deployment using the dev auth flow without specifying deployment name, so this will log the name of the deployment that was chosen so it's easier to debug.
@jessicafalk @joshuahuburn
=> [UNR-3318] Log deployment name when using dev auth flow

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h, SpatialGDK/Source/SpatialGDKServices/Private/SpatialGDKServicesModule.cpp, SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h, SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesModule.h
Make project name field editable in cloud deployment window.
After change the content in the text editor, you can check the value of key `name` in `Samples\UnrealGDKExampleProject\spatial\spatialos.json` and see the new project name.
Users can modify their project name in unreal editor much easier and it is not necessary modify it through command line any more.
=> UNR-3304 Cloud Deployment Window: make project name field editable.

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
Actors belonging to the same ownership hierarchy depends on each other to work. This change makes sure that they all send a transition request together.
They could arrive at different time on their destination though, and could try to transition to an incorrect position. A transition backoff period has been added to mitigate this issue.
Edge cases remains related to snapshot or worker crash, and would need actor sets to be properly handled.
TODO
TODO : Teleporting Gym.
=> [UNR-2987] Actor hierarchy migration

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h
Added OnPlayerSpawnFailed delegate to SpatialGameInstance;
Made OnConnected and OnConnectionFailed BlueprintAssignable
Started a local deployment and deleted the SpatialSpawner to force the spawn request to fail.
release note
=> Added OnPlayerSpawnFailed delegate to SpatialGameInstance

SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h
[Ticket](https://improbableio.atlassian.net/browse/UNR-2770)
This actually fixes an issue that a [previous PR](https://github.com/spatialos/UnrealGDK/pull/1946) claimed to. Actors spawned an immediately locked did not respect locks in the sense that the CreateEntity would have the AuthorityIntent component being sent with the strategized virtual worker (as well as the SpatialDebugging component).
Now, we check for a lock while constructing the CreateEntity request, and if set, use the local virtual worker id instead of the strategized one (and this is also applied to the SpatialDebugging component).
=> [UNR-2770] Actually enable locking immediate after spawning

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Original ticket: https://improbableio.atlassian.net/browse/UNR-3147
As part of enabling dynamic components in the worker SDK, we will get additional Add/RemoveComponent ops when the worker SDK receives delegate/undelegate ops from the runtime. We need to be more robust handling these. Specifically in how we handle double RemoveComponent ops for the UnrealMetadata component because this results in double-attempted Actor deletion.
=> Handle duplicate add remove component ops a bit better

SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
Warnings are produced due to lack of IWYU on Engine.h
=> [UNR-3326] EntityFactory include warning fix

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp
Altered latency tracer to only register stdout if we intend to pipe it to unreal output.
This was done because sim clients also capture *all* stdout, not just what unreal outputs, so they were always capturing the tracer output, which was often many MB. Can still be turned on by altering the `LogSpatialLatencyTracing` category, but must be done before the call to `SpatialLatencyTracer::RegisterProject`
Internal tool, not externally documented.
@ImprobableVlad @improbable-danny
=> Disable stdout register unless we're actually outputting

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorLayoutDetails.h
Add ability to remove the UE4CommandLine.txt from a device.
TODO: Update CHANGELOG.md
I deleted the file from Android device and used ADB shell ls to confirm it was gone.
IOS I deleted the file from the bundle.. but I haven't validated it's removed from the bundle, only that the command did not complain.
STRONGLY SUGGESTED: Create a cloud deployment and dev-auth token, then push the command line with dev auth token to the device (Android and iOS) then connect successfully to the cloud deployment, then remove the command line (Android and iOS) using the remove buttons and confirm it is no longer possible to connect to the cloud deployment.
TODO: Update documentation
@improbable-valentyn @jessicafalk @raymonwang
=> UNR-3295 Add Remove UE4CommandLine.txt from Device

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h, SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp, SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h
* Add Spatial Networking checkbox in 'start' toolbar button dropdown menu.
* Add a dropdown for selecting which connection flow: Native, Local, Cloud.
The Connection field should show which one is currently selected.
If a local deployment is running, disable changing the flow.
* Add a Local Deployment IP field which is editable. 
* Add a Cloud Deployment Name field which is editable.
* If Local is selected: 
Disable “Cloud Deployment Name”.
Take the Local Deployment IP as the runtime IP when starting the deployment.
* If Cloud is selected: 
Disable “Local Deployment IP”
Prepare a dev auth token. 
* If Native is selected: disable both fields
* Add a field / link to the Editor settings
New UI looks like the following picture:
Todo: update the changelog file.
=> UNR-3290 Create dropdown for choosing connection flow in the Start toolbar button

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
When asynchronously loading classes, it could happen that we used it too early, when it was still being loaded in the background.
This PR adds a check, through GetAsyncLoadingPercentage, to avoid this situation.
The bug is a data race on async loading, and the precise set of circumstances when it happens is still unclear. So the test will likely be empirical.
Reproducing it involves starting a fresh client, and having it load replicated actors's classes on the fly (the map should contains soft references to actors to spawn after a while).
Tested in-game, before and after, checked that there were no crashes, and that the situation we are testing for (package being registered in the async loading thread) actually happens.
=> [UNR-3320] Avoid using packages being async loaded

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h
According to our documentation, we need to right now pass in the dev auth token manually for the mobile previewer flow.
In this PR, we changed this. If we connect to a cloud deployment, we automatically pass dev auth token in as a command line arg.
- Start a cloud deployment first.
- Select `connect to cloud deployment` in new Start drop down menu. This will prepare a dev auth token automatically.
- Click `Mobile Preview(PIE)` to start a client, it will use the above dev auth token to connect to cloud deployment.
TODO: Need to update document.
=> UNR-3300 Automatically pass in dev auth token when using mobile PIE flow to connect to spatial cloud deployment.(GDK part)

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
If we are not in local deployment mode disable starting a local deployment.
TBD
I started the PIE session when in local deployment and not in local deployment
Testing PIE sessions in local deployment, cloud deployment and no auto startup modes.
TBD
@raymonwang @improbable-valentyn @jessicafalk
=> Unbind launch delegate when we're not in local deployment mode.

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
================================================
Implement ShouldConnectToLocalDeployment function.
Launched client on android device can connect to the specified cloud deployment when user choose `connect to cloud deployment` and input target deployment name using new UI.
- Choose `connect to cloud deployment` like the following picture.
- Click `Launch` button to start a client in android device.
- The client should be able to connect to the cloud deployment.
- The flow also works for local deployment flow.
TODO.
=> UNR-3294 Hook up cloud connection flow in new UI(GDK part)

.buildkite/premerge.steps.yaml, ci/generate-and-upload-build-steps.sh
EngineNetTest would like to call our CI, but our builds are too big, this makes them smaller for the EngineNetTest.
=> Allow smaller master builds in CI

SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
Map name is being set in the GSM with the PIE prefix and this is causing mobile devices to fail when connecting to the local deployment.
@jessicafalk @joshuahuburn
=> Remove PIE prefix when setting DeploymentMap in GSM

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp
Easier to debug than `Log in via locator failed: gRPC error INVALID_ARGUMENT: could not decode LoginToken` (this is what would previously be printed after trying to connect to locator with an empty login token)
=> [UNR-3411] Print a better error and don't attempt to connect if dev auth flow deployment not found

Setup.bat
If you run `Setup.bat --mobile` or `--china`, it should automatically pass those flags when run from a git hook.
@jessicafalk @joshuahuburn
=> Save arguments passed to Setup.bat when creating git hooks

SpatialGDK/Source/SpatialGDK/Public/Tests/TestDefinitions.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/Misc/SpatialActivationFlagsTest.cpp, ci/setup-build-test-gdk.ps1
Adds the ability to specify slower/more flaky GDK tests with the macros `GDK_SLOW_TEST` and `GDK_SLOW_COMPLEX_TEST`. These tests will run in the nightly, rather than the premerge.
N/A
Ran premerge and slow networking tests in CI.
N/A
@aleximprobable
=> Slow GDK tests will only run nightly

SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
Stop proposing default_launch_config.json as the default launch config for cloud deployment. Instead, the field stays blank, and the added buttons, "Generate from current map" and "Open launch config editor" propose a simple way to get good defaults.
There was some mixups when getting the bManualWorkerConnection's flag value. As we are forcing the value of this flag to false when launching PIE, I changed the default value in the settings to false, and I respect these settings when generating the configuration file for the cloud. That way we have good defaults for the cloud, and the user can persist its own preference instead of us forcing it.
=> [UNR-3078] Launch config files fixups

CHANGELOG.md, RequireSetup, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCloudLauncher.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
Added a new field to specify deployment tags. This is passed as an additional argument to `DeploymentLauncher`.
Original author: @jayprobable 
Original PR: https://github.com/spatialos/UnrealGDK/pull/1931 (this was a bigger PR but I figured this bit can be separated for easier review)
@MatthewSandfordImprobable @ImprobableNic
=> Add deployment tags field to Cloud Deployment window

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/RepLayoutUtils.h
`RepLayoutUtils::GetClassRPCFunctions` ignored interfaces when iterating over the class field.
Added an automated test: https://github.com/improbable/UnrealGDKEngineNetTest/pull/30
=> RPCs can now be called on UINTERFACE

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarStyle.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
Swap the Cloud "Deploy" button action with the Spatial Launch so that quick deploy is on spatial launch and Cloud "Deploy" is the original button.
=> UNR-3421 Swap the toolbar button actions for deployment

SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKSimulatedPlayerDeployment.h
- Set the two interface `IsAssemblyNameValid` and `IsDeploymentNameValid` in SpatialGDKEditorSettings.h to public section.
- Before we save assembly name and deployment name inputted by users into INI file, do some regex checking.
=> UNR-3425 Add regex checking on text committed for deployment and assembly name.

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
bring the settings window to front if already have a cloud deployment settings window and click the button again.
fix the bug of UNR-2570.
REQUIRED: check the windows' pointer if valid.
bring it to the front if valid. and open a new window if not.
bind event on the window destroyed so that clear CloudDeploymentSettingsWindowPtr.
rename SimulatedPlayerDeploymentWindowPtr to CloudDeploymentSettingsWindowPtr.
=> URN-2570 Make the Cloud Deployment Settings Window unique

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
When launching on device with local deployment connection flow selected, the local deployment will need a server connected to it in order for the device to start gameplay. By default, only the dedicated server will be started without the PIE clients, but an option is added to the GDK to also start PIE clients.
Engine PR: https://github.com/improbableio/UnrealEngine/pull/464
=> Add a setting to auto start PIE clients when launching on device

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Notification toasts about Launching a cloud deployment were missing.
This was because no start notification was issued, it is necessary to create a start notification to generate a valid notification pointer.
Added a start notification when launching a cloud deployment, now the success or failure notification will also display and the notification stays alive for the duration of the launch deployment task.
=> Display the Notification about cloud deployment.

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDevAuthTokenGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKDevAuthTokenGenerator.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditor.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
This code encapsulates the Dev Auth Generation into a type that will ensure that it is not performed in overlapping fashion and provides editor notifications while being run in an asynchronous fashion.
Per feedback from @improbable-valentyn ...
This occurs when switching to a cloud deployment via the deployment type radio buttons.
This code does not address generating a dev auth token when pushing the button in the settings window, as perhaps that should be "modal"/blocking...
=> UNR-3420 - Dev Auth Token Generation performed Asynchronously

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Since "Cloud" button now launches the cloud deployment if it's configured, the checkboxes to enable building client and simulated player workers should be in the corresponding dropdown.
Also, we should grey out the button while the assembly is building.
=> Move build client and simplayer checkboxes

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDevAuthTokenGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCommandLineArgsManager.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorCommandLineArgsManager.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorLayoutDetails.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorModule.h, SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp, SpatialGDK/Source/SpatialGDKServices/Public/SpatialCommandUtils.h
Automatically remove UE4Commandline.txt when the launcher session ended in Android device if UnrealEngine version >= 4.24
Automatically remove UE4CommandLine.txt when the launch session ended in Android device if UnrealEngine version >= 4.24.
Because only after 4.24 have events to delegated so that doesn't change UnrealEngine sourcecode anymore.
Automatically remove the file after click 'Cancel' Button or exit App on Android device.
=> UNR-3408 Automatically remove UE4Commandline.txt when the launcher session ended.

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
With the new workflow changes we've added a button to launch a cloud deployment when the "Cloud Deployment" workflow is supported. Unfortunately on Mac launching a cloud deployment isn't supported. For now, grey the button, in the future we can support this, tracked in UNR-3496.
=> UNR-3390 - On Mac do not support launch cloud deployment

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
If generate schema or snapshot fails display a toast and quit cloud deployment process.
Tested by making the scheme database readonly.
=> UNR-3481 Failed schema generation aborts quick deploy

SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp
In SpatialLoadBalanceEnforcer, the worker authoritative over the ACL component (the acl-auth worker) will not process an ACL assignment request if the NetOwningClientWorker component is not present. This ACL assignment process is needed so that the worker authoritative over the rest of the entity (the sim-auth worker) becomes authoritative over the Unreal metadata component (and some other components).
However, the acl-auth worker doesn't necessarily check out the NetOwningClientWorker. It checks it out either when:
1. acl-auth worker == sim-auth worker, because the sim-auth worker already has authority over the NetOwningClientWorker
2. It's run on Kraken, since Kraken has a full initial checkout if you become authoritative over part of the entity.
So if it's run on Squid with multiple …
=> Add NetOwningClient worker to enforcer worker query

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/Utils/EntityPool.h
[Ticket](https://improbableio.atlassian.net/browse/UNR-3284)
Given the nature of commands, it's possible that we end up having two requests to spawn a server worker entity effectively in flight at once from the same worker. Reserving an entity ID for the server worker ID ahead of time will mean this can't happen.
=> Reserve server worker entity

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Fixes an `ensure` when using an actor marked `PendingKillPending` is used to send an RPC, which would (without this change) cause a new channel to be created in this callchain:
```
Server!FDebug::OptionallyLogFormattedEnsureMessageReturningFalseImpl(bool, char const*, char const*, int, char16_t const*, ...)(493) 
Server!FNetworkObjectList::FindOrAdd(AActor*, UNetDriver*, bool*)::$_39::operator()() const(64) 
Server!FNetworkObjectList::FindOrAdd(AActor*, UNetDriver*, bool*)(64) 
Server!FNetworkObjectList::MarkActive(AActor*, UNetConnection*, UNetDriver*)(216) 
Server!UActorChannel::SetChannelActor(AActor*, ESetChannelActorFlags)(2171) 
Server!USpatialActorChannel::SetChannelActor(AActor*, ESetChannelActorFlags)(1058) 
Server!USpatialNetDriver::CreateSpatialActorChannel(AActor*)(2335) …
```
=> Prevent new actor channels for dying actors

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
There is no dependency between the engine project and the automation tool. So when checking out the new engine version that is supposed to add the automation tool command we use to run schema generation, the user still has the old version. Then, when launching the schema generation from the editor, the command is not found and the generation fails.
With this modification, we check that the AutomationTool has the command we want to run, and asks the user to rebuild them if the command is not found.
It seems to be the cheapest and quickest fix since adding the dependency bewteen the projects would require modifying the Unreal Build Tool, regenerating projects (which users will likely not do), and recompile the engine (since the build tool has been updated).
=> [UNR-3503] Check that AutomationTool is up to date when running Schema generation from the editor

ci/generate-and-upload-build-steps.sh
Linux was broken, let's just do linux builds as a premerge gate.
N/A
With CI.
N/A
=> Re-enable linux build for the EngineNetTest repo

SpatialGDK/Source/SpatialGDKServices/Private/SpatialCommandUtils.cpp
Parse the "error" text field out of the returned json when spatial CLI reports a failure generating a dev auth token. This message is more user friendly than the entire json text.
Tested this by changing my project name to something invalid and generating dev auth tokens from both the settings button and by select Use Cloud Deployment from the workflow dropdown menu.
=> UNR-3485 Friendly dev auth error message

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Win64 was the default platform for CookAndGenerateSchema, but that did not work for other Editor platforms.
This setting was added to be able to specify Linux as a build platforms for schema generation, while providing a sensible defaults for the ones who did not build with Linux support.
The change makes automatic platform selection when no setting is set, trying to use Linux if it is available, and falling back to the Editor's platform otherwise.
=> [UNR-3532] Better platform selection for cook and generate schema

SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarStyle.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
'No automatic connection' flow was first added to support the use case of custom authentication flow. However, we don't have a reference implementation of this use case that we can test this flow against. Additionally, there is already an existing way to disable automatic connection by running in offline mode (via advanced networking settings).
So instead of supporting an incomplete feature in this release, we should first implement a reference use case and add this back when we can properly test it.
I also added a ticket to add it back together with the reference use case: https://improbableio.atlassian.net/browse/UNR-3583
@jessicafalk @jayprobable
=> Remove 'No automatic connection' option

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKSimulatedPlayerDeployment.cpp
Whenever the project name is changed through the Cloud Deployment window, automatically generate a new dev auth token.
When changing the project name via the `Cloud Deployment` dialog the development authentication token will automatically be regenerated.
I ran the editor and changed the project name through the Cloud Deployment dialog, toasts for dev auth generation popped-up, and I saw the token value in the settings was different.
Release note
=> UNR-3431 Regenerate Dev Auth Token when Project Name changes

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LayeredLBStrategy.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/LayerInfo.h, SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
This contains 3 changes:
- A few code cleanup comments left over from the main UNR-3095 code review.
- Removing the per-Layer Locking Policy which was added originally but never implemented and now just clutters the UI.
- Actually adding something to the CHANGELOG for the original UNR-3095 PR.
- Settings for Offloading and Load Balancing have been combined and moved from the Editor and Runtime settings to instead be per map in the SpatialWorldSettings. For a detailed explanation please see the Load Balancing documentation.
Ran the offloading test gym.
If your change will take a long time to review, you can name at most two primary …
=> Cleanup comments, CHANGELOG, and Locking Policy from WorldSettings.

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LayeredLBStrategy.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LayeredLBStrategy.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialDebugger.h
This fixes the SpatialDebugger region display. This is a short term solution. The long term solution would be to allow the WorldSettings to specify which layer should be displayed, but in the short term, most developers will want to display the default layer, so that's what this defaults to.
N/A
Run the OffloadingGym in GDKTestGyms and verify that you see 4 colored quadrants, but that the offloaded cube is displayed as a different color.
=> Added an accessor to the LayeredLB to get the Default strategy.

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/CloudDeploymentConfiguration.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditor.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKCloudDeploymentConfiguration.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKCloudDeploymentConfiguration.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
Updated some names after checking with the tech writers:
- Configure instead of Deploy for the button that opens the Cloud Deployment Window
- Cloud Deployment Window is now called Cloud Deployment Configuration Window
- Start deployment instead of Launch deployment because Unreal also uses the term Launch for a installing and starting a game on a different device
- Renamed the `SimulatedPlayerDeployment` files and references to `CloudDeploymentConfiguration`
- Update the Changelog
I haven't updated the DeploymentLauncher, though that might be fine for now. We won't get rid of the word Launch completely, because we still have for example Launch Configurations
=> Update some of the naming in the Editor

SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
The default value for ManualWorkerConnectionOnly is set in FWorkerTypeLaunchSection, but then is overridden when a FSpatialLaunchConfigDescription is created. This removes the override.
The side effect is that by default the settings set ManualWorkerConnection to false, as intended.
How is this documented (for example: release note, upgrade guide, …
=> Do not override default settings for manual connection

SpatialGDK/Source/SpatialGDKEditor/Private/CloudDeploymentConfiguration.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/CloudDeploymentConfiguration.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKCloudDeploymentConfiguration.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKCloudDeploymentConfiguration.h
Starting a cloud deployment can fail after build and upload succeeds, so add a checkbox to skip the build and upload stage.
@jessicafalk @jayprobable
=> Add a checkbox to build and upload assembly

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorLayoutDetails.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditor.h, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorLayoutDetails.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKCloudDeploymentConfiguration.cpp
Add the ability to update the SpatialOS project name via the settings dialog. The primary purpose is to support updating this value on Mac which will not display the "Cloud Deployment" dialog since it is not possible to compile a linux serverworker on Mac currently.
The SpatialOS project name can now be modified via the **Spatial Editor Settings**
I ran the editor and modified the value in the Cloud Deployment and Settings dialogs to confirm the changes were persisted and displayed properly by both.
QA: Edit the project name via the editor then review the spatial.json file to see what project name is in the json.
release note
=> UNR-3555 Enable editing SpatialOS project name from Settings

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Update inspector toolbar link to inspector v2 as new runtime (going default in 0.10) doesn't support inspector v1.
added
Manual local test 
Being handled in https://improbableio.atlassian.net/browse/DOC-1543
=> UNR-2611 - Update default inspector in toolbar to inspector v2

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Remove legacy non-result type functionality.
https://improbableio.atlassian.net/browse/UNR-3552
Running with result types (previously default enabled) is now mandatory. The Runtime setting `bEnableResultTypes` has been removed to reflect this.
@samiwh @alastairdglennie
=> Remove legacy non-result type functionality

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
NWX has run into two problems with the startup ordering and an IsReady check in the LayeredLBStrategy. This fixes both and adds a bit more debugging info.
1. There was a race where the SpatialConnectionManager has made the connection to Spatial but the LoadBalancing system isn't ready yet. If a map loads before the LBStrategy is ready, it could start processing the network initialized actors early. The fix for that is in SpatialGameInstance.
2. NWX is seeing issues with LevelActors being spawned before the NetDriver is ready (specifically before the LBStrategy is ready). The fix for this is in SpatialNetDriver.
REQUIRED: Add a release note to the `##Unreleased` section of CHANGELOG.md. You can find guidance for writing useful release notes …
=> Cleanup race conditions in initialization code

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Set deployment to connect to the one being started as soon as 'Start Deployment' is clicked. This aims to improve the user experience together with @jessicafalk's PR https://github.com/spatialos/UnrealGDK/pull/2206, where clicking on Play or Launch will first check whether the deployment is running before attempting to start a session.
=> Set deployment to connect as soon as 'Start deployment' is clicked

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Make it so you can't attempt to start another deployment while DeploymentLauncher is running. This is especially noticeable when `Build and Upload Assembly` is unchecked, so 'Start Deployment' doesn't get greyed out.
@jessicafalk @jayprobable
=> Disable 'Start Deployment' while DeploymentLauncher is running

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp
Only new deployment name is different with the previous one in cloud deployment window, it will write it in config file and refresh the DEV token.
=> UNR-3635 Cloud deployment configuration window refresh DEV token when it's not necessary.

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKCloudDeploymentConfiguration.cpp
https://github.com/spatialos/UnrealGDK/pull/2204 has removed `CN` from the `ERegionCode` enum values, which can cause an error when upgrading. Instead, we should hide the enum value for now.
```
Error: LoadConfig (/Script/SpatialGDKEditor.Default__SpatialGDKEditorSettings): import failed for PrimaryDeploymentRegionCode in: CN
```
@jayprobable @jessicafalk
=> Prevent enum value error for CN when loading config

SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LayeredLBStrategy.cpp, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LayeredLBStrategy.h
The layer strategies in the LayeredLB were being added to root when put in a local map instead of using a UProperty for the map. This meant that things weren't being cleaned at the right time.
N/A
Run the offloading test gym. Start and restart the PiE instance without stopping the deployment. Run in DebugEditor and check that the editor doesn't crash on exit.
N/A
=> Fix layered lb memory management

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LayeredLBStrategy.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialStatics.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/LayeredLBStrategy/LayeredLBStrategyTest.cpp
Remove the bEnableMultiWorker flag from GDKSettings. The SpatialNetDriver will now always create a LayeredLBStrategy, even if it just has one layer with a 1x1 grid. 
Some places where we used to check if bEnabledMultiWorker, we now just always execute. Others, we check for whether there are multiple layers enabled.
One breaking change is that I added a World parameter to SpatialStatics::IsOffloadingEnabled, because we don't know anymore until we've connected to the deployment. 
How did you test these changes prior to …
=> Remove enable multi worker flag in gdk settings

.gitignore, RequireSetup, Setup.bat, Setup.sh, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKServices/Public/SpatialGDKServicesConstants.h
When using the UnrealGDK in China, you need to run the `Setup` script with `--china`. We can use this to indicate to the GDK whether to use the CN services region.
Running `Setup.bat` (or `Setup.sh` or Mac) will create or delete a file `UseChinaServicesRegion` in the plugin directory. On module startup, the GDK will check the existence of that file to set its services region. Changing the services region from the GDK settings will also create or delete the file.
@jayprobable @jessicafalk
=> Create a marker file to indicate services region

RequireSetup, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs
With the latest changes, all deployments need a snapshot. So far our simplayer deployments never specified one, because they connect immediately to a different deployment. 
This fixes it by simply using the same snapshot as the one used in the main deployment.
At some point we may want to look into creating a temporary empty snapshot for sim player deployments, but as the current main deployment snapshot doesn't have much in it, I'm not sure if it's worth doing it right now.
=> Ensure that simplayer deployments have a snapshot

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LayeredLBStrategy.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
This is a temporary fix for the Warning messages we're getting for the SpatialDebugger/MetricsActor/GameplayDebugger actors which are created and can be authoritative on multiple workers. By default, we will turn off any processing in OnActorSpawn. In the full solution (which is too risky for the RC) this processing will be moved into the LBStrategy. 
Run the Offloading Gym and see that there are no Warnings for the SpatialDebugger/MetricsActor/GameplayDebugger being created on the wrong workers.
How is this documented …
=> Add enable multi worker debugging warnings flag

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
When starting a cloud deployment you have the option to generate schema. 
This fails if you don't have generated schema before you start your cloud deployment. because we only try to do an iterative schema scan.
=> [UNR-3684] Show error message dialog if full schema scan is required

SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
We haven't been validating the cloud deployment configuration fields when set in the editor settings. As we don't really need the fields there, we are simply going to hide them and only make them configurable via the cloud deployment configuration window.
=> [UNR-3657] Hide cloud deployment configuration fields in editor settings

SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
Save services region to default config when it's changed as a result of checking the marker file. This is necessary for the config value to apply to other platforms (Linux, Android, iOS), since before it was saved in `Saved\Config\Windows`.
@jayprobable @jessicafalk
=> Save services region to default config

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
Check for world settings null
Fix for https://improbableio.atlassian.net/browse/UNR-3688
Use the repro in https://improbableio.atlassian.net/browse/UNR-3688 or start the offloading benchmark gym with no SpatialWorldSettings.
=> Check for world settings null

SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
Currently, it's only added via an enforcer update using the ComponentPresence list
=> Add UnrealMetadata to ACL

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Stop-gap fix for UNR-3694
Server worker entity isn't given enough time to delete when running locally with squid.
@samiwh @joshuahuburn @mironec
=> Ensure worker entity is cleaned up on shutdown

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKCloudDeploymentConfiguration.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKCloudDeploymentConfiguration.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Replaced the "Generate From Current Map" button  from the "Cloud Deployment Configuration" window by "Automatically Generate Configuration" checkbox that if ticked, generates an up to date configuration from the current map every time a cloud deployment is started. Also, checking the box prevents the user from clicking "Open Launch Configuration editor" and from manually picking the "Launch Config File". 
Below are two images to make the change easier to visualize, the first one shows the menu before the change, the second shows it after the change: 
Added under ##Unreleased .
Only manual testing, verifying that having the checkbox checked provides the stated functionality, and that the conditions for starting a deployment are updated by this addition.  
Documented by the release note. …
=> UNR-3675 Add Auto Generate Launch Configuration Checkbox

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialPlayerSpawner.h
It's conceivable that the worker authoritative over the PlayerSpawner snapshot entity doesn't correctly find PlayerStarts Actors, e.g. if the PlayerSpawner authoritative worker is the wrong layer / has decided to delete PlayerStarts / FindPlayerStart_Implementation doesn't work correctly on this worker type. In this case, we attempt to route to a worker of the correct layer instead of failing outright. This is a short-term mitigation. The long-term fix is better control over which worker gains auth over PlayerSpawner component.
=> Better player start forwarding logic for offloading multi-worker

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Allow the user to set the snapshot field to empty in the Cloud Deployment Configuration window to make the user experience more consistent (previously it would get automatically assigned to `.../Engine/Binaries/Win64` as a result of converting a relative empty path to full, which was confusing). The user would still not be able to start the deployment until they specify a snapshot path.
@jessicafalk @oblm
=> Allow (temporarily) setting snapshot path to empty in Cloud deployment window

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LayeredLBStrategy.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialWorldSettings.h
If a game has a class inheritance hierarchy such as the following:
Foo
/   \
FooBar  Foo2 , Foo3, Foo4, Foo5...
and they want FooBar on the Default layer but all the other Foo's on the FooLayer, they were not able to specify that without explicitly adding all FooX to the Layer's actor classes. 
This PR adds an explicit ActorClass list to the Default layer, so that the developer could put FooBar on the default layer and Foo on the FooLayer.
N/A
Use the offloading gym and set up a class hierarchy as the one above.
=> Add class override to Default layer

SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp
Add cookloadonly flag to the cooking command, in order to speed up schema generation.
Engine PR : https://github.com/improbableio/UnrealEngine/pull/553
Timings for scavengers, cooking Cascade.
Original time : 18 min.
Time without saving packages : 10 min
Time without saving or caching cooked data : 7.5 min (cookloadonly flag)
Time with cookloadonly and GC threshold set to 32 GB (instead of 16) : 5 min.
Time with cookloadonly and no GC : 4 min.
=> [UNR-3545] Add cookloadonly flag for cookandgenerateschema

SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
If checking the spatial service is in the correct project, first make sure it's actually running. This was really annoying me because it will 100% give you the pop-up dialogue for no reason if the service is stopped.
=> Check if service is actually running before erroring

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
Non-replicated offloaded actors in old offloading were LocalRole == Role_NONE, but in new offloading, they had authority.
This restores the functionality of CleanupLevelInitializedNetworkActors, which does the swap based on the LBStrategy (though this does now happen later than previously).
Engine PRs:
https://github.com/improbableio/UnrealEngine/pull/563
https://github.com/improbableio/UnrealEngine/pull/564
Should have worked. N/A
Example project offloading tutorial.
N/A
@m-samiec @MatthewSandfordImprobable @joshuahuburn
=> [UNR-3772] Fix authority for non-replicated offloaded actors

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCommandLineArgsManager.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKCloudDeploymentConfiguration.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKCloudDeploymentConfiguration.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
I combined https://github.com/spatialos/UnrealGDK/pull/2290 with the Connection Flow dropdown improvements suggested in https://improbableio.atlassian.net/browse/UNR-3746:
- `Cloud Deployment Name` field in the dropdown now refers to the same property as `Deployment Name` in the Cloud Deployment Configuration window, so the `Start Deployment` toolbar button will now use the name specified in the dropdown when quickly starting the new deployment without going through the Cloud Deployment Configuration window.
- `Local Deployment IP` and `Cloud Deployment Name` labels now get grayed out correctly when the edit box is disabled.
- Entering an invalid IP into the `Exposed local runtime IP address` field in the editor settings will trigger a warning popup and reset the value to an empty string. …
=> Improve the connection flow dropdown

SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LayeredLBStrategy.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/TestGridBasedLBStrategy.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/LayeredLBStrategy/TestLayeredLBStrategy.h
Give better error reporting and a failsafe, if a worker layer has a nullptr LoadBalancing Strategy.
Also makes the TestGridLBStrategy (and TwoByFour...) not blueprintable, so users do not choose it in error, since they are not available in non-editor builds.
N/A
Tested manually.
N/A
@jennifer-at-improbable-io @alastairdglennie
=> [UNR-3768] Give better error reporting with incorrect worker layer setup

SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
Found that it was possible for the call to reset `Can_Begin_Play` on editor shutdown could not complete if run with a fast/slow enough PC. This was encountered previously in the RC and fixed similarly with a flush+sleep.
This is a stop-gap solution until we better organise entity cleanup on worker shutdown - UNR-3697
Restarted the empty gym map 900 times
@mironec
=> Add flush and sleep after resetting begin play in gsm

SpatialGDK/Source/SpatialGDKServices/Private/SSpatialOutputLog.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Interop/SpatialOSDispatcherInterface/SpatialOSDispatcherSpy.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/OwnershipLockingPolicy/OwnershipLockingPolicyTest.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/Misc/SpatialActivationFlagsTest.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp, SpatialGDK/SpatialGDK.uplugin, ci/cleanup.sh, ci/generate-and-upload-build-steps.sh, ci/run-tests.sh, ci/setup-build-test-gdk.sh
enabling SpatialGDK tests for macOS CI and also moved the test repo to be the GDKTestGyms instead for macOS. 
corresponding build: https://buildkite.com/improbable/unrealgdk-premerge/builds/14995#_
=> Enable SpatialGDK Tests on MacOS

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialPlayerSpawner.cpp
Fix a bug where we delete a unique pointer immediately before using the value it points to.
Seems to almost never crash unless you put a breakpoint in or use SpatialView.
Run the handover gym and put a breakpoint on the offending line (or run with the experimental-up-to-date SpatialView for some reason I haven't worked out. Presumably more schema shenanigans has some knock on effect on exactly when memory gets cleared :shrug:).
@alastairdglennie
=> Player spawner retry crash

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetrics.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialMetrics.h
Metrics received by the WorkerSDK can be forwarded to Prometheus/Grafana for display in dashboards (approved projects only until SVP) 
Breaking interface change, note added 
Tested manually, can be viewed in NFR project metrics or binding to the delegate and surfacing metrics locally
@m-samiec
=> Histogram metrics and upload worker metrics to Grafana 

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialWorldSettings.h, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/LayeredLBStrategy/LayeredLBStrategyTest.cpp
Replaced the direct usages of  `bEnableMultiWorker` with  `bool IsMultiWorkerEnabled()` in `SpatialGDKDefaultLaunchConfigGenerator` and  `LayeredLBStrategyTest` file.
Made  `bEnableMultiWorker` private and added a setter function for it.
Added release note.
No tests required.
No documentation required.
=> Fix up usages of bEnableMultiWorker

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialFastArrayNetSerialize.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialFastArrayNetSerialize.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentFactory.h, SpatialGDK/Source/SpatialGDK/Public/Utils/ComponentReader.h, SpatialGDK/Source/SpatialGDK/Public/Utils/GDKPropertyMacros.h, SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h, SpatialGDK/Source/SpatialGDK/Public/Utils/RepLayoutUtils.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLatencyTracer.h, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.h, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/Utils/DataTypeUtilities.h, SpatialGDK/Source/SpatialGDKEditor/Private/Utils/LaunchConfigurationEditor.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/Utils/TransientUObjectEditor.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/Utils/Misc/SpatialActivationFlagsTest.cpp
In 4.25, `UProperty` was renamed to `FProperty`. To support both, we can use a macro that expands to `USomethingProperty` or `FSomethingProperty` depending on the engine version.
=> Replace usages of FProperty with GDK_PROPERTY that expands to correct type

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
SpatialStatics::GetActorEntityId() - Remove assert and return INVALID_ENTITY_ID instead.  This will prevent the debug method from taking down a server if it is called with nullptr somewhere.
Release note added.
Verified with event tracing prototype (https://github.com/spatialos/UnrealGDK/tree/feature/GSE-1012-spike-structured-logs), which calls the method above from multiple places, that the server is no longer taken down.
Release note.
* Increment `SPATIAL_ENGINE_VERSION` in `Engine\Source\Runtime\Launch\Resources\SpatialVersion.h` (in the engine fork) as well as `SPATIAL_GDK_VERSION` in `SpatialGDK\Source\SpatialGDK\Public\Utils\EngineVersionCheck.h`. This helps others by providing a …
=> SpatialStatics::GetActorEntityId() - Remove assert and return INVALID_ENTITY_ID instead

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Improvements to ApplyRPCInternal:
- Remove unused/unnecessary Parameters passed to ApplyRPCInternal.
- Refactor ApplyRPC / ApplyRPCInternal so that whether or not to execute the RPC based on queueing timeout is calculated inside ApplyRPCInternal, where it's used.
- Add ability to selectively suppress "Executed <RPCName> with unresolved references" warning per RPC Type using new SpatialGDKSetting RPCTypeAllowUnresolvedParamMap.
Release note added to CHANGELOG.md
Tested cloud deploy on our project with this change.
Use existing workflows to verify RPC functionality is working as expected.  Suppression of the warning can be tested by forcing a very low RPC queueing timeout with/without warning suppression in place via …
=> ApplyRPCInternal improvements

SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowControllerSpawner.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestStep.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestFlowController.h, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestStep.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/CrossServerAndClientOrchestrationTest/CrossServerAndClientOrchestrationFlowController.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/CrossServerAndClientOrchestrationTest/CrossServerAndClientOrchestrationTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/CrossServerAndClientOrchestrationTest/CrossServerAndClientOrchestrationTest.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DormancyAndTombstoneTest/DormancyAndTombstoneTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/RegisterAutoDestroyActorsTest/RegisterAutoDestroyActorsTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMovement/SpatialTestCharacterMovement.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestPossession.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestRepossession.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3066/OwnerOnlyPropertyReplication.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3157/RPCInInterfaceTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestNetReference/SpatialTestNetReference.cpp
Refactored AddServerStep / AddClientStep / AddUniversalStep into just AddStep.
Refactored AddStep function for BP to be AddStepBlueprint (to make it easier for c++ test makers, will still show as AddStep in blueprints)
Added ESpatialFunctionalTestFlowControllerType::All which allows you to run on all workers
NOTE: Because of making only 1 function for each like people were suggesting, if 'All' is passed WorkerId is ignored. It's ok in BP but a bit ugly in c++ since you still need to pass an int. I have a suggestion to it, maybe we have FWorkerDefinition passed in c++ instead of the enum + int, and so I can create some consts to help, thoughts?
There's another CL for the gyms that will be pushed if this one is approved.
=> [GSE-1244] Add functional test step API refactor

ci/unreal-engine.version
As we are dropping support for 4.23 in the next release, we no longer need to test against 4.23 on master.
@mironec @m-samiec
=> Disable testing against 4.23 on master

SpatialGDK/Source/SpatialGDK/Private/SpatialView/ConnectionHandler/SpatialOSConnectionHandler.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialView/OpList/WorkerConnectionOpList.h
* Increment `SPATIAL_ENGINE_VERSION` in `Engine\Source\Runtime\Launch\Resources\SpatialVersion.h` (in the engine fork) as well as `SPATIAL_GDK_VERSION` in …
=> no shadow declarations allowed when building for mac

SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
In 4.25, `UProperty` and types that inherit from it were renamed, and they added macros with deprecation warnings. Since macros operate on text without knowing about types, this also applied to `UInt16Property` which was a variable name we used, which clashes with the type of the same name.
@mironec @m-samiec
=> Fix UIntXProperty variables that collide with deprecated type names

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetricsDisplay.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
In 4.25, `UNetDriver::Time` is deprecated, and `GetElapsedTime()` should be used instead. Instead of doing `#if ENGINE_MINOR_VERSION <= 24` for every time we used `Time`, we can instead define `GetElapsedTime` in 4.24 to return `Time` and have the call sites consistent for 4.24 and 4.25.
@jessicafalk @mironec
=> Fix 4.25 UNetDriver::Time deprecation warnings

SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h
Minor API improvements, renaming variables, giving default values and tooltip for BP, asserting when trying to call GetFlowController with All WorkerType
=> Variable renaming, adding assert / tooltips

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialRPCService.cpp
Fixed a crash in the RPC service where we don't correctly deal with the case where stuff is still overflowed.
Fixed a crash that occured when overflowed RPCs remained overflowed after trying to flush them.
=> Added the overflow case to PushOverflowedRPCs.

CHANGELOG.md, RequireSetup, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/ManagedWorkerCoordinator.cs, SpatialGDK/Source/SpatialGDK/Public/Utils/GDKPropertyMacros.h
Re-add dynamic worker flags to SimPlayer launching as this is now supported again in runtime 0.4.0+
This speeds up deployment launch time.
@improbable-valentyn @improbable-andreaskrugersen
=> UNR-3550 Restore dynamic worker flags

SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LayeredLBStrategy.h
Users can currently select their dropdown to be a `LayeredLBStrategy`.
The `LayeredLBStrategy` should only be used by the GDK internally. If users select this in their configuration then can end up in infinite loops/stack overflows.
=> prevent-users-accidentally-using-layeredlbstrategy

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
Re-add check that was removed in favor of IsReadyToReplicate, since it does not check that the given actor has an entity id.
=> [UNR-3617] Fix incorrect condition check on ownership change

ci/unreal-engine.version
Due to a bug in example project CI (presumably).
N/A
N/A
=> Temporarily make 4.24 the primary engine version

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Adds a missing guard (it's used in all other accesses of the RPCService in this file)
None added: this is a fix to code introduced after the last release.
My project was breaking before, now it doesn't \0/
-
@MatthewSandfordImprobable @padhansell
=> Add missing RPCService guard

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitReader.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetBitWriter.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetBitReader.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetBitWriter.h
The SpatialPackageMapClient incorrectly assumed that it would always be used from inside the net stack, and cast an archive to a FSpatialNetBitReader.
This was done in order to be able to distinguish null references from unresolved ones and return the expected value. We do not need the archive to be an actual FSpatialNetBitReader to do this work.
But we do need to perform the additional task of collecting the mapped/unresolved references. This is done by setting a tls pointer to an instance of FSpatialNetBitReader in its constructor. This allows the code to perform its expected tasks while being compatible with another type of archive. And we also keep a scoped workflow compared to the native driver which uses arrays on the package map client which are reset in between properties reads. …
=> [UNR-3935] Remove cast to FSpatialNetBitReader in favor of a static methods.

CHANGELOG.md, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs
In the GDK build script, `-nocompile` has been conflated to affect both compiling the game binaries and the automation scripts. This will split it out so `-nobuild` can be passed to skip compiling the game binaries and `-nocompile` can be passed to skip the automation scripts (e.g. for pre-built engine, where from in 4.25 running UAT with `-compile` will cause an error).
=> Separate -nocompile from -nobuild

CHANGELOG.md, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/SpatialConfig/spatialos.SimulatedPlayerCoordinator.worker.json, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorCommandLineArgsManager.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp
With UE 4.25 using an invalid address leads to the connection being closed. Let's use a valid IP address to fix this. we are not using this address anyway, so it can just be localhost.
todo
Tested it by running cloud deployments and connecting sim players. Still need to test it on mobile.
* Increment `SPATIAL_ENGINE_VERSION` in `Engine\Source\Runtime\Launch\Resources\SpatialVersion.h` (in the engine fork) as well as `SPATIAL_GDK_VERSION` in `SpatialGDK\Source\SpatialGDK\Public\Utils\EngineVersionCheck.h`. This helps others by providing a more helpful message during compilation to make sure the GDK and the Engine are up to date.
If your …
=> UNR-3925: Use valid ip address

SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h
PR https://github.com/spatialos/UnrealGDK/pull/2411 introduced an additional non-auth server interest type. That addition would actually only have downsides in setting the system in a state when it is waiting to get additional component information while trying to load balance a child actor.
It is better if there is no change of component interest for non-auth servers.
=> [UNR-3837] Rollback additional server interest

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestClientNetOwnership/SpatialTestNetOwnership.cpp
fixing max build 
* Increment `SPATIAL_ENGINE_VERSION` in `Engine\Source\Runtime\Launch\Resources\SpatialVersion.h` (in the engine fork) as well as `SPATIAL_GDK_VERSION` in …
=> Remove shadow declaration

ci/get-engine.ps1
The get-engine.ps1 script does not format the gcloud url properly if you use a commit hash.
Format should be: UnrealEngine-commit hash.zip
This was found because the nightly mobile tests use the commit hash instead of a HEAD branch/name ...
I made an effort to review the other pipelines and I didn't find any other case where we explicitly used the commit hash, so I think this code path was just not exercised.
https://buildkite.com/improbable/unrealgdkexampleproject-nightly/builds/2729
@joshuahuburn @jessicafalk @yujunting
=> UNR-3999 - Fix gcloud engine URL generation when using commit hash

SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/ManagedWorkerCoordinator.cs
SimultedPlayerCoordinators wait for the `target_deployment_ready` tag to become `true`, but the DeploymentLauncher sets it to a capitalized `True`because of `bool::ToString`. This PR fixes this, and also includes a driveby fix for an off-by-one logging mistake of mine.
The code this fixes hasn't been released yet, but we probably do want to pull it into the 0.11 RC.
Tested by starting simulated player deployments for the Siege demo.
Starts deployments using the DeploymentLauncher and see if the simplayers connect.
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible …
=> Fix simplayer autoconnection

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Fix for a crash seen in servers when shutting down. Logs indicate the world is shutting down, and at that point the `OnConnectionToSpatialOSFailed` delegate is called, which attempts to access an invalid world.
@mironec
=> Ensure world is valid before dereferencing

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialRPCService.cpp
Print a warning and early out in `ExtractRPCsForType` if there's no entry for the entity + RPC type in the `LastSeenMulticastRPCIds` or `LastSeenRPCIds` map. This could happen when the RPC service is destroyed following a server travel, but the view still contains entities from the previous session, and an update comes through.
@MatthewSandfordImprobable @mironec
=> Fix RPC Service crash after server travel

SpatialGDK/Build/Scripts/BuildWorker.bat
We now try to call `Build.exe --help` instead of duplicating the information.
Tested kind of with both engine and project plugin setups, but someone testing with an actual project plugin setup would be nice.
=> Make build worker usage message consistent with the Build.exe message

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
Add NetworkFailure broadcast with OutdatedClient type and prevent further spawn attempts / map loading when client schema hash mismatches server schema hash
Tested , the broadcast is received in the game instance successfully, 
Feature is being documented as a troubleshooting step for public docs
@m-samiec @mironec
=> UNR-3962 - Broadcast OutdatedClient Network Failure on schema mismatch

SpatialGDK/Source/SpatialGDK/Public/Utils/LayerInfo.h
Added a missing include to LayerInfo.h, which was explosed due to Unity/non-unity build differences.
N/A
Compiled Windows Development Editor.
N/A
=> * adding missing include to LayerInfo.h

SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/GridBasedLBStrategy/GridBasedLBStrategyTest.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/LayeredLBStrategy/LayeredLBStrategyTest.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/OwnershipLockingPolicy/OwnershipLockingPolicyTest.cpp
Fixing the nightly tests by cleaning up the world after running load balancing tests.
The leftover actors cause log spam and invalid replication state.
N/A
Ran a slow (~= nightly) test run: https://buildkite.com/improbable/unrealgdk-premerge/builds/16960
N/A
Yes
=> [UNR-4138] Fix nightly tests

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h
Initialize SpatialDebugger to nullptr in constructor of FSpatialGDKEditorToolbarModule
Ran the editor with the default map set as benchmarkgym and two zones configured.
STRONGLY SUGGESTED: First test that the benchmarkgym works on master, if it crashes in IsValid(SpatialDebugger) then this fix should resolve it.. if the default configuration does not crash, change the default map to benchmarkgym and relaunch the editor (I believe in this case it may crash).. this fix prevents the crash.
@MatthewSandfordImprobable @samiwh
=> UNR-4128 - Prevent crash on editor startup because of invalid SpatialDebugger pointer

SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h, SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
GamePlayDebugger is only available either when `bBuildDeveloperTools ` is explicitly set or when it's building for debug/development. This is currently breaking some of our builds, so adding the checks into the GDK as well.
none required
Tested it locally and also kicked off a new build to test it: https://buildkite.com/improbable/unrealgdk-nfr/builds/2718
none required
=> make gameplay debugger only available for debug and development

SpatialGDK/Source/SpatialGDK/Private/Tests/RPCServiceTest.cpp, ci/build-project.sh
When running Unreal on mac, it saves some settings outside of the actual project folder. This has caused a test to start using the wrong netmode -> no net driver got created. Additionally, the test crashed, because we did not check whether the net driver exists.
passing mac build: https://buildkite.com/improbable/unrealgdk-premerge/builds/17355#_
=> Fix crash in tests when running mac ci

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/VisibilityTest/VisibilityTest.cpp
Our tests with SpatialOS disabled seem to be a bit slower for this test every now and then. Increasing the step time limit should fix it. At least I was no longer able to reproduce that flake locally.
=> fix flaky test

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialReplicationGraph.cpp
Gnarly bug where PlayerState isn't added as a dependency to the PlayerController because the PlayerController isn't in the GlobalActorReplicationInfoMap at this stage in the startup lifecycle. This prevents the PlayerState being found as a dependent Actor during the migration process, and so gets stuck on an old worker
=> Fix PlayerState migration with rep graph

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestShutdownPreparation/SpatialTestShutdownPreparationTrigger.cpp
FinishTest resets its local step definition to default values. The lambda for the step's code is stored in the definition, which means that the reset clears out the captured values of the lambda, in this case the `this` pointer. That means that accessing it after FinishStep leads to crashes (though only in Debug builds, since only those scribble the overwritten memory).
This issue will be investigated properly in the future, but for now these changes should fix the immediate issue with this test.
=> Move access to `this` before FinishTest, since the lambda is invalid after that

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewDelta.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/ExpectedViewDelta.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewDelta.h
Those checks somehow got lost when I first merged in the expected view delta class. This adds some additional checks to make sure that the connection status code and disconnect reason are tested correctly.
=> View Delta Tests: add connection status checks

SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp
Changed how CurrentStep.Reset() is called to prevent the lambdas being GCed (would happen when you do more things after calling FinishStep())
=> [unr-4279] Clear Step After Ticking

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLatencyTracer.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLatencyTracer.h
Add a blueprint callable SetTraceMetadata function. Because for zoning latency tracing of cross server RPCs and property updates it's necessary to have a consistent runid and we'd like to leverage the existing id which is the deployment Id of the simulated players deployment, so that we can continue to gather the metrics for client to server rpc and multicast rpc and simply add the additional cross server latency metrics.
I ran many cloud deployments with simulated players as well as running test cases in the nfr framework, for example:
https://buildkite.com/improbable/product-research-benchmarks-run/builds/15865#827c0602-7c02-4bd6-9288-bd720c7479be
STRONGLY SUGGESTED: Run the gdk_latency_zone2_1 test scenario via the nfr framework.
I believe this should generally not be impactful, it's …
=> UNR-4163 zoning latency nfr

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialVirtualWorkerTranslationManager.h, SpatialGDK/Source/SpatialGDK/Public/Interop/GlobalStateManager.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h
Made some noisy logs verbose, and kept relevant ones around. Spam still occurs in case of a problematic startup.
Logs relevant to startup are scattered around in various classes, and some phases are stateless. It would require an additional mechanism (status callback, global map) to gather them and emit them in a controlled fashion. Is it worth thinking about such a mechanism ?
=> [UNR-4113] Cleanup worker startup logs.

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp
Fixup two small errors;
`bEnableCrossLayerActorSpawning` was incorrectly used
`bEnableCrossLayerActorSpawning` wasn't being default initialised correctly (https://github.com/spatialos/UnrealGDK/pull/2467)
The hilarious combination of these two errors meant the issue wasn't obvious.
@samiwh @alastairdglennie
=> Fix bEnableCrossLayerActorSpawning in spatial settings

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialDebugger.h
Centre the Spatial Debugger tags over the actor's world location no matter how many parts of the tag (ex. Authority, Lock, etc) are enabled.
For the actors in the world:
1. Calculate the total width of the icons and text to be rendered
2. Calculate the horizontal offset based on the total width
3. Draw icons and text based on the calculated offset
I think this is too minor for a release note.
Tested manually with a local deployment of the Handover Gym by viewing different combinations of tags (ex. Authority, Lock, etc). 
See screenshots below:
QA Testing
As above (Press F9 to activate the Spatial Debugger runtime menu)
Updated the Spatial Debugger animation in https://docs.google.com/document/d/1G9cRz891Ycaiax-M7Psx3rlfX8qTIi0CTk8_71PL4Zg/edit#heading=h.j4ppr52lw6ck
=> Smarter positioning of Spatial Debugger tag elements

SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/WorkerRegion.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialDebugger.h
Added a property changed event for Spatial Debugger to refresh the worker regions in the editor when any visible property change is made to the Worker Regions e.g. Opacity, Height, and Vertical Scale. 
Also fixed an issue with Opacity not updating on the new combined worker boundary material.
These changes relate to new features that have not been released yet so I think a note about the bug is not needed.
Added tests to https://docs.google.com/spreadsheets/d/1Ld-2mkBAhA3i7Asf39tf_JeWScbw1Ya3mlYXGDrrWZw/edit#gid=0
Run the new tests from the above test plan in the section: Change Spatial Debugger visual properties
These changes relate to new features that have not been released yet so I think a note about the bug is not needed.
=> Spatial debugger editor missing property change event

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Little changes for a format-string error.
We shouldn't use %d for a string value.
This code does not raise an error simply because the log type is verbose.
=> fix a printf error

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracer.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/CriticalSectionFilter.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/ReceivedOpEventHandler.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewCoordinator.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewDelta.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/WorkerView.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/WorkerViewTest.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialEventTracer.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/CriticalSectionFilter.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ReceivedOpEventHandler.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewCoordinator.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewDelta.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/WorkerView.h
Read in commit order to prevent long term health problems.
Follow up work to the event tracing stuff.
Moves the critical section filtering from the worker view. Making it possible to remove event tracing code from the view delta.
=> Spatial view stuff critical section cleanup

RequireSetup
Event tracing doesn't compile unless you run `Setup.bat` to update the worker libs. Incrementing `RequireSetup` will run `Setup.bat` automatically when someone pulls master.
@MatthewSandfordImprobable @improbable-danny
=> Increment RequireSetup for event tracing

RequireSetup
Increment RequireSetup so `Setup.bat` runs automatically to update the hand-written schema in the `spatial` folder after pulling the new changes.
@jacquese @mironec
=> Increment RequireSetup after changes to hand-written schema

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
This log was called whenever a server received an RPC for an actor that it just destroyed, which is a valid case so this should not be an error log.
```Entity receiving ring buffer RPC does not exist in PackageMap!```
@mironec @alastairdglennie
=> [UNR-4396] Downgrade 'Entity receiving RPC not in PackageMap' log from error

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialRPCService.cpp
'Sent some but not all overflowed RPCs' is misleading when no RPCs were actually sent.
@MatthewSandfordImprobable @samiwh
=> [UNR-4399] Don't log 'Sent some but not all overflowed RPCs' if no RPCs were sent

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialLoadBalanceEnforcer.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
Do not include entity completeness tags in component presence, otherwise they get delegated, and cause unintended workers to view them, which makes them think the associated entities are complete (e.g. wrt to the LB system).
n/a
Handover test now mostly works...
n/a
@jacquese @m-samiec
=> [UNR-4390] Fix loadbalancing

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Drops a received actor's PendingAddComponent only if the actor is not ready, which means it is locally authoritative and awaiting its acknowledgement by the runtime.
The other case where it can happen is when the authority is delegated, we can received AddComponent for all the delegated components, which can contain new data.
Tested with the test contained in https://github.com/spatialos/UnrealGDK/pull/2636, which happened to frequently trip on this case
=> [UNR-4401] Drop component data only if the actor is not ready

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracerUserInterface.cpp
Android clients do not seem to have GWorld defined. This is causing CI issues in the example project. I don't think including it here is providing us any value. Additionally I believe GWorld should be used only in totally necessary cases so I think we can just remove it.
=> Removing use of GWorld.

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h, SpatialGDK/Source/SpatialGDK/Public/SpatialCommonTypes.h, SpatialGDK/Source/SpatialGDK/Public/Utils/EntityFactory.h
OnSubobjectDeleted was called with a dangling pointer, which was used to build a weak pointer, causing a crash.
This fix add a weak pointer to the method, in order to be able to properly cleanup the map.
=> [UNR-4249] Change onSubObjectDeleted to use a weak pointer

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Debug components get added to `PendingAddComponents` and then passed to `ApplyComponentDataOnActorCreation` in `ReceiveActor` but they don't represent a generated component so there's no corresponding class info, thus the warning gets printed.
Fix: don't pass them to `ApplyComponentDataOnActorCreation`.
@ImprobableNic @MatthewSandfordImprobable
=> [UNR-4440] Fix 'Could not find offset for component id' warning

SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/MulticastRPCService.cpp
The order we process authority wrt updates does matter. This PR reflects that for the multicast rpc service where we can lose and gain authority over components we care about.
=> fix ordering

SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingTest.cpp
Fixing up a failure in event tracing tests. The wrong event was being fired in the GDK.
=> Fixing merge component event trace test

SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Change EActorMigrationResult to enum class to fix a naming collision with BrainComponent.h.
How did you test these changes prior to submitting this pull request? Compiled Windows editor and Linux server against a project that also uses BrainComponent.h.
What automated tests are included in this PR? N/A
STRONGLY SUGGESTED: How can this be verified by QA? N/A
How is this documented (for example: release note, upgrade guide, feature page, in-code documentation)? N/A
=> Change EActorMigrationResult to enum class to fix a naming collision

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKCloudDeploymentConfiguration.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKCloudDeploymentConfiguration.h
Similarly to the handling of the deployment name, the deployment launcher displays the hint for the simulated players deployment name, if it does not conform to the regex format.
Checked by launching UE4 and attempting to start a cloud deployment, with simulated players, where the simulated players deployment name is invalid (e.g. > 32 chars)
Documentation not required as it is visible by user
=> UNR-2162 fix: display regex errors for simplayers deployment name

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewDelta.cpp, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp
The worker configuration file watcher checks the file extension and only updates if files with the `.worker.json` extension are changed.
Run UE4 and change the files in `UnrealGDKExampleProject\spatial\workers\`
=> UNR-4221 fix: worker checks file ext

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMigration/SpatialTestCharacterMigration.cpp
Ensured the test only runs with one client by setting the Testing Mode to Detect in the WorldSettings on the corresponding test map and removed the step which to move multiple characters out of the way.
Run the automated test with 1 or 2 clients, a warning is expected in both cases: 
`LogSpatialLoadBalancingHandler: Warning: Prevented Actor TeleportingPlayerController_C_0 's hierarchy from migrating because Actor Actor_0 (9) does not have authority`
Corresponding test gym PR needed for this test to run correctly: https://github.com/spatialos/UnrealGDKTestGyms/pull/230
=> Migration test timeout for multiple clients

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/ClientServerRPCService.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/MulticastRPCService.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/RPCServiceTest.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/ClientServerRPCService.h, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/MulticastRPCService.h, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/SpatialRPCService.h
Prevent RPCs being dropped by splitting the rpc system into view-like and update-like parts. The actor system relies on rpc data being initialised before it has the opportunity to try and send rpcs, and the rpc service relies on actors having been instantiated to receive rpcs.
=> UNR-4456 Ensure the rpc data has been written before processing rpcs.

Setup.sh
Cut \r from version now that the version file has CRLF file endings
Passing macOS build: https://buildkite.com/improbable/unrealgdk-premerge/builds/19595
=> UNR-4504: fix version parse

SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Clarify the name of the manually entered number of server-worker to be launched in the editor option.
=> UNR-3633 - Clarify options for number of workers launched

SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTest.h, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestFlowController.h, ci/gdk_build.template.steps.yaml
Internal.
The issue I think stems from some race conditions in the testing framework itself.
I work around this by attaching a StepIndex when completing a step, to avoid double-advancing a step.
That in turn requires slightly more robust replication for CurrentStepIndex, and this is an unfortunate thing - since even with my changes, there is still an extremely rare (hopefully) race condition where this will fail to replicate correctly. (RPC -> var -> onRep -> finishStep)
=> [UNR-4540] Try to fix ensure in FlowControllers

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialTraceEventBuilder.cpp
This fixes an issue when uploading the event trace json data to Kibana. Kibana sees the "." character and creates an ""object" type instead of just using a string.
=> Remove "." from key string

SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp
There can only be a single FSpatialNetBitReader in a given stack. Their scope in ApplyRPCInternal was not small enough and a complex scenario while calling RPCs could loop the NetDriver back  in the stack.
=> Fix scope for FSpatialNetBitReader lifecycle

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewCoordinator.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewDelta.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/WorkerView.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/CommandRetryHandlerTest.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/DispatcherTest.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/SubViewTest.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/ViewCoordinatorTest.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/ViewDeltaTest.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/WorkerViewTest.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ComponentSetData.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewCoordinator.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewDelta.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/WorkerView.h, SpatialGDK/Source/SpatialGDK/Public/Tests/SpatialView/SpatialViewUtils.h
Easier to read in commit order.
Updating spatial view to work with 15.
The change from component authority to component set authority requires a significant change to spatial view.
Instead of getting add and remove component ops from the worker sdk on authority delegations, we now get the current state of all existing components in a component set, when that set is delegated, as a list.
In order to deal with this we need to refresh components delegated in a component set and we need to know which components are missing from an authority op to know when to remove them.
When an authority op is received the view delta will generate intermediate component changes to remove all components from that set on the relevant entity. It will then generate intermediate component changes to add all …
=> Feature/unr 4576 spatial view 15 - Part 1

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialSnapshotTest/SpatialSnapshotTest.cpp
Bump pinned runtime version to 15.0.0-preview-5 to fix an issue where snapshot were saved containing a partition component which could not be reloaded.
The issue is that when reloading from a snapshot, some workers recreate their startup actors. Namely, their singletons, GameState and GameMode. This was due to a race in the startup sequence on an update to the GSM.
Analysis : 
In UGlobalStateManager::ApplyStartupActorManagerUpdate, changing 
```
bCanBeginPlay = Schema_ReadBool(...
bCanSpawnWithAuth = true
```
to 
```
bCanSpawnWithAuth = !bCanBeginPlay
bCanBeginPlay = Schema_ReadBool(...
```
**StartupSequence :** 
Wait for GlobalStateManager->IsReady() == bCanBeginPlay || IsLeader()
Wait for WorkerTranslation->IsReady() (the worker translation manager waits for IsReadyToBeginPlay before …
=> [UNR-4482] Change how bCanSpawnActorWithAuthority is set after an update

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
In 4.26 `UpdateChangelistMgr` now returns a result status. When a replicated array is over the maximum size, this result is `ERepLayoutResult::FatalError`, and native Unreal just closes the connection if that happens.
In Spatial, for now, we will just skip replicating that actor or object, but we need to properly investigate this behavior.
Follow-up ticket: https://improbableio.atlassian.net/browse/UNR-4667
=> Early out from replication if UpdateChangelistMgr fails

SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
There was a workaround for 4.20 to correctly import libraries. This is not necessary anymore.
Corresponding change in the engine: 
- 4.25: https://github.com/improbableio/UnrealEngine/pull/721
- 4.24: https://github.com/improbableio/UnrealEngine/pull/722
Adds the changes done in : https://github.com/spatialos/UnrealGDK/pull/1026
=> UNR-1628/Remove runtime library build workaround

SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Epic deprecated `InvokeTab` in 4.26, and we should use `TryInvokeTab` instead.
@antoinecordelle @MatthewSandfordImprobable
=> [UNR-4687] Fix deprecation warning for InvokeTab in 4.26

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
In a rare case, when an entity that was loaded asynchronously, it could happen that we receive a second component add on UNREAL_METADATA_COMPONENT. Most likely caused by interest flickering (remove-add being given as an add after going through SpatialView)
These add would then trigger an assertion when dequeuing the ops later. It turns out that a lot of components do not need to be queued, so we avoid doing that for the problematic component as well.
=> [UNR-4603] When async loading, avoid queuing components that are handled through static component view

SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp
Fixes an off-by-one error in AddStepSetTagDelegation.
ServerWorkerIDs in the testing framework start at 1, so the largest allowed index is equal to the number of workers in the deployment.
The existing debug interface doesn't actually use this function, which is why this did not get caught.
=> Set delegation index fix

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialCleanupConnectionTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialTest1x2GridSmallInterestStrategy.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialCleanupConnectionTest.h, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialTest1x2GridSmallInterestStrategy.h
Fixed client connection not being cleaned up when moving out of interest of a server.
Fixed client connection not being cleaned up when moving out of interest of a server.
Added functional test to test number of connections when moving in and out of interest range of a server.
Documentation in release notes
=> UNR-988 Bugfix/cleanup zombie connections

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialReceiver.h
Entities depending on a package being loaded in the background are processed as soon as we receive the callback on the package bein loaded.
This triggered a rare issue in UNR-4630 where this callback was sent while we were deserializing a component. This caused it to try to deserialize another component, and cased an assertion error in FSpatialNetBitReader which have the limitation that we can only have a single one per stack.
While we could remove that limitation, a better choice would be to remove this unecessary reentrancy, queue the packages that have been loaded, and process them later. This will make stacks less complicated.
=> [UNR-4630] Queue async loaded packages instead of processing them right away

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp
This warning can occur under normal operation, for example when running tests.  This change downgrades it to verbose.
I don't think this change requires a release note, but let me know if i'm wrong.
n/a
n/a
* Increment `SPATIAL_ENGINE_VERSION` in `Engine\Source\Runtime\Launch\Resources\SpatialVersion.h` (in the engine fork) as well as `SPATIAL_GDK_VERSION` in `SpatialGDK\Source\SpatialGDK\Public\Utils\EngineVersionCheck.h`. This helps others by providing a more helpful message during compilation to make sure the GDK and the Engine are up to date.
If your change updates `Setup.bat`, `Setup.sh`, core SDK version, any C# tools in `SpatialGDK\Build\Programs\Improbable.Unreal.Scripts`, or hand-written schema in `SpatialGDK\Extras\schema`:
* …
=> Warning -> Verbose

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRepNotify/SpatialTestRepNotify.cpp
Fix failing test in 4.26, where the expected native behaviour changed.
Thankfully, the behaviour is now the same as ours.
N/A
This is fixing a test.
N/A, but added comments explaining this.
=> [UNR-4724] Fix SpatialTestRepNotify failing on native in 4.26

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialStatics.h
Added blue print callable function `GetMaxDynamicallyAttachedSubobjectsPerClass` to `USpatialStatics` that get the maximum dynamically attached subobjects per class as set in `SpatialGDKSettings`.
To support fixing the dynamic components gym PR:
- https://github.com/spatialos/UnrealGDKTestGyms/pull/262
Added to release notes.
=> UNR-4459 Bugfix/dynamic components gym too many subobjects

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
Prevent spatial debugger from consuming input.
=> Spatial debugger, don't consume input

SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialGDKFunctionalTestsModule.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialGDKFunctionalTestsPrivate.h, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/LogSpatialFunctionalTest.h
Adds an outwardly accessible `LogSpatialFunctionalTest` category, to be used for logs in functional test implementations (as opposed to `LogSpatialGDKFunctionalTests`, which is used for logging in the functional test framework itself).
*Alternative solutions:*
- Don't add a category. Have every test define its own category if it needs to.
- Expose the existing `LogSpatialGDKFunctionalTests` and use it both for the framework implementation and in test implementations.
*Request for bikeshedding:* This is almost certainly a terrible name since it's so similar to `LogSpatialGDKFunctionalTests`. Other ideas welcome (either for a different name, or for different solutions altogether).
N/A I believe?
=> Add LogSpatialFunctionalTest

SpatialGDK/Source/SpatialGDKFunctionalTests/Private/Test1x2WorkerSettings.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/Test1x2WorkerSettings.h
Adds a C++ version of the 1x2 worker settings used in test maps.
Used in the SpatialZoningMap re-created here: https://github.com/spatialos/UnrealGDKTestGyms/pull/268
=> Add 1x2 worker settings in C++

CHANGELOG.md, RequireSetup, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/DeploymentLauncher/DeploymentLauncher.cs, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/AbstractWorkerCoordinator.cs, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/ManagedWorkerCoordinator.cs, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/RegisseurWorkerCoordinator.cs, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialConnectionManager.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialGameInstance.h
DeploymentLauncher no longer adds `target_deployment_ready` flag to the simplayer deployments; simplayer deployments, in turn, no longer check whether this flag is set.
Instead, WorkerCoordinator tries to launch simplayer executables as soon as it can, and restarts them should they fail.
Simplayer UE clients now finish with a nonzero exit code if they get a NetworkFailure or a TravelFailure.
Together, these changes solve the initial issue: simplayer deployments now can be restarted via the console.
Additionally, I've added some more NetworkFailures when SpatialConnectionManager errors out.
Added a release note.
No automated tests were added. To check, launch a cloud deployment with SimPlayers and restart them via the Console.
Added a set of notes to CHANGELOG.
=> UNR-4319: Moved main deployment availability checking to WorkerCoordinator

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/CrossServerAbilityActivationTest/CrossServerAbilityActivationTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/CrossServerAbilityActivationTest/CrossServerAbilityActivationTest.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/CrossServerAbilityActivationTest/GA_IncrementSpyValue.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/CrossServerAbilityActivationTest/GA_IncrementSpyValue.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/CrossServerAbilityActivationTest/SpyValueGASTestActor.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/CrossServerAbilityActivationTest/SpyValueGASTestActor.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/GASTestActorBase.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/GASTestActorBase.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDKFunctionalTests.Build.cs
Corresponding PR with the map containing this test: https://github.com/spatialos/UnrealGDKTestGyms/pull/259
Adds a multi-server test for activating abilities from one server on another server, via handle/class/tag/event.
TODO:
- Unreal build tool gives a warning about the test module depending on GameplayAbilities while the GDK uplugin does not. The solution would be to add GameplayAbilities as a plugin dependency, but then the GDK as a whole requires that dependency. There does not appear to be a way to specify a plugin-level dependency as optional.
N/A I believe.
This is the test for https://github.com/improbableio/UnrealEngine/pull/692
N/A
=> [UNR-4529] Cross-server ability activation functional test

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/EventTracingTests/EventTracingTest.cpp
The issue was that the event tracing files selected were both clients. We want to use one client and one worker.
=> Ensure we only take one worker and one client ET files.

CHANGELOG.md, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMigration/SpatialTestCharacterMigration.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestCharacterMigration/SpatialTestCharacterMigration.h
The movement can sometimes become unstable and fall off the map and not trigger the trigger boxes which are spawned. This method works a lot more reliably at low FPS 
=> Trigger boxes don't always work with low FPS 

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Spatial bundles should not be requested when running with spatial disabled
- Unauth spatial, boot editor with/without the setting enabled. Ensure that spatial does not fetch a cached bundle as this doesn't require auth and silently executes the command.
- Launch the editor with spatial disabled, enable spatial and attempt to run a deployment. Ensure that this attempts to auth and download the runtime binaries 
^
@MatthewSandfordImprobable @jnicholas-io
=> Don't fetch spatial bundles if spatial is not enabled

SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SchemaGenObjectStub.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SchemaGenObjectStub.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Add testing of `OwnerOnly` and `Handover` properties for schema generation.
Previously this test did not actually test all supported features, it now covers generation of all support property types.
TestEqualDatabaseEntryAndSchemaFile logging has been improved and should be more clearly specify what caused the test failure.
Passed snapshot:
=> UNR-4793 Schema generator test support cond_owneronly

CHANGELOG.md
* Notes that we don't support ServerTravel.
* This sits under `0.12.0` > `Breaking Changes`. It was a breaking change introduced in `0.11.0` but we forgot to document it when that release went out and our thinking is that:
1. It's more noticeably non-functional in `0.12.0` so we should flag it here.
1. Users today are more likely to read `0.12.0` release notes than `0.11.0`, and they need to know this.
This is an un-release note
Rendered the markdown, checked the language with @mironec, ran spellcheck.
@mironec
=> Note that we don't support ServerTravel

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetConnection.h
Fixed a missing `OnDestroyed` subscription due to `UPlayer::GetPlayerController(UWorld*)` returning `nullptr`, when called on a client from a `USpatialNetConnection`.
The repro steps I used are as follows:
* Start a cloud deployment with the GDK Shooter Example
* Connect to it from the Editor
* Start a packet shaper such as Clumsy with 100% packet loss
* Run around and shoot for ~10 seconds
* Stop the shaper; the controller should be destroyed after this.
Added a release note to the changelog.
=> UNR-4807: Fixed heartbeats potentially executing with destroyed controllers

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
The issue lies in Unreal converting every path to a path relative to `FPlatformProcess::BaseDir()`, so when we're launching the runtime exe to convert the non-classic config to a classic one, we pass in this relative path. The working dir of the runtime, however, is `%PROJECT_PATH%/spatial`, which leads to pathing issues.
So when the engine is at `D:/work/UnrealEngine/`, BaseDir would be `D:/work/UnrealEngine/Engine/Binaries/Win64/`. Project directory would be `D:/work/UnrealGDKTestGyms`, so the absolute config path is `D:/work/UnrealGDKTestGyms/spatial/Something.json`; the relative path is `../../../../UnrealGDKTestGyms/spatial/Something.json`. Before the changes, working directory of runtime is `D:/work/UnrealGDKTestGyms/spatial`, so after being combined with the relative path it points …
=> UNR-4799: Fixed an error with launch config generation

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialReceiver.cpp
Fix verifySlow and checkSlow firing in SetOwner due to a misordering of PreNetReceive and PostNetReceive due to the previous bugfix for concurrent modification while iterating over the set.
Hmmmmmmmmm, is this in 0.12-rc?
Tested random maps in debug mode (where the slow checks would normally fire).
N/A
=> [UNR-4708] Fix verifySlow and checkSlow in SetOwner

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/Components/RemotePossessionComponent.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLoadBalancingHandler.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/Components/RemotePossessionComponent.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialLoadBalancingHandler.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerMultiPossessionTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerMultiPossessionTest.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionGameMode.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionGameMode.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionLockTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionLockTest.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionTest.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/NoneCrossServerPossessionTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/NoneCrossServerPossessionTest.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestRemotePossession.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestRemotePossession.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/TestPossessionPlayerController.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/TestPossessionPlayerController.h
RemotePossessionComponent for PlayerController to Cross-Server possession
A generic solution for Cross-Server Possession. 
The customer can add a RemotePossessionComponent to an AController if the AController wants to possess an APawn which authoritative in another worker. The AController will be migrated to that worker. The AController will possess the APawn after OnAuthorityGained.
We have 3 functional test cases for this feature.
1. 1 Controller possesses 1 Pawn. Contributed by @siliviali 
2. 3 Controllers possess 1 Pawn. Contributed by @yujunting 
3. 1 Locked Controller possesses 1 Pawn. Contributed by @jayprobable 
Jira ticket:https://improbableio.atlassian.net/browse/UNR-4671
=> UNR-4671 RemotePossessionComponent and TestCases

SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs
Modified SpatialGDK.Build.cs to remove warnings related to Android build.
N/A
I built the example project for Android.
Also ran buildkite build of Android: [see results here](https://buildkite.com/improbable/unrealgdkexampleproject-nightly/builds/4161)
N/A
=> UNR-4703 Cleanup Android build warnings

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp
Code was designed to handle both automatic and manual configuration, but the check for manual worker connection was done before actually generating the configuration (if it was needed).
The format was also outdated and needed to be updated.
=> [UNR-4794] Fix scan for manual worker launch

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialComponentTest/SpatialComponentTest.cpp
Fix a compile warning as:
1>C:\io\UE4\4.26\Engine\Plugins\UnrealGDK\SpatialGDK\Source\SpatialGDKFunctionalTests\SpatialGDK\SpatialComponentTest\SpatialComponentTest.cpp(231): warning C4996: 'AActor::GetComponentsByClass': Use one of the GetComponents implementations as appropriate Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
=> Use GetComponents instead of GetComponentsByClass to fix a compile warning

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracer.cpp
Fix for sampling mode strings, it looks like StringCast is pointing to the same internal memory so maybe it has a static conversion buffer or something. The result was that the string would be modified to the last entry 
Tested manually
=> Fix for sampling mode strings 

SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
Previously the schema database validator was using the asset registry's object path name for identifying asset classes that were still valid within a project. Turns out that although object path name is almost always == class path, it's not true 100% of the time. Specifically in Interpid, one of their levels contained some sublevels where this wasn't true for any of them. @alastairdglennie found the correct information in the "GeneratedClass" asset tag, which this PR switches to using.
Ran full schema gen on TestGyms/Interpid/Scavengers with no stale classes found.
@alastairdglennie
=> Use generated tag class name instead of object path

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStaticComponentView.cpp, SpatialGDK/Source/SpatialGDK/Private/Schema/ClientEndpoint.cpp, SpatialGDK/Source/SpatialGDK/Private/Schema/MulticastRPCs.cpp, SpatialGDK/Source/SpatialGDK/Private/Schema/ServerEndpoint.cpp, SpatialGDK/Source/SpatialGDK/Public/Schema/ClientEndpoint.h, SpatialGDK/Source/SpatialGDK/Public/Schema/MulticastRPCs.h, SpatialGDK/Source/SpatialGDK/Public/Schema/ServerEndpoint.h
RPC endpoints are no longer read from the static view, so remove that logic and clean up inheritance from `Component`.
@jacquese @MatthewSandfordImprobable
=> Remove RPC endpoints from static component view

SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerMultiPossessionTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionLockTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/NoneCrossServerPossessionTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/TestPossessionPlayerController.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/TestPossessionPlayerController.h
1. Fix the SetReplicates warning message issue of RemotePossession test case.
this issue coming from the Default Pawn of PlayerController, it was set as replicated, so when remote possess been called, `SetReplicates(true);` was called from APawn::PossessedBy(AController* NewController).
To avoid this issue is UnPossess the Default Pawn before possess
2. Fix the issue on FunctionalTest, we hit a random issue only happened in server only tests.
the reason is bHasAckFinishedTest wasn't installed in the constructor. So the client flow didn't start and stop so bHasAckFinishedTest is never changed, but by default, is maybe false, so the check acknowledges failed.
3. Update the introduction of each test.
4. Have some spell changes and name changes.
Successful tests:
=> UNR-4852 Make the RemotePossession Functional tests workes for together and fix bug bout SetReplicates warning message issue

ci/ReleaseTool/PrepCommand.cs
Adds Xbox and PlayStation dlls checks to the release process.
Not applicable, internal only.
I rendered this markdown in my IED.
@m-samiec
=> UNR-4642: Add Xbox & PlayStation dll checks to the release process

SpatialGDK/Source/SpatialGDK/Public/SpatialGDKLoader.h
SpatialGDKLoader is trying to load a non-existent .prx worker lib for PS4, eventually causing the console to crash on connection to Spatial.
Fixed by updating libworker.prx to libimprobable_worker.prx
Tested on PS4 by attempting to connect to a Spatial deployment, observed no crash after change.
@mironec @m-samiec @joshuahuburn
=> Fix PS4 Worker Lib file name

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDK/Public/Utils/EntityPool.h
Fixed entitypool capacity overflow issue by removing the ability to request a pool size larger than max_int32
I did a manual test with a high value.
=> [UNR-4524] Fix for entity pool int32 overflow

SpatialGDK/Source/SpatialGDK/Private/Utils/RPCRingBuffer.cpp
Fixed a warning due to using a variable that's uninitialized in `default` case.
@mironec
=> Fix uninitialized variable warning

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
We need to advance `RPCService`'s view before the `ActorSystem`'s so we can correctly call RPCs when checking out actors.
@ImprobableNic
=> Restore ordering of RPCService->AdvanceView()

SpatialGDK/Source/SpatialGDK/SpatialGDK.Build.cs, SpatialGDK/Source/SpatialGDKEditor/SpatialGDKEditor.Build.cs, SpatialGDK/Source/SpatialGDKEditorCommandlet/SpatialGDKEditorCommandlet.Build.cs, SpatialGDK/Source/SpatialGDKEditorToolbar/SpatialGDKEditorToolbar.Build.cs, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDKFunctionalTests.Build.cs, SpatialGDK/Source/SpatialGDKServices/SpatialGDKServices.Build.cs, SpatialGDK/Source/SpatialGDKTests/SpatialGDKTests.Build.cs
`bFasterWithoutUnity` was deprecated a long time ago but we kept it around for 4.23 compatibility. We can replace its usage with `bUseUnity` now.
@joshuahuburn @mironec
=> Replace usage of deprecated bFasterWithoutUnity with bUseUnity

SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/MulticastRPCService.cpp
Add missing break that meant we were calling `PopulateDataStore` every time an update came through. This doesn't seem to have affected correctness, although we probably did a bunch of extra copies.
@jacquese
=> Add missing break in MulticastRPCService

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslator.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/DebugLBStrategy.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LayeredLBStrategy.cpp, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/DebugLBStrategy.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/GridBasedLBStrategy.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LayeredLBStrategy.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDK/LoadBalancing/AbstractLBStrategy/LBStrategyStub.h
Enhanced server logging to include load balancing and local worker info on startup.
Manual test of the "Offloading Gym" logged the following output in Unreal (only a sample included for brevity):
```
LogSpatialVirtualWorkerTranslator: ApplyVirtualWorkerManagerData for UnrealWorkerA643129A432C162875AF45B9D05DBD29:
LogSpatialVirtualWorkerTranslator:     -> VirtualWorkerTranslator is now ready for loadbalancing.
LogSpatialVirtualWorkerTranslator:     -> Strategy: Layered, LocalLayerName = DefaultLayer, LocalVirtualWorkerId = 1, LayerStrategy = Grid, LayerNamesPerVirtualWorkerId = {1 = DefaultLayer, 2 = DefaultLayer, 3 = DefaultLayer, 4 = DefaultLayer, 5 = Offloading}
LogSpatialVirtualWorkerTranslator:     -> Assignment: Virtual Worker 1 to UnrealWorkerA643129A432C162875AF45B9D05DBD29 with …
```
=> [UNR-4862] Output load balancing and local worker info on startup

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp
Revert a change made in the RoutingWorker PR. Batching RPC updates together results in better throughput and potentially better data consistency, but also increased latency.
The data consistency benefits won't be there until the ComponentSet updates land in the runtime, and the latency NFR regressed. So we are reverting that change for now.
=> [UNR-5028] Send RPCs immediately again

ci/gdk_build.template.steps.yaml
CI builds were timing out, up the timeout
=> Increase ci timeouts to 180 minutes

SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp
Server worker partition entities should persist so they can be reclaimed when reloading.
Snapshot reloading tests (when run correctly) now work.
@mironec @Vix2021
=> Fix snapshot reloading tests

SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/RPCService.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/RPCTypes.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCService.h, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCTypes.h, SpatialGDK/Source/SpatialGDK/Public/Schema/RPCPayload.h
Add the basic infrastructure that will be used to implement the various types of RPCs we have.
The plan is to reimplement each type of RPC using it (tickets in https://improbableio.atlassian.net/browse/UNR-4839), and swap usage one by one until there is no remaining code that calls the previous SpatialRPCService.
Tests will be created for each individual RPC type.
=> [UNR-5035] Add base infrastructure for modularised RPC service

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
Fix/limit default client permissions from auto generated launch config.
Added to release notes.
- Fixed an issue where an auto generated launch config was giving the client worker too many permissions.
=> UNR-4915 fix auto generated launch config for clients.

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
Sublevel world-settings objects didn't have the correct authority set on them when begin play was called. This turned out to be a quirk of the ActorIterator which [explicitly ignores sublevel WorldSettings](https://github.com/improbableio/UnrealEngine/blob/bee929c9691fa4da724623d91ed12cf2124adaf8/Engine/Source/Runtime/Engine/Public/EngineUtils.h#L314). The impact of this was that multiple world settings entities (1 per server) would be created for each sublevel. 
The fix just involves iterating over all level actors directly instead of using the ActorIterator.
- Fixed an issue where authority was not correctly delegated to sublevel world settings prior to BeginPlay being issued. This resulted in duplicate world settings entities being created.
Running world comp gyms, I can now see the …
=> World settings fix

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/SpatialRPCService.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialSender.h
Move RPC logic from sender into the RPC service. This PR is a subset of https://github.com/spatialos/UnrealGDK/pull/2879 because that one got too conflicty. This PR is entirely copy paste other than:
- Clearing RPC flows are now aligned for incoming and outgoing.
- Makes processing incoming and outgoing RPCs periodically uniform (not using timer manager)
=> Move RPC logic from sender into RPC service

CHANGELOG.md, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Build/Build.cs, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/Common/LinuxScripts.cs, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/AbstractWorkerCoordinator.cs, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/LifetimeComponent.cs, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/ManagedWorkerCoordinator.cs, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/RegisseurWorkerCoordinator.cs, SpatialGDK/Build/Programs/Improbable.Unreal.Scripts/WorkerCoordinator/WorkerCoordinator.csproj
[UNR-4933 Modify Worker Coordinator to restart simplayers](https://improbableio.atlassian.net/browse/UNR-4933?atlOrigin=eyJpIjoiMWI1YTIwYjU3YTQzNDlkNjk5OWYyYzQ3ZTljNDkxZTIiLCJwIjoiaiJ9)
Modify worker coordinator to support lifetime management. 
Worker coordinator can periodically do these:
- Start a simulated player client with a random lifetime.
- Wait for the lifetime runs out.
- Stop the simulated player client and wait for it timeout at server.
- Restart the simulated player client.
Parameters:
- `max_lifetime` **Default is not to turn on this function.** Maximal random range about the client's lifetime in seconds.
- `min_lifetime` Minimal random range about the client's lifetime in seconds.
- `restart_after_seconds` When the client runs out of lifetime and ends, wait for seconds to …
=> UNR-4933: Modify worker coordinator to support lifetime management.

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestCrossServerRPC/SpatialTestCrossServerRPC.cpp
Added an "ActorReady" test step before RPCs are sent, to ensure RPCs are not lost.
Fix for an existing automated test, which failed intermittently.
=> [UNR-5078] Fix for cross server RPC intermittent test failure

SpatialGDK/Source/SpatialGDK/Private/SpatialGDKModule.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorModule.cpp, SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/SpatialGDKEditorCommandletModule.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialGDKFunctionalTestsModule.cpp, SpatialGDK/Source/SpatialGDKTests/Private/SpatialGDKTestsModule.cpp
Complex types were instantiated in SpatialConstants.h, weighing on the compilation unecessarily.
They are changed to extern declaration and explicitely instantiated in the module files.
This shaves off 8 sec from the build (108 vs 117s) and 90 MB from the obj files (1.39 vs 1.48GB)
=> Remove complex type instantation from SpatialConstants.h

SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp
The following PR changed how constants were declared : https://github.com/spatialos/UnrealGDK/pull/2968
This resulted in a global variable not getting its expected value because global variable initialization happens in an arbitrary order.
=> Fix static initialization fiasco

SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/GeneratedTestMap.cpp
This change doesn't affect maps on which the viewport isn't the default one. (e.g. maps with possession tests where the viewport follows a certain actor)
=> Made default viewport nicer on generated maps 

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverRPC.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialTraceUniqueId.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/RPCService.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/RPCTypes.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverRPC.h, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialTraceUniqueId.h, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCQueues.h, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCService.h, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCTypes.h, SpatialGDK/Source/SpatialGDK/Public/Utils/ObjectAllocUtils.h
The modularized RPC infrastructure needed additional facilities to accommodate the need for event tracing.
This boils down to two thing, triggering some behaviour at certain points of the pipeline, and storing some data alongside queued RPC (received/to send). 
To keep the system without opinion as to which types represent EventTracing data, this should be implemented in a way that the system would not need to be modified (too much) if we were to change all the EventTracing types, for instance.
A callback on given events is not enough, or it could be, but the storage would then be divided between queues, and some additional external storage for additional data. This would require additional callbacks for cleanup, and make bookeeping convoluted.
So another approach is to have RPC queues …
=> [UNR-5036] Additional facilities to handle event tracing with the modularied RPC system.

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditorSettings.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSettings.h
Made "delete dynamic entities" flag a child of "auto stop deployment" flag so as to disable the ability to toggle it when auto stop is set to OnEndPIE.
=> Unr 4922/update delete dynamic entities flag usage

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialComponentTest/SpatialComponentTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForInterestActor.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForSpawnActor.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestInitialOnly/SpatialTestInitialOnlyForSpawnComponents.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPlayerControllerMigration/SpatialTestPlayerControllerHandover.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestSingleServerDynamicComponents/SpatialTestSingleServerDynamicComponents.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestTearOff/ReplicatedTearOffActor.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestTearOff/ReplicatedTearOffActor.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestTearOff/SpatialTestTearOff.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestClientNetOwnership/SpatialTestNetOwnership.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/UNR-3761/SpatialTestClientNetOwnership/SpatialTestNetOwnership.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/VisibilityTest/VisibilityTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/VisibilityTest/VisibilityTest.h, ci/gdk_build.template.steps.yaml, ci/generate-and-upload-build-steps.sh, ci/setup-build-test-gdk.ps1
Change CI so that it runs tests with the replication graph at a nightly cadence.
Also fixed or otherwise dealt with the tests that would have failed as a result of this.
Copy-pasted dev notes:
```
Fail with native replication graph:
- SpatialTestTearOff
- TearOff can't be called on BeginPlay in RepGraph
- Fix: move to first tick
- SpatialTestInitialOnlyForInterestActor
- Test had a race condition
- Fix: fix the race condition
- SpatialTestInitialOnlyForSpawnActor
- Test had a race condition
- Fix: fix the race condition
- VisibilityTest
- Test just doesn't make much sense with replication graph
- Fix: special-case it so that it tests our expectation for replication graph
- SpatialTestNetOwnership
- Warning is not produced with native replication graph
- It seemingly IS produced with …
```
=> [UNR-4548] Run tests using the replication graph nightly

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
Previously, when a sublevel got unloaded, the actor channels for its actors would be broken by native Unreal. This PR overrides the level unload callbacks on `SpatialNetDriver` so we clean up the channels instead of breaking them and adds an error log to `SpatialActorChannel` to flag if an actor channel gets broken in the future (e.g. if the related code changes in a future engine version).
Additionally, after cleaning up the channel, there was a case where if the sublevel gets unloaded and reloaded fast enough so the temporary loss of interest results in components being refreshed instead of remove and add entity, the newly loaded stably named actors wouldn't have actor channels to process the component refresh. This PR also restores the actor channels for those actors in that situation. …
=> [UNR-4714] Fix level reload crash

SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/CallbacksTest.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialView/Callbacks.h
Stopped callbacks marked as "pending remove" from being invoked.
Fixed associated automated test to verify this behaviour.
=> [UNR-5233] Stopped callbacks marked as "pending remove" from being invoked

SpatialGDK/Source/SpatialGDK/Private/SpatialView/Dispatcher.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/SpatialView/DispatcherTest.cpp
Removing Dispatcher callbacks includes value callbacks, as expected, in addition to added and removed callbacks.
Added an automated test to verify this behaviour, and improved existing automated test coverage that verifies removal of added and removed callbacks.
Automated tests.
=> [UNR-5234] Removing Dispatcher callbacks includes value callbacks

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DebugInterface/SpatialDebugInterfaceTest.cpp
The DebugInterface test had steps which mixed observing changes to actors with changes to the same actors. If workers do not go through these in lock-steps, it could cause some workers to get stuck in a future step.
Fixing it requires separating the steps that poll for changes from the steps that modify the world.
The test will be added back into the CI
=> [UNR-5141] Fix races in the DebugInterface test

RequireSetup, SpatialGDK/Extras/schema/server_worker.schema
`ServerWorkerAuthComponentSet` includes a few components from schema standard library, so we should explicitly include the standard library schema file.
This was causing the Mac CI to fail, and it's unclear why it wasn't causing any problems for the Windows builds.
Ran a Mac build that succeeded:
https://buildkite.com/improbable/unrealgdk-premerge/builds/23990#32bb6b09-3a31-4e57-8430-f13d077d06ca
@ImprobableNic @simonsarginson
=> Explicitly include standard library schema

RequireSetup, SpatialGDK/Extras/schema/debug_component.schema, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverDebugContext.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DebugInterface/SpatialDebugInterfaceTest.cpp
SpatialSubView have a blind spot regarding completeness depending on dynamically added components used as tags.
Since loopback is disabled, component addition won't make it into the view delta, and the view on the authoritative worker won't be updated once it adds the tag.
The debug system has a requirement on receiving authority loss events to properly choose which data to use for load-balancing decisions.
This PR changes how the debug view works by adding a static tag, and a filter on the actual debug component. The query for the debug components still looks for the dynamic components in order to not have every single incomplete actor being tagged in the subview.
Ran the SpatialDebugInterfaceTest with random delays in steps to help trigger the races.
=> [UNR-5141] Fix the debug sub view not getting the locally authoritative components

.buildkite/premerge.steps.yaml
Remove UnrealGDK slack notify as this is now in UnrealGDKBuild
@mironec @simonsarginson
=> Remove UnrealGDK slack notify as this is now in UnrealGDKBuild

SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/GeneratedTestMap.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialAuthorityMap.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialComponentMap.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/TestMaps/GeneratedTestMap.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestAttachedComponentReplication/SpatialTestAttachedComponentReplication.cpp
Minor change to UGeneratedTestMap::AddActorToLevel to return a ref since it does a CastChecked.
Ran the map generation command.
=> Change UGeneratedTestMap::AddActorToLevel to return a ref

.buildkite/premerge.steps.yaml
Labels are used to identify which builds are required by GH. By generating unique labels for each branch we were spamming our GH UI with new builds to watch and also made it impossible to make the old-ci non-required without removing it. This fixes that.
@mironec @simonsarginson
=> Fix labels and messages. Make new ci required.

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/PartiallyStablePathTest/PartiallyStablePathTest.cpp
The test step to receive the server RPC was supposed to be on the tick event. If it's on the start event, there's a chance it would start before the RPC is received, and then it wouldn't call the event again and the step would time out.
@m-samiec
=> Fix a race condition in PartiallyStablePathTest

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerMultiPossessionTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionLockTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionLockTest.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionMap.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionMap.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/CrossServerPossessionTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/NoneCrossServerPossessionTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestRemotePossession.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/SpatialTestRemotePossession.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/TestPossessionPlayerController.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPossession/TestPossessionPlayerController.h
Added cleanup steps for the tests so that the map is reverted to its original state at the end of each test. In all cases this involved restoring possession of the original pawns to the player controllers. For the lock test needed to add support to release locks from netdriver.
Some refactoring was done as there's shared code between the tests and they share a parent class. 
Some fixes were applied to the tests themselves as some didn't achieve their intended functionality.
Ran the tests in CI and on multiple machines multiple times through the Session Frontend.
All Cross-Server Possession Tests.
Starting the tests through …
=> [UNR-5121] Cross server possession tests can't be placed in the same map

SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SnapshotGenerator/SpatialGDKEditorSnapshotGenerator.cpp
The partition shadow component got accidentally merged out in the 0.12 >> master update.
[Commit](https://github.com/spatialos/UnrealGDK/pull/2874/commits/d86dfa2c5437ee6a8e00cfef74405fb33d30cffd)
Re-adding it.
@simonsarginson @mironec
=> Re-add partition shadow component

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialLoadBalancingHandler.cpp
If ShouldHaveAuthority(MyActor) returns false on a worker, but WhoShouldHaveAuthority(MyActor) returns that worker's virtual worker id, then the GDK will log `Attempted to update AuthorityIntent twice to the same value.` The worker will treat that actor as if it has lost authority, but the actor will never be migrated, resulting in a bad state where no worker thinks it is auth over the actor.
This situation doesn't occur (to my knowledge) in GDK load balancing strategies, but can occur in bad custom load balancing strategies, and has proven difficult to track down in the past.
Tested in game code base.
=> [UNR-5046] Duplicate authority intent update bugfix

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
Added the migration diagnostic component to the list of server authority well-known components.
- Fixed an issue with migration diagnostic logging failing, when the actor did not have authority.
To test this locally you can cause a migration failure, one way to do this in comment out the following code in the `ActorSystem` and then run the automated function test: `SpatialTestCharacterMigration`:
```
// bReplicates is not replicated, but this actor is replicated. 
/*if (!Actor->GetIsReplicated()) 
{ 
Actor->SetReplicates(true); 
}*/ 
```
The test should fail and you should see the following migration log:
`Prevented owning actor PlayerController_0 (11)'s hierarchy from migrating because of blocking actor Actor_2 (3016). Originating worker (2) does not have authority of blocking actor. …
=> Fixed an issue with migration diagnostic logging failing.

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp
https://improbableio.atlassian.net/browse/UNR-5425
IsGarbageCollecting() isn't sufficient in this instance, because the call originates from IncrementalPurgeGarbage(), not a garbage collect.
Bugfix: Fixed an issue where during shutdown unregistering NetGUIDs could cause an asset load and program stall.
=> Fix asset load causing stall during shutdown

.buildkite/premerge.steps.yaml
Allowing a single override to be used for both engine majors was a mistake. This removes it. Miron's automated branch matching address this once merged. 
@simonsarginson @mironec
=> Remove engine branch override from RC

SpatialGDK/Source/SpatialGDK/Private/Tests/RPCs/RPCRingBufferTest.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCTypes.h
The RPC queue was looping over the incorrect number of items to move, which caused Array out of bounds, and Memory stomp issues.
=> Fix RPC queue moving incorrect number of items

SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
Returning after allocating `FWorkerComponentUpdate`s leaks memory due to that type not owning the underlying `Worker_ComponentUpdate` allocation.
From what I can see there's no reason to do the authority check that late in the function, so I moved it up. This also means we don't send traces for replicating data we then don't send.
Another way to fix this is to just remove the authority check altogether, though it's not clear if we are now guaranteed to not hit this check.
TODO. Is this worth a changelog note?
N/A
=> Move SendComponentUpdates early out to avoid memory leak

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/SpatialComponentMap.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestHandoverReplication/SpatialTestHandoverActorComponentReplication.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestHandoverReplication/SpatialTestHandoverActorComponentReplication.h
Previously if a handover struct had handover member variables in it, schema would be generated for the inner members, even though they would not be used during runtime, as we don't support flattening handover structs. This produced errors as a result of UNR-3128.
Fix here is to not generate the schema for these inner members. The proper long term fix is to support flattened handover structs.
Probably not required?
Modified a test to also check for this.
N/A
@m-samiec @improbable-dmitrii
=> [UNR-5404] Fix error with flattened handover structs

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp
Fix issue where  on startup blueprint streamed levels would immediately trigger an unload and an attempted tombstone creation before entity pool was complete. 
The fix was to check the world was in a correct state before allowing tombstone to be created for it. Additionally added a check that we don't attempt to create tombstones with INVALID_ENTITY_ID which was breaking connection to runtime.
=> Fix bad tombstone creations

SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKServices/LocalDeploymentManager/LocalDeploymentManagerUtilities.cpp
Prevent async calls from being able to spam the deployment manager and crash the editor.
Repro steps in https://improbableio.atlassian.net/browse/UNR-5390 no longer crash the editor when Graceful Runtime Shutdown is enabled
@MatthewSandfordImprobable  @improbable-danny
=> Fix graceful shutdown spam crashing the editor

SpatialGDK/Source/SpatialGDKEditor/Private/SpatialTestSettings.cpp
Fixed path to base overrides test setting, which was broken by a recent change to specify test overrides.
=> Fix test override base

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverDebugContext.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialVirtualWorkerTranslationManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSetWriter.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialClassInfoManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialDispatcher.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialSender.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LayeredLBStrategy.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/OwnershipLockingPolicy.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/SpatialMultiWorkerSettings.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityPool.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/Interest/NetCullDistanceInterest.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/RPCContainer.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebuggerSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialMetricsDisplay.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverDebugContext.h, SpatialGDK/Source/SpatialGDK/Public/Interop/CreateEntityHandler.h, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCTypes.h, SpatialGDK/Source/SpatialGDK/Public/Schema/MigrationDiagnostic.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h
Use ensures over checks because middleware shouldn't be crashing any games. 
High-level tenets:
* General rule of thumb: use ensures over checks
* Checks in any debugging / utility / logging code should be removed
* Checks in code that's part of a direct user API (highly susceptible to bad input) should be removed
* Checks in places where state means a client is wrecked but the server could remain healthy should be removed
* Checks can still exist in fundamental locations, e.g. trying to initialize core load balancing classes but NetDriver is undefined
=> Downgrade aggressive GDK checks

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/RelevancyTest/RelevancyTest.cpp
Removed the non-default 5 second timeout in the timesteps in place for 
Not necessary
Ran the test multiple times locally and on CI.
Trigger multiple builds on CI that run the functional tests.
Not needed
=> [UNR-5497] RelevancyTest is flaky

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp
It seemed that this code was only triggered by blueprint-referenced sublevels but it seems that as part of LoadMap that this can actually happen in at least one other scenario (ChildActorComponent::OnRegister). It seems the best course of action is to ignore all actor deletion prior to World::BeginPlay, as all other Actor::BeginPlay are triggered after this point. 
The reason we didn't see this before is because there is a race around PackageMap, if the Spatial connection isn't fully connected yet (which is the case usually in PIE) then this code is not hit at all due to the PackageMap != null condition. 
See 
UE4Editor-Engine-Win64-Debug.dll!AActor::BeginPlay Line 3702
UE4Editor-Engine-Win64-Debug.dll!AStaticMeshActor::BeginPlay Line 58 …
=> Tombstone logging for destroyed actors before BeginPlay triggering errors during map load

CHANGELOG.md, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKEditor.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbar.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Private/SpatialGDKEditorToolbarCommands.cpp, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbar.h, SpatialGDK/Source/SpatialGDKEditorToolbar/Public/SpatialGDKEditorToolbarCommands.h
This change
- Fixes the bug, where if a schema gen failed, the SchemaDatabase.uasset would stay in a locked state and couldn't be deleted (see note below).
- Adds a menu option for cleaning and regenerating schema (ie, deletes the schema database, the schema generated folder, and runs a full scan).
- Adds a pop-up menu prompt that comes up when schema generation fails, asking the user if they would like to clean and regenerate schema (This is meant to help unblock the average user who doesn't think about schema, since most issues can be fixed with a clean and regen -- this prompt would likely have saved some hours of dev time based on what I saw on Scavengers)
Note: I'm not super sure about the fix to unlock the SchemaDatabase.uasset. What I saw happening was that schema generation begins …
=> UNR-5318 Fix (Invalid schema state if schema fails to generate)

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverRPC.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/EntityFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverRPC.h, SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealObjectRef.h
Contains the following modifications : 
1. Ensure FUnrealObjectRef::bNoLoadOnClient has a value that indicates if the referenced object can be resolved and loaded from a remote worker
2. Use FUnrealObjectRef::bNoLoadOnClient in the RPC application callbacks to know if we can wait longer than the RPC timeout. This is useful for objects asynchronously loaded.
3. A driveby fix, for a bug spotted while sending for a reliable and an unreliable RPC to a new actor in the new RPC service implementation. We did not merge data from different queues that targeted the same component. Now both Data and Updates are properly merged.
Added https://github.com/spatialos/UnrealGDKTestGyms/pull/366
=> [UNR-5415] Fix RPC parameter timeout around objects that can be locally loaded.

SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentReader.cpp
* Increment `SPATIAL_ENGINE_VERSION` in `Engine\Source\Runtime\Launch\Resources\SpatialVersion.h` (in the engine fork) as well as `SPATIAL_GDK_VERSION` in …
=> Downgrade check to error log in ApplyProperty

SpatialGDK/Source/SpatialGDKTests/Public/GDKAutomationTestBase.h
Context: After a functional test finishes we do not shut down the deployment. This saves us time in CI. This does mean that the next automated test will start with an already existing deployment running. This is where the warning came from. 
Potential fixes for this issue:
1. Demote warning to log
2. Shuffle all functional tests to the end of the test run.
3. Have a means of having a functional test shutdown the runtime when it finishes.
1. Seemed most appropriate as we 100% know this code path will be hit. 
2. Bad practice really...
3. Would require a sizable amount of work to ensure that deployments are not shutdown when a functional test finishes when the next test is another functional test and only in the case where the next test is an automated test.
What is most important here is …
=> Demote Warning to Log

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp
Switch from calling member directly to using GetSpatialWorkerId()
Built this locally with tracelibs enable but nothing significant past that.
Build it with tracelibs enabled, run an NFR scenario.
Fixed NFR Run: https://buildkite.com/improbable/unrealgdk-nfr/builds/5033
This is a fix for something which broke the nightly NFRs. Thanks to Jane for pinpointing this issue.
Broken nightly nfr: https://buildkite.com/improbable/unrealgdk-nfr/builds/5029#1c865c46-ed92-41f3-ac10-31f07e8bb55d
@martin-improbable @m-samiec @Jane-XuJingyi
=> UNR-5551 - Use GetSpatialWorkerId in Tracelib Enabled Code

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestLoadBalancingData/SpatialTestLoadBalancingData.cpp
Increased timeouts in the timesteps by setting them to the default (20 seconds) and added an IsActorReady check to avoid potential nullptr on other servers.
Not required.
Ran the test multiple times on CI and locally.
Trigger multiple builds which run the functional tests on CI.
Not required.
=> [UNR-5324] SpatialTestLoadBalancingData is flaky

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverRPC.cpp
There was an additional path, when tracing was enabled, which pushed a new update item on the update queue. This path forgot to initialize the schema object to null.
=> [UNR-5557] Initialize pointer in tracing callback

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialWorldSettings.h, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialTestSettings.cpp
Made the settings override the file path relative to the game directory.
Added an error message if a file is specified but cannot be found.
- Fixed the test settings overrides config filename in the `World Settings` so that the file path is relative to the game directory.
Run automated functional tests locally.
Release note
=> Fix settings override path

CHANGELOG.md, SpatialGDK/Source/SpatialGDKServices/Private/LocalDeploymentManager.cpp, SpatialGDK/Source/SpatialGDKServices/Public/LocalDeploymentManager.h
before, multiple threads could attempt to shut down the runtime at the same time. Sometimes the runtime took a long time to shut down, and unreal's main thread called the destructor of `LocalDeploymentManager` while that other thread was still running on the shutdown runtime method/s.
This fixes that
`Fix editor encountering exceptions when shutting down during a PIE session.`
I saw I could follow repro steps and it no longer crashed
none
see linked ticket for repro steps
release note
If your change will take a long time to review, you can name at most two primary reviewers who are ultimately responsible for reviewing this …
=> [UNR-5524] make ending deployment during PIE thread safe

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h
Changed GetActorEntityId() to not lazy construct an entityid, and the API to be const.
Manual.
=> [UNR-5438] Change UNetDriver GetActorEntityId to not lazy construct

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h
Broadcast network failure if any network errors occurred at the end of the TickDispatch function.
Prevented client crash that occurs if there is a mismatch between the client and server schema hash.
Manual tests using the repro steps in the JIRA ticket.
Release note.
=> Client crash schema hash mismatch 

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/DebugInterface/SpatialDebugInterfaceTest.cpp
Disable the DebugInterface test until either we get time to debug it, or we decide what to do with flaky tests.
=> Disable TestDebugInterface because of flakyness.

CHANGELOG.md, RequireSetup, Setup.sh
* Fixes: [UNR-5610](https://improbableio.atlassian.net/browse/UNR-5610) - UnrealGDK/Setup.sh throws `sed: can't read : No such file or directory`
* This defect was discovered while I was working on: https://github.com/improbableio/UnrealEngine/pull/953
See CHANGELOG.
* Tested on macOS Big Sur
* Tested the full install path, the incremental install path, the CN & Mobile paths
CHANGELOG entry will suffice.
If your change updates `Setup.bat`, `Setup.sh`, core SDK version, any C# tools in `SpatialGDK\Build\Programs\Improbable.Unreal.Scripts`, or hand-written schema in `SpatialGDK\Extras\schema`:
* Increment the number in `RequireSetup`. This will automatically run `Setup.bat` or `Setup.sh` when the GDK is next pulled.
=> Fixes UNR-5610 - UnrealGDK/Setup.sh throws `sed: can't read : No such file or directory`

SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/InterestFactory.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SpatialActorUtils.h
This PR changes the `InterestFactory` to add an extra query to `GameplayDebuggerCategoryReplicator` actors ensuring that the auth server can see the owning `PlayerController`. Right now, this is a no-op change since the auth server for the player controller and the replicator are always the same one, so interest is maintained through authority. However, once we start decoupling them (see [design doc](https://brevi.link/multiworker-gameplay-debugger-design)) we have to ensure that whatever server gains authority over the replicator doesn't lose track of the owning player controller actor.
N/A, will follow as part of full feature release
Inspector shows the query being successfully added in the multi worker world composition gym:
In this case, entity 3009 is the one representing the player …
=> UNR-5530 Gameplay debugger interest setup

SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx
https://github.com/spatialos/UnrealGDK/commit/56779ef86994a89143baf222d60999d4d0680cfa added this dependency without include. Patch fix.
=> Fix server only schema include

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialGameInstance.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/CrossServerRPCSender.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/ViewCoordinator.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialWorkerConnection.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/SpatialOSWorker.h, SpatialGDK/Source/SpatialGDK/Public/SpatialView/ViewCoordinator.h
Create an interface wrapping the functionality of the ViewCoordinator to later be used in public interfaces.
Along with some minor change. Moved the order of functions around to be more sensible and removed the non-retry variants of the command senders as they aren't used and don't add extra functionality.
=> unr-5322 view coordinator interface

CHANGELOG.md, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowControllerSpawner.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestFlowController.h
Reverted https://github.com/spatialos/UnrealGDK/pull/3175 . This caused native tests to fail as the number of registered clients was wrong.
=> Revert "Fix spatial flow controller registration" 

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialCleanupConnectionTest/SpatialCleanupConnectionTest.cpp
Added missing 'ActorReady' verification step, to ensure actor is ready before later steps are executed.
=> Added missing 'ActorReady' check to SpatialCleanupConnectionTest

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/StaticSubobjectsTest/StaticSubobjectsTest.cpp
There is a mismatch between spatial and native in how pointers to deleted objects are replicated (i.e. native sets them to NULL, spatial doesn't?)
Because of this, the test wasn't passing in native. This fixes that.
static subobjects test
static subobjects test
fixing something that went in today
=> fix static subobjects test not passing in native

CHANGELOG.md, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowController.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/SpatialFunctionalTestFlowControllerSpawner.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Public/SpatialFunctionalTestFlowController.h
Re-revert for the original fix now that https://github.com/improbableio/UnrealEngine/commit/67b19471da6744c16ea8a3e9aba5ba3144637d89 (and the 4.25 version) are in.
Original: https://github.com/spatialos/UnrealGDK/pull/3175/
=> [UNR-5579] Re-fix too many spatial flow controllers

SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialView/SubView.cpp, SpatialGDK/Source/SpatialGDK/Public/SpatialView/SubView.h
As part of https://github.com/spatialos/UnrealGDK/pull/3030/files `GetCompleteEntities` was refactored to provide any entity state that was is the process of being complete this frame (between dispatcher invoke and subview advance). In practice this isn't needed, and is a huge performance hit, so reverting to using the CompleteEntities array instead.
@improbable-dmitrii
=> Revert CompleteEntity recalculation

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
Fix for dormancy checking if there are pending ops waiting on an actor.
Dormant actors will now have their channels correctly closed when entering dormancy.
@ImprobableNic
=> Fixed dormancy unresolved ref checking

SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialEventTracer.h
Sampling probability should only affect spans. Currently if a span should not be sampled we don't create an event.
=> Correctly handle sampling of spans

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/SpatialTestReplicationConditions.cpp
This fixes a bug you can only trigger manually by running the SpatialTestReplicationConditions test manually in the session frontend with spatial turned off (it does not run in CI because its in the spatial only folder).
=> Fix ASpatialTestReplicationConditions COND_Custom test

SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialEventTracer.cpp, SpatialGDK/Source/SpatialGDK/Private/SpatialGDKSettings.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/Connection/SpatialEventTracer.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDKEditor/Private/SpatialGDKDefaultLaunchConfigGenerator.cpp
Warnings were being fired when a "None" ET sampling settings object was being used when ET was enabled. This was due to us not being able to parse a valid filter on the sampling settings.
To get around this filters now default to "false" so that None and new ET sampling settings assets are valid by default. 
Additionally moved a bit of the logic into the settings to allow the settings to always return valid filters in whatever form they are needed.
=> Fixing ET Settings Warnings

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStrategySystem.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LBDataStorage.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingStrategy.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/PartitionManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Schema/ActorOwnership.h, SpatialGDK/Source/SpatialGDK/Private/Schema/StaticSymbols.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStrategySystem.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LBDataStorage.h, SpatialGDK/Source/SpatialGDK/Public/Schema/ActorGroupMember.h, SpatialGDK/Source/SpatialGDK/Public/Schema/ActorSetMember.h, SpatialGDK/Source/SpatialGDK/Public/Schema/AuthorityIntent.h, SpatialGDK/Source/SpatialGDK/Public/Schema/DebugComponent.h, SpatialGDK/Source/SpatialGDK/Public/Schema/GameplayDebuggerComponent.h, SpatialGDK/Source/SpatialGDK/Public/Schema/Interest.h, SpatialGDK/Source/SpatialGDK/Public/Schema/MigrationDiagnostic.h, SpatialGDK/Source/SpatialGDK/Public/Schema/NetOwningClientWorker.h, SpatialGDK/Source/SpatialGDK/Public/Schema/PlayerSpawner.h, SpatialGDK/Source/SpatialGDK/Public/Schema/Restricted.h, SpatialGDK/Source/SpatialGDK/Public/Schema/ServerWorker.h, SpatialGDK/Source/SpatialGDK/Public/Schema/SnapshotVersionComponent.h, SpatialGDK/Source/SpatialGDK/Public/Schema/SpatialDebugging.h, SpatialGDK/Source/SpatialGDK/Public/Schema/SpawnData.h, SpatialGDK/Source/SpatialGDK/Public/Schema/StandardLibrary.h, SpatialGDK/Source/SpatialGDK/Public/Schema/Tombstone.h, SpatialGDK/Source/SpatialGDK/Public/Schema/UnrealMetadata.h
Preparing some facilities in order to start working on a way to expose partition metadata to unreal server workers (to implement things like the test debug interface, amongst other things).
There was a lot of boilerplate code to extract data and updates from sub views, which could be united into a single utility class, and used everywhere we want to extract some collection of data.
This comes along with a template data storage which wraps the component classes we write for our custom components, in order to further reduce the amount of boilerplate code needed to pass component data around.
Read in commit order.
Had to fix an obscure linking error for Clang in C++14 (UE 4.25) : https://stackoverflow.com/questions/8016780/undefined-reference-to-static-constexpr-char
=> Additional facilities for getting LB data and cleanup of the systems using them

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/Interest/NetCullDistanceInterest.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialActorChannel.h
Small usability tweaks based on NFR work.
1. Expose last updated spatial actor position
2. Call GetSpatialActorPosition only once in a standard update
3. Don't create interest queries with invalid distance constraints
=> Small tweaks

SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialRoutingSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/TestRoutingWorker.cpp, SpatialGDK/Source/SpatialGDK/Public/Utils/CrossServerUtils.h
The routing worker had a couple of edge cases that were not handled when a receiver was missing, or arrived too late into the view.
Ran SpatialEntityInteractionTest, and checked that the crash did not appear (test could fail for other reasons though, see https://improbableio.atlassian.net/browse/UNR-5780)
=> [UNR-5762] Avoid a crash in the routing worker in case of interest races on the receiver

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/Private/TestMaps/Spatial2WorkerMap.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialActorResolutionTest/SpatialActorResolutionTest.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialActorResolutionTest/SpatialActorResolutionTest.h
Reapplied a part of the fix introduced in UNR-4849 and added a functional test covering this functionality.
The flow of the bug is:
1. Create a replicated actor
2. This actor is replicated for the first time and has an entity created for it
3. The actor is destroyed before we've received the entity from the Runtime; we save this entity ID as EntityToRetireOnAuthorityGain.
4. We receive the entity and try to create it.
The fix is first checking for the entity to be an EntityToRetireOnAuthorityGain, and not creating an actor for it in such a case.
Added a release note.
I've added a new functional test and ran the existing test suite.
Release note.
=> UNR-5752: Fixed an error caused by destroying an actor between entity creation and confirmation thereof

.buildkite/premerge.definition.yaml
Reverts: https://github.com/spatialos/UnrealGDK/pull/3176
We were forced to pick a [different approach](https://improbableio.atlassian.net/browse/UNR-4903?focusedCommentId=451317).
The `circle ci pipeline check` output for this change is:
```ERRO Pipeline not as expected, would apply the following diff:
@@ -4,10 +4,10 @@
ID: ""
Name: unrealgdk-premerge
ProviderSettings:
-  branch_configuration: '!dry-run/* !skip-ci/* !doc/* !docs/*'
+  branch_configuration: ""
publish_commit_status_per_step: true
-  pull_request_branch_filter_configuration: '!dry-run/* !skip-ci/* !doc/* !docs/*'
-  pull_request_branch_filter_enabled: true
+  pull_request_branch_filter_configuration: ""
+  pull_request_branch_filter_enabled: false
Repository:
url: git@github.com:spatialos/UnrealGDK.git
Slug: ""
=> Reverts PR #3176

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialPackageMapClient.h
Running the GDK I encounter a dynamic subobject (AutoDestroyActor component) that already has a netguid->objectref/objectref->netguid mapping in spatialguidmap when running resolvesubobject while the object itself does not have a netguid/does not exist within the standard guidmap.
Related is https://improbableio.atlassian.net/browse/UNR-5785 (see for repro steps)
`- Fixed an issue that could cause SpatialNetGuidCache and native's NetGuidCache to become out of sync.`
=> Spatialguidmap has an objectref->netguid mapping that should have been deleted

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialStatics.cpp
SpatialSwitchHasAuthority now respects World's version of IsServer which assumes server status when NetDriver is null.
=> Update SpatialSwitchHasAuthority to check NetDriver via World

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/StaticSubobjectsTest/StaticSubobjectsTest.cpp
Fix the nightly tests by making the StaticSubobjectTest leave the pawn in a good location, so the UnresolvedReferenceTest can proceed smoothly. Interestingly, this only seems to be required in Native, as in Spatial the cleanup possession at the end of the StaticSubobjectTest seems to be sufficient.
N/A
Ran locally
N/A
@MCArth-improbable
=> [UNR-5812] Fix nightly test failures - UnresolvedRefTest in Native

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/ActorSystem.h
In this PR I have moved the tearing off of channels that have been newly marked as tear off (and we noticed after  an applycomponentupdate), to after rep notifies.
Why:
The TearOff test started failing after https://github.com/spatialos/UnrealGDK/pull/3268/files was merged, due to the `Failed to invoke rep notifies for an object as its entity id was invalid` warning.
However, that PR did not actually break tearoff. The reason it surfaced there was because I removed the early out clause for repnotifies.
```
void ActorSystem::TryInvokeRepNotifiesForObject(FWeakObjectPtr& WeakObjectPtr, FObjectRepNotifies& ObjectRepNotifies) const
{
if (ObjectRepNotifies.RepNotifies.Num() == 0)
{
return;
}
```
The change that broke this was the change that moved repnotifies for all entities till after all …
=> Move tear off channels after rep notifies

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/AlwaysInterestedTestActors.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/TestActors/RelevancyTestActors.cpp
Reverts spatialos/UnrealGDK#3282
Failing rep graph nightlies
=> Revert "Cleanup NCD values"

SpatialGDK/Extras/schema/server_worker.schema, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialServerWorkerSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/Connection/SpatialWorkerConnection.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialServerWorkerSystemImpl.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialServerWorkerSystemImpl.h, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStrategySystem.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/ActorSetSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LBDataStorage.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingStrategy.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyServerWorkerSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/PartitionManager.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriver.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialServerWorkerSystem.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStrategySystem.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/ActorSetSystem.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LBDataStorage.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyLoadBalancingStrategy.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyServerWorkerSystem.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LoadBalancingStrategy.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/PartitionManager.h, SpatialGDK/Source/SpatialGDK/Public/SpatialGDKSettings.h, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h, SpatialGDK/Source/SpatialGDKEditorCommandlet/Private/Commandlets/CookAndGenerateSchemaCommandlet.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Add server a serverworker subsystem which allows per-worker information to be published to the centralized load balancer.
Also contains a couple of driveby, to clear the modified entities at the beginning of each advance/update steps, instead of doing it explicitely.
=> [UNR-5632] Add ServerWorker System

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/ReplicatedTestActorSubobject.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/ReplicatedTestActorSubobject.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestPropertyReplication/SpatialTestPropertyReplicationSubobject.cpp
The subobject test was actually testing another actor, which is redundant, and introduced races in the way it was setup.
Since we actually want to test subobjects, changed the test to be about actor components instead, since this is something we will be interested in eventually.
=> [UNR-5849] Make subobject test about actor component, instead of a spawned actor.

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriver.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverDebugContext.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStrategySystem.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/DebugLBStrategy.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/GridBasedLBStrategy.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LBDataStorage.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyLoadBalancingStrategy.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/LegacyServerWorkerSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/PartitionManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Schema/StaticSymbols.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverDebugContext.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/AbstractLBStrategy.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/DebugLBStrategy.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyLoadBalancingStrategy.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LegacyLoadbalancingComponents.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LoadBalancingStrategy.h, SpatialGDK/Source/SpatialGDK/Public/LoadBalancing/LoadBalancingTypes.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaOption.h
Implements the test debug strategy in the centralized load balancer.
This requires data to be published in the various server workers, and interpreted on the centralized load balancer, to manipulate interest and authority accordingly.
TestDebugInterface and SpatialTestPlayerControllerHandover use this feature.
=> [UNR-5632] Implement the test debug interface in the strategy worker

SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/CrossServerRPCService.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/RPCs/SpatialRPCService.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialRoutingSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/Tests/TestRoutingWorker.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/CrossServerRPCService.h, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/RPCStore.h, SpatialGDK/Source/SpatialGDK/Public/Interop/RPCs/SpatialRPCService.h
When encountering race conditions around entity interest when sending/receiving RPCs, RPCs that fail to send due to 'TargetUnknown' are immediately resent. 
Alternative solutions like 'blank entities' might be considered in the future.
Automated test.
=> [UNR-5780] Handle races on interest for routing worker

CHANGELOG.md, RequireSetup, SpatialGDK/Extras/core-sdk.version, SpatialGDK/Source/SpatialGDK/Public/Utils/WorkerVersionCheck.h
UE 426: https://github.com/improbableio/UnrealEngine/pull/1043
UE 425: https://github.com/improbableio/UnrealEngine/pull/1042
GDK: https://github.com/spatialos/UnrealGDK/pull/3309
Test Gyms: https://github.com/spatialos/UnrealGDKTestGyms/pull/466
Example: https://github.com/spatialos/UnrealGDKExampleProject/pull/299
Engine Net Test: https://github.com/improbable/UnrealGDKEngineNetTest/pull/99
=> [UNR-5875] Update worker sdk to 15.1.1

SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Public/SpatialGDKEditorSchemaGenerator.h
Our tests were timing out on when running nightlies.
This was because the nightly tests run as follows:
- Fast Tests
- Slow Tests (inc schema gen tests)
- RepGraph Tests <--- Tests fail and timeout
The Slow Tests with schema gen tests were wrecking the compiled schema binary (schema.sb) which was used in following runs. This is due to https://github.com/spatialos/UnrealGDK/commit/d767ba0e2a5170f52eb071ef62756bc029a91148 
What's happening is the new additional run of `SchemaCompiler` as part of the final test in `CreateServerWorkerAuthoritySet` https://github.com/spatialos/UnrealGDK/commit/2c6620cde8db612fa4e5dc2ec7063283e1b241b4 
causes the schema binary used by the runtime to get nuked. This causes the next test which uses the runtime to enter a bad state and thus timeout. 
This only …
=> UNR-5896 - Test Timeouts

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/ActorSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/ComponentFactory.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialClassInfoManager.h, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialConditionMapFilter.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.cxx, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDK/Public/Utils/EngineVersionCheck.h, SpatialGDK/Source/SpatialGDK/Public/Utils/SchemaDatabase.h, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/SpatialGDKEditorSchemaGenerator.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.cpp, SpatialGDK/Source/SpatialGDKEditor/Private/SchemaGenerator/TypeStructure.h, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/SpatialTestReplicationConditions.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/TestReplicationConditionsActor.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/TestReplicationConditionsActor.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SchemaGenObjectStub.cpp, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SchemaGenObjectStub.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Added an auth server only replication type and updated labeled
applicable areas of the GDK.
Engine 4.26 change: https://github.com/improbableio/UnrealEngine/pull/1061
Engine 4.27 change: https://github.com/improbableio/UnrealEngine/pull/1058
How did you test these changes prior to submitting this pull request? In customer's codebase.
updated SpatialGDKSchemaGeneratorTest
* Increment `SPATIAL_ENGINE_VERSION` in `Engine\Source\Runtime\Launch\Resources\SpatialVersion.h` (in the engine fork) as well as `SPATIAL_GDK_VERSION` in `SpatialGDK\Source\SpatialGDK\Public\Utils\EngineVersionCheck.h`. This helps others by providing a more helpful message during compilation to make sure the GDK and the …
=> Add Only Authoritative Server Replication

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/VisibilityTest/VisibilityTest.cpp
Fixing our tests when running with repgraph enabled. We now have parity with native concerning hidden actors.
=> Check the same behaivour between spatial and native when repgraph is enabled

SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/InterestManager.cpp
Android broke in [previous ](https://github.com/spatialos/UnrealGDK/pull/3339), looks like a mismatch in clang versions being included. Removing include until resolved.
=> Fix android

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp
When replicating an empty subobject (such as a simulated task in the test gym where this crash was found, https://improbableio.atlassian.net/browse/UNR-5971), the `Cmds` array in `RepLayout` will only have one element, which is the return command. The previous logic would try to check the `Parent` command, but the `Parents` array would actually be empty in that case.
As far as I could tell, this would be the only case where the `Parents` array could be empty, so we can still assume that `Cmd.ParentIndex` is a valid index into the array as long as it's not the return command.
Also, this might fix another edge case where previously the RepMovement check would skip the return command if the first element in the `Parents` array was inactive (haven't actually tested this, but I'm assuming this …
=> Fix crash when trying to replicate empty subobject

RequireSetup, SpatialGDK/Extras/core-sdk.version, SpatialGDK/Extras/schema/skeleton_entity.schema, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPackageMapClient.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SkeletonEntityManifestPublisher.cpp, SpatialGDK/Source/SpatialGDK/Private/Interop/SpatialStrategySystem.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/InterestManager.cpp, SpatialGDK/Source/SpatialGDK/Private/LoadBalancing/PartitionManager.cpp, SpatialGDK/Source/SpatialGDK/Private/Schema/ChangeInterest.cpp, SpatialGDK/Source/SpatialGDK/Private/Utils/InterestFactory.cpp, SpatialGDK/Source/SpatialGDK/Public/Interop/SpatialStrategySystem.h, SpatialGDK/Source/SpatialGDK/Public/Schema/ChangeInterest.h, SpatialGDK/Source/SpatialGDK/Public/SpatialConstants.h, SpatialGDK/Source/SpatialGDK/Public/Utils/WorkerVersionCheck.h, SpatialGDK/Source/SpatialGDKTests/SpatialGDKEditor/SpatialGDKEditorSchemaGenerator/SpatialGDKEditorSchemaGeneratorTest.cpp
Add new "true constraint" on strategy worker to remove need for QBI.
Add self constraint on GSM worker to remove last QBI query. 
The GSM was previously getting interest in the `SKELETON_ENTITY_MANIFEST_COMPONENT_ID` entities via a component constraint on the GSM entity. This has been reworked to give the GSM worker authority over a new tag component we add to the skeleton entity manifest entities, and then uses self-interest to gain interest in the rest of the entity. 
I'll leave the QBI queries within the snapshot entities for now, until we fully shift to USI.
=> Add usi support to strategy worker

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialActorChannel.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/SpatialTestReplicationConditions.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/TestReplicationConditionsActor.cpp, SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestReplicationConditions/TestReplicationConditionsActor.h
This check wasn't accounting for inactive dynamic arrays.
Fix for recent change, no release note.
=> Correct cond custom replication

SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialPartitionSystem.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialServerWorkerSystem.cpp
Ensures were being fired in Spatial subsystems when starting a game instance that wasn't a `USpatialGameInstance`.
This should not be happening in non-GDK projects when Spatial networking is disabled.
None, this fixes unreleased code.
Manual:
1. Open a non-GDK project with a GDK engine.
1. Make sure `Spatial Networking` is unchecked.
1. Start a play session.
1. Ensures should not be hit in Spatial systems.
@m-samiec
=> Fix ensure hit for non-GDK projects in Spatial subsystems

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialNetDriverAuthorityDebugger.cpp, SpatialGDK/Source/SpatialGDK/Private/EngineClasses/SpatialShadowActor.cpp, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialNetDriverAuthorityDebugger.h, SpatialGDK/Source/SpatialGDK/Public/EngineClasses/SpatialShadowActor.h
https://improbableio.atlassian.net/browse/INT-124
Two small improvements to shadow actor checking;
1. Client's don't error against server-only replicated properties
2. Added autonomous proxy filter for clients and included "Pawn" in it, as it can be set preemptively by clients during possession.
@improbable-dmitrii
=> Better checking of actor's shadow data

CHANGELOG.md, SpatialGDK/Source/SpatialGDK/Private/Interop/GlobalStateManager.cpp
When running PIE in multiple processes, the shutdown command won't reach the other servers before they're killed by normal UE PIE stop flow. Added a flush and a wait to allow for the command to be delivered.
Added a changelog note.
Ran `Snapshot reloading test`.
A changelog note.
=> INT-126: Fixed server workers launched via multiple processes PIE not receiving the shutdown command

SpatialGDK/Source/SpatialGDK/Private/Interop/ClientConnectionManager.cpp
Demoted an ensure triggered during SnapshotReloadingTest down to a warning as this case is potentially possible unless handled in a systematic fashion.
=> INT-126: Demoted the missing worker entity ensure down to a warning

SpatialGDK/Source/SpatialGDKFunctionalTests/SpatialGDK/SpatialTestRPCTimeout/SpatialTestRPCTimeout.cpp
Stop RPC timeout test running in native.
=> Disabling run under single process doesn't work in native

SpatialGDK/Source/SpatialGDK/Private/Utils/SpatialDebugger.cpp
Companion PR for https://github.com/spatialos/UnrealGDKTestGyms/pull/299
=> Disable spatial debugger tick when running a replay
